// Generated by scripts/generate-tsrx-types.mjs.
import type { BaseDatum, CloudWord, WordcloudConfig } from './types';
export type WordBounds = {
    left: number;
    right: number;
    top: number;
    bottom: number;
};
/**
 * Estimates the axis-aligned rectangle occupied by a laid-out word. The same
 * browser-independent metric is used for collision checks during SSR and the
 * first client render.
 */
export declare function getEstimatedWordBounds(word: Pick<CloudWord, 'padding' | 'rotate' | 'size' | 'style' | 'text' | 'weight' | 'x' | 'y'>): WordBounds;
export declare function layoutWordcloud<Datum extends BaseDatum>({ width, height, font, fontSize, fontStyle, fontWeight, padding, random, rotate, spiral, words, }: WordcloudConfig<Datum>): CloudWord[];
export default function useWordcloud<Datum extends BaseDatum>(config: WordcloudConfig<Datum>): CloudWord[];
