// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { BaseDatum, CloudWord, WordcloudConfig } from './types';
export interface WordcloudProps<Datum extends BaseDatum> extends WordcloudConfig<Datum> {
    children: (words: CloudWord[]) => OctaneNode;
}
export default function Wordcloud<Datum extends BaseDatum>(props: WordcloudProps<Datum>): import("react").JSX.Element | null;
