// Declaration companion for createFormHook.tsrx, adapted from the
// @tanstack/react-form 1.33.2 declaration surface to Octane renderer types.
import { AnyFieldApi, AnyFormApi, BaseFormOptions, DeepKeysOfType, FieldApi, FieldsMap, FormAsyncValidateOrFn, FormOptions, FormValidateOrFn } from '@tanstack/form-core';
import type { Context } from 'octane';
import { FieldComponent } from './useField.tsrx';
import { OctaneFormExtendedApi } from './useForm.tsrx';
import { AppFieldExtendedOctaneFieldGroupApi } from './useFieldGroup.tsrx';
type HookRenderable = unknown;
type HookPropsWithChildren<P = object> = P & {
    children?: HookRenderable;
};
type HookFunctionComponent<P = object> = (props: P) => HookRenderable;
type HookComponentType<P = object> = HookFunctionComponent<P>;
/**
 * TypeScript inferencing is weird.
 *
 * If you have:
 *
 * @example
 *
 * interface Args<T> {
 *     arg?: T
 * }
 *
 * function test<T>(arg?: Partial<Args<T>>): T {
 *     return 0 as any;
 * }
 *
 * const a = test({});
 *
 * Then `T` will default to `unknown`.
 *
 * However, if we change `test` to be:
 *
 * @example
 *
 * function test<T extends undefined>(arg?: Partial<Args<T>>): T;
 *
 * Then `T` becomes `undefined`.
 *
 * Here, we are checking if the passed type `T` extends `DefaultT` and **only**
 * `DefaultT`, as if that's the case we assume that inferencing has not occurred.
 */
type UnwrapOrAny<T> = [unknown] extends [T] ? any : T;
type UnwrapDefaultOrAny<DefaultT, T> = [DefaultT] extends [T] ? [T] extends [DefaultT] ? any : T : T;
declare function useFormContext(): OctaneFormExtendedApi<Record<string, never>, any, any, any, any, any, any, any, any, any, any, any>;
export declare function createFormHookContexts(): {
    fieldContext: Context<AnyFieldApi>;
    useFieldContext: <TData>() => FieldApi<any, string, TData, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any>;
    useFormContext: typeof useFormContext;
    formContext: Context<AnyFormApi>;
};
interface CreateFormHookProps<TFieldComponents extends Record<string, HookComponentType<any>>, TFormComponents extends Record<string, HookComponentType<any>>> {
    fieldComponents: TFieldComponents;
    fieldContext: Context<AnyFieldApi>;
    formComponents: TFormComponents;
    formContext: Context<AnyFormApi>;
}
/**
 * @private
 */
export type AppFieldExtendedOctaneFormApi<TFormData, TOnMount extends undefined | FormValidateOrFn<TFormData>, TOnChange extends undefined | FormValidateOrFn<TFormData>, TOnChangeAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnBlur extends undefined | FormValidateOrFn<TFormData>, TOnBlurAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnSubmit extends undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnDynamic extends undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnServer extends undefined | FormAsyncValidateOrFn<TFormData>, TSubmitMeta, TFieldComponents extends Record<string, HookComponentType<any>>, TFormComponents extends Record<string, HookComponentType<any>>> = OctaneFormExtendedApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta> & NoInfer<TFormComponents> & {
    AppField: FieldComponent<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, NoInfer<TFieldComponents>>;
    AppForm: HookComponentType<HookPropsWithChildren<{}>>;
};
export interface WithFormProps<TFormData, TOnMount extends undefined | FormValidateOrFn<TFormData>, TOnChange extends undefined | FormValidateOrFn<TFormData>, TOnChangeAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnBlur extends undefined | FormValidateOrFn<TFormData>, TOnBlurAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnSubmit extends undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnDynamic extends undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnServer extends undefined | FormAsyncValidateOrFn<TFormData>, TSubmitMeta, TFieldComponents extends Record<string, HookComponentType<any>>, TFormComponents extends Record<string, HookComponentType<any>>, TRenderProps extends object = Record<string, never>> extends FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta> {
    props?: TRenderProps;
    render: HookFunctionComponent<HookPropsWithChildren<NoInfer<TRenderProps> & {
        form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TFieldComponents, TFormComponents>;
    }>>;
}
export interface WithFieldGroupProps<TFieldGroupData, TFieldComponents extends Record<string, HookComponentType<any>>, TFormComponents extends Record<string, HookComponentType<any>>, TSubmitMeta, TRenderProps extends object = Record<string, never>> extends BaseFormOptions<TFieldGroupData, TSubmitMeta> {
    props?: TRenderProps;
    render: HookFunctionComponent<HookPropsWithChildren<NoInfer<TRenderProps> & {
        group: AppFieldExtendedOctaneFieldGroupApi<unknown, TFieldGroupData, string | FieldsMap<unknown, TFieldGroupData>, undefined | FormValidateOrFn<unknown>, undefined | FormValidateOrFn<unknown>, undefined | FormAsyncValidateOrFn<unknown>, undefined | FormValidateOrFn<unknown>, undefined | FormAsyncValidateOrFn<unknown>, undefined | FormValidateOrFn<unknown>, undefined | FormAsyncValidateOrFn<unknown>, undefined | FormValidateOrFn<unknown>, undefined | FormAsyncValidateOrFn<unknown>, undefined | FormAsyncValidateOrFn<unknown>, unknown extends TSubmitMeta ? never : TSubmitMeta, TFieldComponents, TFormComponents>;
    }>>;
}
export declare function createFormHook<const TComponents extends Record<string, HookComponentType<any>>, const TFormComponents extends Record<string, HookComponentType<any>>>({ fieldComponents, fieldContext, formContext, formComponents, }: CreateFormHookProps<TComponents, TFormComponents>): {
    useAppForm: <TFormData, TOnMount extends undefined | FormValidateOrFn<TFormData>, TOnChange extends undefined | FormValidateOrFn<TFormData>, TOnChangeAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnBlur extends undefined | FormValidateOrFn<TFormData>, TOnBlurAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnSubmit extends undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnDynamic extends undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnServer extends undefined | FormAsyncValidateOrFn<TFormData>, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents, TFormComponents>;
    withForm: <TFormData, TOnMount extends undefined | FormValidateOrFn<TFormData>, TOnChange extends undefined | FormValidateOrFn<TFormData>, TOnChangeAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnBlur extends undefined | FormValidateOrFn<TFormData>, TOnBlurAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnSubmit extends undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnDynamic extends undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnServer extends undefined | FormAsyncValidateOrFn<TFormData>, TSubmitMeta, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents, TFormComponents, TRenderProps>) => WithFormProps<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnMount>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnChange>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnChangeAsync>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnBlur>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnBlurAsync>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnSubmit>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnDynamic>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync>, UnwrapDefaultOrAny<undefined | FormValidateOrFn<TFormData>, TOnServer>, UnwrapOrAny<TSubmitMeta>, UnwrapOrAny<TComponents>, UnwrapOrAny<TFormComponents>, UnwrapOrAny<TRenderProps>>["render"];
    withFieldGroup: <TFieldGroupData, TSubmitMeta, TRenderProps extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents, TFormComponents, TSubmitMeta, TRenderProps>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount extends undefined | FormValidateOrFn<TFormData>, TOnChange extends undefined | FormValidateOrFn<TFormData>, TOnChangeAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnBlur extends undefined | FormValidateOrFn<TFormData>, TOnBlurAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnSubmit extends undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnDynamic extends undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnServer extends undefined | FormAsyncValidateOrFn<TFormData>, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps> & {
        form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, unknown extends TSubmitMeta ? TFormSubmitMeta : TSubmitMeta, TComponents, TFormComponents> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta ? TFormSubmitMeta : TSubmitMeta, TComponents, TFormComponents>;
        fields: TFields;
    }>) => ReturnType<HookFunctionComponent>;
    useTypedAppFormContext: <TFormData, TOnMount extends undefined | FormValidateOrFn<TFormData>, TOnChange extends undefined | FormValidateOrFn<TFormData>, TOnChangeAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnBlur extends undefined | FormValidateOrFn<TFormData>, TOnBlurAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnSubmit extends undefined | FormValidateOrFn<TFormData>, TOnSubmitAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnDynamic extends undefined | FormValidateOrFn<TFormData>, TOnDynamicAsync extends undefined | FormAsyncValidateOrFn<TFormData>, TOnServer extends undefined | FormAsyncValidateOrFn<TFormData>, TSubmitMeta>(_props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents, TFormComponents>;
    extendForm: <const TNewField extends Record<string, HookComponentType<any>> & { [K in keyof TComponents]?: "Error: field component names must be unique \u2014 this key already exists in the base form"; }, const TNewForm extends Record<string, HookComponentType<any>> & { [K in keyof TFormComponents]?: "Error: form component names must be unique \u2014 this key already exists in the base form"; }>(extension: {
        fieldComponents?: TNewField;
        formComponents?: TNewForm;
    }) => {
        useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField, TFormComponents & TNewForm>;
        withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField, TFormComponents & TNewForm, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
            form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField>, UnwrapOrAny<TFormComponents & TNewForm>>;
        }>>;
        withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField, TFormComponents & TNewForm, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
            form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField, TFormComponents & TNewForm> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField, TFormComponents & TNewForm>;
            fields: TFields;
        }>) => ReturnType<HookFunctionComponent>;
        useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField, TFormComponents & TNewForm>;
        extendForm: <const TNewField_1 extends Record<string, HookComponentType<any>> & (TComponents & TNewField extends infer T ? { [K in keyof T]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_1 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm extends infer T_1 ? { [K_1 in keyof T_1]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
            fieldComponents?: TNewField_1 | undefined;
            formComponents?: TNewForm_1 | undefined;
        }) => {
            useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1, TFormComponents & TNewForm & TNewForm_1>;
            withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1, TFormComponents & TNewForm & TNewForm_1, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1>>;
            }>>;
            withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1, TFormComponents & TNewForm & TNewForm_1, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1, TFormComponents & TNewForm & TNewForm_1> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1, TFormComponents & TNewForm & TNewForm_1>;
                fields: TFields;
            }>) => ReturnType<HookFunctionComponent>;
            useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1, TFormComponents & TNewForm & TNewForm_1>;
            extendForm: <const TNewField_2 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 extends infer T_2 ? { [K_2 in keyof T_2]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_2 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 extends infer T_3 ? { [K_3 in keyof T_3]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                fieldComponents?: TNewField_2 | undefined;
                formComponents?: TNewForm_2 | undefined;
            }) => {
                useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2>;
                withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                    form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2>>;
                }>>;
                withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                    form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2>;
                    fields: TFields;
                }>) => ReturnType<HookFunctionComponent>;
                useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2>;
                extendForm: <const TNewField_3 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 extends infer T_4 ? { [K_4 in keyof T_4]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_3 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 extends infer T_5 ? { [K_5 in keyof T_5]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                    fieldComponents?: TNewField_3 | undefined;
                    formComponents?: TNewForm_3 | undefined;
                }) => {
                    useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3>;
                    withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                        form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3>>;
                    }>>;
                    withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                        form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3>;
                        fields: TFields;
                    }>) => ReturnType<HookFunctionComponent>;
                    useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3>;
                    extendForm: <const TNewField_4 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 extends infer T_6 ? { [K_6 in keyof T_6]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_4 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 extends infer T_7 ? { [K_7 in keyof T_7]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                        fieldComponents?: TNewField_4 | undefined;
                        formComponents?: TNewForm_4 | undefined;
                    }) => {
                        useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4>;
                        withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                            form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4>>;
                        }>>;
                        withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                            form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4>;
                            fields: TFields;
                        }>) => ReturnType<HookFunctionComponent>;
                        useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4>;
                        extendForm: <const TNewField_5 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 extends infer T_8 ? { [K_8 in keyof T_8]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_5 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 extends infer T_9 ? { [K_9 in keyof T_9]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                            fieldComponents?: TNewField_5 | undefined;
                            formComponents?: TNewForm_5 | undefined;
                        }) => {
                            useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5>;
                            withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                                form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5>>;
                            }>>;
                            withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                                form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5>;
                                fields: TFields;
                            }>) => ReturnType<HookFunctionComponent>;
                            useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5>;
                            extendForm: <const TNewField_6 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 extends infer T_10 ? { [K_10 in keyof T_10]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_6 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 extends infer T_11 ? { [K_11 in keyof T_11]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                                fieldComponents?: TNewField_6 | undefined;
                                formComponents?: TNewForm_6 | undefined;
                            }) => {
                                useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6>;
                                withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                                    form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6>>;
                                }>>;
                                withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                                    form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6>;
                                    fields: TFields;
                                }>) => ReturnType<HookFunctionComponent>;
                                useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6>;
                                extendForm: <const TNewField_7 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 extends infer T_12 ? { [K_12 in keyof T_12]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_7 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 extends infer T_13 ? { [K_13 in keyof T_13]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                                    fieldComponents?: TNewField_7 | undefined;
                                    formComponents?: TNewForm_7 | undefined;
                                }) => {
                                    useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7>;
                                    withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                                        form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7>>;
                                    }>>;
                                    withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                                        form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7>;
                                        fields: TFields;
                                    }>) => ReturnType<HookFunctionComponent>;
                                    useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7>;
                                    extendForm: <const TNewField_8 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 extends infer T_14 ? { [K_14 in keyof T_14]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_8 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 extends infer T_15 ? { [K_15 in keyof T_15]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                                        fieldComponents?: TNewField_8 | undefined;
                                        formComponents?: TNewForm_8 | undefined;
                                    }) => {
                                        useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8>;
                                        withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                                            form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8>>;
                                        }>>;
                                        withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                                            form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8>;
                                            fields: TFields;
                                        }>) => ReturnType<HookFunctionComponent>;
                                        useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8>;
                                        extendForm: <const TNewField_9 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 extends infer T_16 ? { [K_16 in keyof T_16]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_9 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 extends infer T_17 ? { [K_17 in keyof T_17]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                                            fieldComponents?: TNewField_9 | undefined;
                                            formComponents?: TNewForm_9 | undefined;
                                        }) => {
                                            useAppForm: <TFormData, TOnMount extends FormValidateOrFn<TFormData> | undefined, TOnChange extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta>(props: FormOptions<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount, TOnChange, TOnChangeAsync, TOnBlur, TOnBlurAsync, TOnSubmit, TOnSubmitAsync, TOnDynamic, TOnDynamicAsync, TOnServer, TSubmitMeta, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9>;
                                            withForm: <TFormData, TOnMount_1 extends FormValidateOrFn<TFormData> | undefined, TOnChange_1 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_1 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_1 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_1 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_1 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_1, TRenderProps extends object = {}>({ render, props, }: WithFormProps<TFormData, TOnMount_1, TOnChange_1, TOnChangeAsync_1, TOnBlur_1, TOnBlurAsync_1, TOnSubmit_1, TOnSubmitAsync_1, TOnDynamic_1, TOnDynamicAsync_1, TOnServer_1, TSubmitMeta_1, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9, TRenderProps>) => HookFunctionComponent<HookPropsWithChildren<NoInfer<UnwrapOrAny<TRenderProps>> & {
                                                form: AppFieldExtendedOctaneFormApi<UnwrapOrAny<TFormData>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnMount_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChange_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlur_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmit_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamic_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_1>, UnwrapDefaultOrAny<FormValidateOrFn<TFormData> | undefined, TOnServer_1>, UnwrapOrAny<TSubmitMeta_1>, UnwrapOrAny<TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9>, UnwrapOrAny<TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9>>;
                                            }>>;
                                            withFieldGroup: <TFieldGroupData, TSubmitMeta_2, TRenderProps_1 extends object = {}>({ render, props, defaultValues, }: WithFieldGroupProps<TFieldGroupData, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9, TSubmitMeta_2, TRenderProps_1>) => <TFormData, TFields extends DeepKeysOfType<TFormData, TFieldGroupData | null | undefined> | FieldsMap<TFormData, TFieldGroupData>, TOnMount_2 extends FormValidateOrFn<TFormData> | undefined, TOnChange_2 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_2 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_2 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_2 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_2 extends FormAsyncValidateOrFn<TFormData> | undefined, TFormSubmitMeta>(params: HookPropsWithChildren<NoInfer<TRenderProps_1> & {
                                                form: AppFieldExtendedOctaneFormApi<TFormData, TOnMount_2, TOnChange_2, TOnChangeAsync_2, TOnBlur_2, TOnBlurAsync_2, TOnSubmit_2, TOnSubmitAsync_2, TOnDynamic_2, TOnDynamicAsync_2, TOnServer_2, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9> | AppFieldExtendedOctaneFieldGroupApi<unknown, TFormData, string | FieldsMap<unknown, TFormData>, any, any, any, any, any, any, any, any, any, any, unknown extends TSubmitMeta_2 ? TFormSubmitMeta : TSubmitMeta_2, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9>;
                                                fields: TFields;
                                            }>) => ReturnType<HookFunctionComponent>;
                                            useTypedAppFormContext: <TFormData, TOnMount_3 extends FormValidateOrFn<TFormData> | undefined, TOnChange_3 extends FormValidateOrFn<TFormData> | undefined, TOnChangeAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnBlur_3 extends FormValidateOrFn<TFormData> | undefined, TOnBlurAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnSubmit_3 extends FormValidateOrFn<TFormData> | undefined, TOnSubmitAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnDynamic_3 extends FormValidateOrFn<TFormData> | undefined, TOnDynamicAsync_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TOnServer_3 extends FormAsyncValidateOrFn<TFormData> | undefined, TSubmitMeta_3>(_props: FormOptions<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3>) => AppFieldExtendedOctaneFormApi<TFormData, TOnMount_3, TOnChange_3, TOnChangeAsync_3, TOnBlur_3, TOnBlurAsync_3, TOnSubmit_3, TOnSubmitAsync_3, TOnDynamic_3, TOnDynamicAsync_3, TOnServer_3, TSubmitMeta_3, TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9, TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9>;
                                            extendForm: <const TNewField_10 extends Record<string, HookComponentType<any>> & (TComponents & TNewField & TNewField_1 & TNewField_2 & TNewField_3 & TNewField_4 & TNewField_5 & TNewField_6 & TNewField_7 & TNewField_8 & TNewField_9 extends infer T_18 ? { [K_18 in keyof T_18]?: "Error: field component names must be unique — this key already exists in the base form" | undefined; } : never), const TNewForm_10 extends Record<string, HookComponentType<any>> & (TFormComponents & TNewForm & TNewForm_1 & TNewForm_2 & TNewForm_3 & TNewForm_4 & TNewForm_5 & TNewForm_6 & TNewForm_7 & TNewForm_8 & TNewForm_9 extends infer T_19 ? { [K_19 in keyof T_19]?: "Error: form component names must be unique — this key already exists in the base form" | undefined; } : never)>(extension: {
                                                fieldComponents?: TNewField_10 | undefined;
                                                formComponents?: TNewForm_10 | undefined;
                                            }) => /*elided*/ any;
                                        };
                                    };
                                };
                            };
                        };
                    };
                };
            };
        };
    };
};
export {};
