export {
	addAfterEffect,
	addEffect,
	addTail,
	advance,
	applyProps,
	buildGraph,
	calculateDpr,
	context,
	createRoot,
	dispose,
	extend,
	flushGlobalEffects,
	getRootState,
	invalidate,
	unmountComponentAtNode,
	useFrame,
	useGraph,
	useInstanceHandle,
	useStore,
	useThree,
} from './core/index.js';
export type {
	Args,
	Attach,
	Catalogue,
	ConstructorRepresentation,
	Instance,
	InstanceProps,
	MathRepresentation,
	MathType,
	MathTypes,
	PrimitiveProps,
	ThreeElement,
	ThreeElements,
	ThreeInstanceProps,
	ThreeKey,
	ThreeRef,
	ThreeToJSXElements,
} from './core/index.js';
export type {
	Camera,
	CameraProps,
	CanvasLike,
	DefaultGLProps,
	Dpr,
	EventManager,
	Frameloop,
	GLProps,
	GlobalEffectType,
	GlobalRenderCallback,
	InternalState,
	ObjectMap,
	Performance,
	RefObject,
	RenderCallback,
	Renderer,
	RenderProps,
	RootState,
	RootStore,
	Size,
	Subscription,
	ThreeRoot,
	Viewport,
	XRManager,
} from './core/index.js';
export { Canvas } from './web/Canvas.tsrx';
export type { CanvasProps, CanvasRef, CanvasStyle } from './web/Canvas.tsrx';
