// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
export type ShapeCircleProps = {
    /** The fill color for the circle. */
    fill?: string;
    /** Width of the container. The circle radius is derived from max(width, height). */
    width?: string | number;
    /** Height of the container. The circle radius is derived from max(width, height). */
    height?: string | number;
    /** Additional CSS styles to apply to the circle. */
    style?: CSSProperties;
};
export default function ShapeCircle({ fill, width, height, style }: ShapeCircleProps): import("react").JSX.Element;
