// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
export type ShapeShapeLineProps = {
    /** The stroke color for the line. Note: Despite the name, this is used as the stroke, not fill. */
    fill?: string;
    /** Width of the line. */
    width?: string | number;
    /** Height of the container. The line is vertically centered. */
    height?: string | number;
    /** Additional CSS styles to apply to the line. The strokeWidth from style is used for line thickness. */
    style?: CSSProperties;
};
export default function ShapeLine({ fill, width, height, style }: ShapeShapeLineProps): import("react").JSX.Element;
