// Ported from react-aria (source: .react-spectrum/packages/react-aria/src/collections/useCachedChildren.ts).
// octane adaptations: `cloneElement` from 'octane' (descriptors carry
// .props/.key like React elements, so the caching walk is verbatim); React
// element types → `any`; public-hook slot threading (splitSlot/subSlot) with
// explicit dependency arrays.
import type { Key } from '@react-types/shared';
import { cloneElement, useMemo } from 'octane';

import { S, splitSlot, subSlot } from '../internal';

export interface CachedChildrenOptions<T> {
	/** Item objects in the collection. */
	items?: Iterable<T>;
	/** The contents of the collection. */
	children?: any | ((item: T) => any);
	/** Values that should invalidate the item cache when using dynamic collections. */
	dependencies?: ReadonlyArray<any>;
	/** A scope to prepend to all child item ids to ensure they are unique. */
	idScope?: Key;
	/** Whether to add `id` and `value` props to all child items. */
	addIdAndValue?: boolean;
}

/**
 * Maps over a list of items and renders octane elements for them. Each rendered item is
 * cached based on object identity, and keys are generated from the `key` or `id` property.
 */
export function useCachedChildren<T>(props: CachedChildrenOptions<T>): any;
// Slot-threading form: sibling ported hooks pass their derived sub-slot as the trailing arg.
export function useCachedChildren<T>(
	props: CachedChildrenOptions<T>,
	slot: symbol | undefined,
): any;
export function useCachedChildren(...args: any[]): any {
	const [user, slotArg] = splitSlot(args);
	const slot = slotArg ?? S('useCachedChildren');
	const props = user[0] as CachedChildrenOptions<any>;
	let { children, items, idScope, addIdAndValue, dependencies = [] } = props;

	// In development, invalidate when the children function updates (e.g. HMR).
	let childrenString = useMemo(
		() =>
			process.env.NODE_ENV !== 'production' && typeof children === 'function'
				? children.toString()
				: undefined,
		[children],
		subSlot(slot, 'childrenString'),
	);

	// Invalidate the cache whenever dependencies change.
	let cache = useMemo(
		() => new WeakMap(),
		[...dependencies, childrenString],
		subSlot(slot, 'cache'),
	);

	return useMemo(
		() => {
			if (items && typeof children === 'function') {
				let res: any[] = [];
				for (let item of items) {
					let cacheKey = isWeakKey(item) ? item : null;
					let rendered = cacheKey ? cache.get(cacheKey) : null;
					if (!rendered) {
						rendered = children(item);
						let id = rendered.props.id ?? item?.key ?? item?.id;
						if (idScope != null && rendered.props.id == null && id != null) {
							id = idScope + ':' + id;
						}

						// If no id is inferred from data, use the index as the key.
						// An id will be generated by the collection document.
						let key = id ?? res.length;

						// Note: only works if wrapped Item passes through id...
						rendered = cloneElement(rendered, addIdAndValue ? { key, id, value: item } : { key });
						if (cacheKey) {
							cache.set(cacheKey, rendered);
						}
					}
					res.push(rendered);
				}
				return res;
			} else if (typeof children !== 'function') {
				return children;
			}
		},
		[children, items, cache, idScope, addIdAndValue],
		subSlot(slot, 'result'),
	);
}

function isWeakKey(value: any): value is WeakKey {
	switch (typeof value) {
		case 'object':
			return value != null;
		case 'function':
		case 'symbol':
			return true;
		default:
			return false;
	}
}
