// Generated by scripts/generate-tsrx-types.mjs.
import type { GridRowsProps, GridScale } from '@octanejs/visx/grid';
import type { AnimationTrajectory } from '../types';
export default function AnimatedGridRows<Scale extends GridScale>({ scale, width, numTicks, tickValues, offset, className, animationTrajectory, top, left, ...lineProps }: Omit<GridRowsProps<Scale>, 'children'> & {
    animationTrajectory?: AnimationTrajectory;
}): import("react").JSX.Element;
