// Generated by scripts/generate-tsrx-types.mjs.
import type { GridColumnsProps, GridScale } from '@octanejs/visx/grid';
import type { AnimationTrajectory } from '../types';
export default function AnimatedGridColumns<Scale extends GridScale>({ scale, height, numTicks, tickValues, offset, className, animationTrajectory, top, left, ...lineProps }: Omit<GridColumnsProps<Scale>, 'children'> & {
    animationTrajectory?: AnimationTrajectory;
}): import("react").JSX.Element;
