// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
import type { GridScale, GridLines, CommonGridProps } from '@octanejs/visx/grid';
import type { TransitionConfig } from '../spring-configs/useLineTransitionConfig.tsrx';
export type AnimatedGridLinesProps<Scale extends GridScale> = {
    lines: GridLines;
    lineKey: (line: GridLines[number]) => string;
    scale: Scale;
} & Omit<SVGProps<SVGLineElement>, 'ref' | 'scale'> & Pick<TransitionConfig<Scale>, 'animationTrajectory' | 'animateXOrY'> & Pick<CommonGridProps, 'stroke' | 'strokeWidth' | 'lineStyle' | 'strokeDasharray'>;
export default function AnimatedGridLines<Scale extends GridScale>({ scale, lines, animationTrajectory, animateXOrY, lineKey, lineStyle, ...lineProps }: AnimatedGridLinesProps<Scale>): import("react").JSX.Element;
