// Generated by scripts/generate-tsrx-types.mjs.
import type React from 'react';
import type { OctaneNode } from 'octane';
import type { ChartTooltipConfig, ChartTooltipContentProps, ChartTooltipItem } from './ChartTooltipContent.tsrx';
import type { FloatingTooltipOffset, FloatingTooltipPadding, FloatingTooltipPortalProps, FloatingTooltipPositionerProps, FloatingTooltipRootState, TooltipAnchor, TooltipPlacement, UseFloatingTooltipOptions } from './types';
export { ChartTooltipItem } from './ChartTooltipContent.tsrx';
export type ChartTooltipControlledProps<Datum = unknown> = {
    open: boolean;
    anchor: TooltipAnchor | null;
    items: ChartTooltipItem<Datum>[];
};
export type ChartTooltipProps<Datum = unknown> = ChartTooltipControlledProps<Datum> & {
    config?: ChartTooltipConfig<Datum>;
    label?: OctaneNode;
    placement?: TooltipPlacement;
    strategy?: 'absolute' | 'fixed';
    offset?: number | FloatingTooltipOffset;
    collisionPadding?: FloatingTooltipPadding;
    portal?: boolean;
    portalProps?: Omit<FloatingTooltipPortalProps, 'children'>;
    positionerProps?: Omit<FloatingTooltipPositionerProps, 'children'>;
    contentProps?: Omit<ChartTooltipContentProps<Datum>, 'items' | 'config' | 'label'>;
    floatingOptions?: Omit<UseFloatingTooltipOptions<ChartTooltipItem<Datum>[]>, 'open' | 'defaultOpen' | 'data' | 'defaultData' | 'anchor' | 'defaultAnchor'>;
    renderContent?: (params: {
        items: ChartTooltipItem<Datum>[];
        config?: ChartTooltipConfig<Datum>;
        state: FloatingTooltipRootState<ChartTooltipItem<Datum>[]>;
    }) => OctaneNode;
};
export default function ChartTooltip<Datum = unknown>({ anchor, collisionPadding, config, contentProps, floatingOptions, items, label, offset, open, placement, portal, portalProps, positionerProps, renderContent, strategy, }: ChartTooltipProps<Datum>): React.JSX.Element;
