// Generated by scripts/generate-tsrx-types.mjs.
import type React from 'react';
export type ChartTooltipItem<Datum = unknown> = {
    key: string;
    datum?: Datum;
    index?: number;
    label?: React.ReactNode;
    value?: React.ReactNode;
    rawValue?: unknown;
    color?: string;
    x?: number;
    y?: number;
    distance?: number;
    hidden?: boolean;
    payload?: unknown;
};
export type ChartTooltipConfig<Datum = unknown> = Record<string, {
    label?: React.ReactNode | ((item: ChartTooltipItem<Datum>) => React.ReactNode);
    color?: string | ((item: ChartTooltipItem<Datum>) => string | undefined);
    icon?: React.ComponentType<{
        item: ChartTooltipItem<Datum>;
    }>;
    formatValue?: (value: unknown, item: ChartTooltipItem<Datum>) => React.ReactNode;
    formatLabel?: (item: ChartTooltipItem<Datum>) => React.ReactNode;
    hide?: boolean;
    order?: number;
}>;
export type ChartTooltipIndicator = 'dot' | 'line' | 'dashed' | 'square' | 'none';
export type ChartTooltipLabelRenderParams<Datum = unknown> = {
    label: React.ReactNode;
    items: ChartTooltipItem<Datum>[];
    config?: ChartTooltipConfig<Datum>;
};
export type ChartTooltipItemRenderParams<Datum = unknown> = {
    item: ChartTooltipItem<Datum>;
    configEntry?: ChartTooltipConfig<Datum>[string];
    label: React.ReactNode;
    value: React.ReactNode;
    color?: string;
    indicator: ChartTooltipIndicator;
};
export type ChartTooltipValueRenderParams<Datum = unknown> = ChartTooltipItemRenderParams<Datum>;
export type ChartTooltipContentProps<Datum = unknown> = React.HTMLAttributes<HTMLDivElement> & {
    label?: React.ReactNode;
    items: ChartTooltipItem<Datum>[];
    config?: ChartTooltipConfig<Datum>;
    indicator?: ChartTooltipIndicator;
    hideLabel?: boolean;
    hideIndicator?: boolean;
    sortItems?: (a: ChartTooltipItem<Datum>, b: ChartTooltipItem<Datum>) => number;
    renderLabel?: (params: ChartTooltipLabelRenderParams<Datum>) => React.ReactNode;
    renderItem?: (params: ChartTooltipItemRenderParams<Datum>) => React.ReactNode;
    renderValue?: (params: ChartTooltipValueRenderParams<Datum>) => React.ReactNode;
    getItemKey?: (item: ChartTooltipItem<Datum>, index: number) => React.Key;
    'data-testid'?: string;
};
export default function ChartTooltipContent<Datum = unknown>({ className, config, getItemKey, hideIndicator, hideLabel, indicator, items, label, renderItem, renderLabel, renderValue, sortItems, 'data-testid': dataTestId, ...restProps }: ChartTooltipContentProps<Datum>): React.JSX.Element | null;
