// Generated by scripts/generate-tsrx-types.mjs.
import type React from 'react';
import type { FloatingTooltipRootState } from './types';
export type FloatingTooltipContextProviderProps = {
    children: React.ReactNode;
    value: FloatingTooltipRootState<any>;
};
export declare function FloatingTooltipContextProvider({ children, value, }: FloatingTooltipContextProviderProps): React.JSX.Element;
export declare function useFloatingTooltipContext(componentName: string): FloatingTooltipRootState<any>;
