// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { FloatingTooltipRootState } from './types';
export type FloatingTooltipContextProviderProps = {
    children: OctaneNode;
    value: FloatingTooltipRootState<any>;
};
export declare function FloatingTooltipContextProvider({ children, value, }: FloatingTooltipContextProviderProps): import("react").JSX.Element;
export declare function useFloatingTooltipContext(componentName: string): FloatingTooltipRootState<any>;
