// Generated by scripts/generate-tsrx-types.mjs.
import type { ElementDescriptor } from 'octane';
import type { FloatingTooltipArrowProps, FloatingTooltipContentProps, FloatingTooltipPortalProps, FloatingTooltipPositionerProps, FloatingTooltipProviderProps, FloatingTooltipRootProps, FloatingTooltipTriggerProps } from './types';
declare function Provider({ children, closeDelay, delay, skipDelay, }: FloatingTooltipProviderProps): import("react").JSX.Element;
declare function Root<TData = unknown>({ children, forceMount, ...options }: FloatingTooltipRootProps<TData>): import("react").JSX.Element;
declare function Trigger({ disabled, render }: FloatingTooltipTriggerProps): ElementDescriptor<any>;
declare function Portal({ children, container, disabled }: FloatingTooltipPortalProps): unknown;
declare function Positioner({ children, id, render, style, ...restProps }: FloatingTooltipPositionerProps): ElementDescriptor<any> | null;
declare function Content({ children, render, ...restProps }: FloatingTooltipContentProps): ElementDescriptor<any> | null;
declare function Arrow({ height, padding: _padding, render, tipRadius, width, ...restProps }: FloatingTooltipArrowProps): import("react").JSX.Element | ElementDescriptor<any> | null;
declare const FloatingTooltip: {
    Arrow: typeof Arrow;
    Content: typeof Content;
    Portal: typeof Portal;
    Positioner: typeof Positioner;
    Provider: typeof Provider;
    Root: typeof Root;
    Trigger: typeof Trigger;
};
export default FloatingTooltip;
