// Generated by scripts/generate-tsrx-types.mjs.
import type React from 'react';
import type { ChartTooltipItem, ChartTooltipProps, ChartTooltipControlledProps } from './ChartTooltip.tsrx';
import type { FloatingTooltipOffset, TooltipAnchor, TooltipPlacement, UseFloatingTooltipOptions } from './types';
export type ChartTooltipLocalPoint = {
    x: number;
    y: number;
};
export type ChartTooltipSvgPoint = {
    type: 'svg-local-point';
    x: number;
    y: number;
};
export type UseChartTooltipOptions<Datum = unknown> = {
    defaultOpen?: boolean;
    defaultItems?: ChartTooltipItem<Datum>[];
    defaultAnchor?: TooltipAnchor | null;
    placement?: TooltipPlacement;
    offset?: number | FloatingTooltipOffset;
    hideDelay?: number;
    container?: Element | null;
    floatingOptions?: Omit<UseFloatingTooltipOptions<ChartTooltipItem<Datum>[]>, 'open' | 'defaultOpen' | 'data' | 'defaultData' | 'anchor' | 'defaultAnchor'>;
};
export type UseChartTooltipReturn<Datum = unknown> = {
    open: boolean;
    items: ChartTooltipItem<Datum>[];
    anchor: TooltipAnchor | null;
    containerRef: React.RefCallback<HTMLElement | SVGElement>;
    show: (args: {
        anchor: TooltipAnchor | ChartTooltipLocalPoint | ChartTooltipSvgPoint;
        items: ChartTooltipItem<Datum>[];
    }) => void;
    hide: () => void;
    update: (args: Partial<{
        anchor: TooltipAnchor;
        items: ChartTooltipItem<Datum>[];
    }>) => void;
    tooltipProps: ChartTooltipControlledProps<Datum> & Pick<ChartTooltipProps<Datum>, 'floatingOptions' | 'offset' | 'placement'>;
};
export default function useChartTooltip<Datum = unknown>({ container, defaultAnchor, defaultItems, defaultOpen, floatingOptions, hideDelay, offset, placement, }?: UseChartTooltipOptions<Datum>): UseChartTooltipReturn<Datum>;
