// Generated by scripts/generate-tsrx-types.mjs.
import type { UseFloatingTooltipOptions, UseFloatingTooltipReturn } from './types';
export default function useFloatingTooltip<TData = unknown>({ anchor: anchorProp, arrow, collisionBoundary, collisionPadding, data: dataProp, defaultAnchor, defaultData, defaultOpen, disabled, flip, hideWhenDetached, id, interactions, middleware, middlewareMode, offset, onOpenChange, open: openProp, placement, role, shift, size, strategy, whileElementsMounted, }?: UseFloatingTooltipOptions<TData>): UseFloatingTooltipReturn<TData>;
