// Generated by scripts/generate-tsrx-types.mjs.
export type UseTooltipParams<TooltipData> = {
    /** Whether the tooltip is currently open/visible. */
    tooltipOpen: boolean;
    /** The left position (in pixels) of the tooltip. */
    tooltipLeft?: number;
    /** The top position (in pixels) of the tooltip. */
    tooltipTop?: number;
    /** The data associated with the tooltip. */
    tooltipData?: TooltipData;
    /** Function to update tooltip state. */
    updateTooltip: (args: UpdateTooltipArgs<TooltipData>) => void;
    /** Function to show the tooltip with the specified position and data. */
    showTooltip: (args: ShowTooltipArgs<TooltipData>) => void;
    /** Function to hide the tooltip. */
    hideTooltip: () => void;
};
type UseTooltipState<TooltipData> = Pick<UseTooltipParams<TooltipData>, 'tooltipOpen' | 'tooltipLeft' | 'tooltipTop' | 'tooltipData'>;
type ValueOrFunc<T> = T | ((t: T) => T);
type ShowTooltipArgs<TooltipData> = ValueOrFunc<Omit<UseTooltipState<TooltipData>, 'tooltipOpen'>>;
type UpdateTooltipArgs<TooltipData> = ValueOrFunc<UseTooltipState<TooltipData>>;
export default function useTooltip<TooltipData = {}>(
/** Optional initial TooltipState. */
initialTooltipState?: Partial<UseTooltipParams<TooltipData>>): UseTooltipParams<TooltipData>;
export {};
