// Generated by scripts/generate-tsrx-types.mjs.
import type { FC } from 'react';
import type { RectReadOnly, Options as BaseUseMeasureOptions } from '../../internal/useMeasure.tsrx';
import type { PortalProps } from '../Portal.tsrx';
import type { TooltipProps } from '../tooltips/Tooltip.tsrx';
export type TooltipInPortalProps = TooltipProps & Pick<UseTooltipPortalOptions, 'detectBounds' | 'zIndex'>;
export type UseTooltipInPortal = {
    /** Ref callback to be attached to the container element for boundary detection. */
    containerRef: (element: HTMLElement | SVGElement | null) => void;
    /** The bounding box of the container element. */
    containerBounds: RectReadOnly;
    /** Function to force a refresh of the container bounds. */
    forceRefreshBounds: () => void;
    /** Component to render the tooltip in a portal. */
    TooltipInPortal: FC<TooltipInPortalProps>;
};
export type UseTooltipPortalOptions = Pick<PortalProps, 'zIndex'> & {
    /** whether TooltipWithBounds should be used to auto-detect (page) boundaries and reposition itself. */
    detectBounds?: boolean;
    /** Debounce resize or scroll events in milliseconds (needed for positioning) */
    debounce?: number | {
        scroll: number;
        resize: number;
    };
    /** React to nested scroll changes, don't use this if you know your view is static */
    scroll?: boolean;
    /** You can optionally inject a ResizeObserver polyfill. */
    polyfill?: BaseUseMeasureOptions['polyfill'];
};
/**
 * Hook that handles rendering of a Tooltip or TooltipWithBounds in a Portal.
 * Handles conversion of container coordinates to page coordinates using the container bounds.
 */
export default function useTooltipInPortal({ detectBounds: detectBoundsOption, zIndex: zIndexOption, ...useMeasureOptions }?: UseTooltipPortalOptions | undefined): UseTooltipInPortal;
