// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { AnimationTrajectory } from '@octanejs/visx/react-spring';
import type { BaseAxisProps } from './BaseAxis.tsrx';
export type AnimatedAxisProps<Scale extends AxisScale> = Omit<BaseAxisProps<Scale>, 'AxisComponent'> & {
    /** Animation trjectory of axis ticks. */
    animationTrajectory?: AnimationTrajectory;
};
export default function AnimatedAxis<Scale extends AxisScale>(props: AnimatedAxisProps<Scale>): import("react").JSX.Element;
