// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BaseAxisProps } from './BaseAxis.tsrx';
export type AxisProps<Scale extends AxisScale = AxisScale> = Omit<BaseAxisProps<Scale>, 'AxisComponent'>;
export default function Axis<Scale extends AxisScale = AxisScale>(props: AxisProps<Scale>): import("react").JSX.Element;
