// Generated by scripts/generate-tsrx-types.mjs.
import type { FC } from 'react';
import type { AxisScale, AxisProps as VxAxisProps } from '@octanejs/visx/axis';
export type BaseAxisProps<Scale extends AxisScale> = Omit<VxAxisProps<Scale>, 'scale' | 'orientation'> & {
    /** Required axis orientation. */
    orientation: NonNullable<VxAxisProps<Scale>['orientation']>;
} & {
    /** Rendered component which is passed VxAxisProps by BaseAxis after processing. */
    AxisComponent: FC<VxAxisProps<Scale>>;
};
/**
 * Component which handles all xychart-specific logic for axes,
 * and passes processed props to a specified Axis / AnimatedAxis component.
 */
export default function BaseAxis<Scale extends AxisScale>({ AxisComponent, ...props }: BaseAxisProps<Scale>): import("react").JSX.Element | null;
