// Generated by scripts/generate-tsrx-types.mjs.
import type { AccessorInput } from '@octanejs/visx/kernel';
import type { VoronoiConfig } from '../voronoi';
export type UseVoronoiOptions<Datum> = Omit<VoronoiConfig<Datum>, 'x' | 'y'> & {
    /** Set the x-value accessor function or string key for the voronoi layout. */
    x?: AccessorInput<Datum, number>;
    /** Set the y-value accessor function or string key for the voronoi layout. */
    y?: AccessorInput<Datum, number>;
};
export default function useVoronoi<Datum>({ width, height, x, y }: UseVoronoiOptions<Datum>): import("d3-voronoi").VoronoiLayout<unknown>;
