// Generated by scripts/generate-tsrx-types.mjs.
import type { TicksRendererProps, AxisScale } from '@octanejs/visx/axis';
import type { AnimationTrajectory } from '../types';
export default function AnimatedTicks<Scale extends AxisScale>({ hideTicks, horizontal, orientation, scale, tickClassName, tickComponent, tickLabelProps: allTickLabelProps, tickStroke, tickTransform, ticks, tickLineProps, animationTrajectory, }: TicksRendererProps<Scale> & {
    animationTrajectory?: AnimationTrajectory;
}): import("react").JSX.Element;
