// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisProps, AxisScale } from '@octanejs/visx/axis';
import type { AnimationTrajectory } from '../types';
export type AnimatedAxisProps<Scale extends AxisScale> = Omit<AxisProps<Scale>, 'ticksComponent'> & {
    animationTrajectory?: AnimationTrajectory;
};
export default function AnimatedAxis<Scale extends AxisScale>({ animationTrajectory, tickComponent, ...axisProps }: AnimatedAxisProps<Scale>): import("react").JSX.Element;
