// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
import type { OctaneNode } from 'octane';
export type ChartA11yLivePoliteness = 'polite' | 'assertive';
export type ChartA11yAnnouncerProps = {
    id?: string;
    message?: OctaneNode;
    children?: OctaneNode;
    politeness?: ChartA11yLivePoliteness;
    atomic?: boolean;
    visible?: boolean;
    className?: string;
    style?: CSSProperties;
};
export declare function ChartA11yAnnouncer({ id, message, children, politeness, atomic, visible, className, style, }: ChartA11yAnnouncerProps): import("react").JSX.Element;
