// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
import type { ChartA11yConfig } from '../types';
export type ChartA11yDataTableProps<Datum> = ChartA11yConfig<Datum> & {
    visible?: boolean;
    className?: string;
    style?: CSSProperties;
};
export declare function ChartA11yDataTable<Datum>({ visible, className, style, ...config }: ChartA11yDataTableProps<Datum>): import("react").JSX.Element;
