// This file is generated by scripts/error-codes/generate.mjs. Do not edit.
import {
	formatDevErrorMessage,
	formatProdErrorMessage,
	formatUnknownDevErrorMessage,
} from './error-message.js';

type ClientErrorArguments = {
	1: [];
	2: [];
	3: [unknown];
	4: [];
	5: [];
	6: [];
	7: [unknown];
	8: [unknown];
	9: [];
	10: [unknown];
	11: [];
	12: [unknown];
	13: [];
	14: [unknown];
	15: [unknown];
	16: [];
	17: [];
	18: [unknown];
	19: [];
	20: [];
	21: [];
	22: [];
	23: [];
	24: [unknown];
	25: [];
	26: [unknown];
	27: [];
	28: [];
	29: [];
	46: [unknown, unknown];
};

export function formatClientError<Code extends keyof ClientErrorArguments>(
	code: Code,
	...args: ClientErrorArguments[Code]
): string {
	if (process.env.NODE_ENV !== 'production') {
		switch (code) {
			case 1:
				return formatDevErrorMessage(
					'Maximum update depth exceeded. Octane limits the number of nested updates to prevent infinite loops.',
					args,
				);
			case 2:
				return formatDevErrorMessage(
					'Children.only expected to receive a single element child.',
					args,
				);
			case 3:
				return formatDevErrorMessage(
					'Objects are not valid as an Octane child (found: %s). If you meant to render a collection of children, use an array instead.',
					args,
				);
			case 4:
				return formatDevErrorMessage(
					'cloneElement: the first argument must be an element (from createElement / JSX).',
					args,
				);
			case 5:
				return formatDevErrorMessage(
					'Can only set one of `children` or `props.dangerouslySetInnerHTML`.',
					args,
				);
			case 6:
				return formatDevErrorMessage(
					'`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`',
					args,
				);
			case 7:
				return formatDevErrorMessage(
					'`%s` is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 8:
				return formatDevErrorMessage(
					'`<%s>` is a void element tag and must neither have children nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 9:
				return formatDevErrorMessage(
					'Too many re-renders. Octane limits the number of renders to prevent an infinite loop.',
					args,
				);
			case 10:
				return formatDevErrorMessage(
					"lazy: expected the load() promise to resolve to a component function or a module with a component as its default export, got '%s'",
					args,
				);
			case 11:
				return formatDevErrorMessage(
					"A function wrapped in useEffectEvent can't be called during rendering.",
					args,
				);
			case 12:
				return formatDevErrorMessage('%s(): argument is not a Context nor a thenable', args);
			case 13:
				return formatDevErrorMessage('Multiple errors were thrown during the render flush.', args);
			case 14:
				return formatDevErrorMessage(
					'act(): scheduler did not stabilize after %s iterations — likely an infinite render loop',
					args,
				);
			case 15:
				return formatDevErrorMessage(
					"%s was called without a hook slot. The octane compiler injects per-call-site keys; ensure your project loads this runtime through the Vite plugin (octane/compiler/vite). To call hooks by hand, pass a stable symbol, e.g. useState(0, Symbol.for('my-stable-id')).",
					args,
				);
			case 16:
				return formatDevErrorMessage(
					'Hydrate: `when` must synchronously return a hydration strategy with a valid type.',
					args,
				);
			case 17:
				return formatDevErrorMessage(
					'Hydrate: the compiler-generated child loader did not resolve to a component.',
					args,
				);
			case 18:
				return formatDevErrorMessage(
					'%s(): a React context can only be read inside a React-hosted Octane island (see octane/react); this component is not rendered under one.',
					args,
				);
			case 19:
				return formatDevErrorMessage(
					'A renderer-owned DOM region is missing its universal owner bridge.',
					args,
				);
			case 20:
				return formatDevErrorMessage(
					'bindRendererRegionOwner() must run while a DOM component is rendering.',
					args,
				);
			case 21:
				return formatDevErrorMessage(
					'bindRendererRegionOwner() must be the first call in a renderer-owned DOM root component.',
					args,
				);
			case 22:
				return formatDevErrorMessage('A renderer-owned DOM region requires a live DOM root.', args);
			case 23:
				return formatDevErrorMessage('Server-rendered use() rejected', args);
			case 24:
				return formatDevErrorMessage(
					'Element type is invalid: expected a string (for a built-in element) or a function (for a component), but got: %s.',
					args,
				);
			case 25:
				return formatDevErrorMessage(
					'Octane: internal — a component descriptor reached the de-opt host reconciler (should have been routed through a Block via hostElementBody/componentSlot).',
					args,
				);
			case 26:
				return formatDevErrorMessage(
					'`<%s>` is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 27:
				return formatDevErrorMessage(
					'A hosted foreign-context request escaped its renderer-region owner; the owning bridge is gone or declined it.',
					args,
				);
			case 28:
				return formatDevErrorMessage('Target container is not a DOM element.', args);
			case 29:
				return formatDevErrorMessage('Cannot update an unmounted root.', args);
			case 46:
				return formatDevErrorMessage(
					'Expected %s listener to be a function, instead got a value of `%s` type.',
					args,
				);
			default:
				return formatUnknownDevErrorMessage(code);
		}
	}
	return formatProdErrorMessage(code, args);
}
