// This file is generated by scripts/error-codes/generate.mjs. Do not edit.
// The consumer's bundler substitutes the whole Node environment expression below,
// so the source guard must stay written out literally. Declared module-locally — never
// `declare global`, which would ship in the tarball — so this file type-checks in
// a browser app that has no `@types/node`.
declare const process: { env: { NODE_ENV?: string } };

import {
	formatDevErrorMessage,
	formatProdErrorMessage,
	formatUnknownDevErrorMessage,
} from './error-message.js';

type ClientErrorArguments = {
	1: [];
	2: [];
	3: [unknown];
	4: [];
	5: [];
	6: [];
	7: [unknown];
	8: [unknown];
	9: [];
	10: [unknown];
	11: [];
	12: [unknown];
	13: [];
	14: [unknown];
	15: [unknown];
	16: [];
	17: [];
	18: [unknown];
	19: [];
	20: [];
	21: [];
	22: [];
	23: [];
	24: [unknown];
	25: [];
	26: [unknown];
	27: [];
	29: [];
	46: [unknown, unknown];
	49: [];
	50: [];
	58: [];
	63: [];
	64: [];
	66: [];
	67: [unknown];
	72: [];
	74: [];
	75: [];
	76: [];
	77: [];
	78: [];
	79: [];
	81: [];
	82: [unknown];
	83: [];
	84: [];
	85: [];
	86: [];
	87: [];
	88: [];
	89: [];
	90: [];
	91: [];
	92: [];
	93: [unknown];
	94: [];
	95: [];
	96: [unknown];
	97: [];
	98: [];
	99: [];
	100: [];
	101: [];
	102: [unknown];
	103: [];
	104: [];
	105: [];
	106: [];
	107: [];
	108: [];
	109: [];
	110: [];
	111: [];
	112: [];
	113: [unknown];
	114: [];
	115: [];
	116: [];
	117: [];
	118: [];
	119: [];
	120: [];
	121: [];
	122: [];
	123: [];
	124: [];
	125: [unknown];
	126: [unknown];
	127: [];
	128: [];
	129: [];
	130: [];
	131: [];
	132: [unknown];
	133: [unknown];
	134: [unknown, unknown];
	135: [];
	136: [];
	137: [];
	138: [];
	139: [];
	140: [];
	141: [];
	142: [];
	143: [];
	144: [unknown];
	145: [unknown];
	146: [unknown];
	147: [];
	148: [];
	149: [];
	150: [];
	151: [unknown];
	152: [];
	153: [unknown];
	154: [unknown];
	155: [];
	156: [];
	157: [];
	158: [];
	159: [];
	160: [];
	161: [];
	162: [];
	163: [];
	164: [];
	165: [];
	166: [];
	167: [];
	168: [];
	169: [];
	170: [];
	171: [];
	172: [];
	173: [];
	174: [];
	175: [];
	176: [];
	177: [];
	178: [];
	179: [unknown];
	180: [unknown, unknown];
	181: [];
	182: [];
	183: [];
	184: [];
	185: [];
	186: [];
	187: [];
	188: [unknown];
	189: [];
	190: [];
	191: [];
	192: [];
	193: [];
	194: [unknown, unknown, unknown];
	195: [];
	196: [];
	197: [];
	198: [];
	199: [];
	200: [];
	201: [];
	202: [unknown];
	203: [];
	204: [];
	205: [];
	206: [];
	207: [];
	208: [];
	209: [];
	210: [];
	211: [];
	212: [];
	213: [];
	214: [];
	215: [];
	216: [];
	217: [];
	218: [];
	219: [];
	220: [];
	221: [];
	222: [];
	223: [];
	224: [];
	225: [];
	226: [];
	227: [];
	228: [];
	229: [];
	230: [];
	231: [];
	232: [];
	233: [];
	234: [];
	235: [];
	236: [];
	237: [];
	238: [];
	239: [];
	240: [];
	241: [];
	242: [unknown];
	243: [];
	244: [unknown];
	245: [];
	246: [];
	247: [];
	248: [];
	249: [];
	250: [];
	251: [];
	252: [];
	253: [];
	254: [];
	255: [];
	256: [];
	257: [];
	258: [];
	259: [];
	260: [];
	261: [];
	262: [];
	263: [];
	264: [];
	265: [];
	266: [];
	267: [];
	268: [];
	269: [];
	270: [];
	271: [];
	272: [];
	273: [];
	274: [];
	275: [];
	276: [];
	277: [];
	278: [];
	279: [];
	280: [];
	281: [];
	282: [];
	283: [];
	284: [];
	285: [];
	286: [];
	287: [];
	288: [];
	289: [];
	290: [];
	291: [];
	292: [];
	293: [];
	294: [];
	295: [];
	296: [];
	297: [];
	298: [];
	299: [];
	300: [];
	301: [];
	302: [];
	303: [];
	304: [];
	305: [];
	306: [];
	307: [];
	308: [];
	309: [];
	310: [];
	311: [];
	312: [];
	313: [];
	314: [];
	315: [];
	316: [];
	317: [];
	318: [];
	319: [];
	320: [];
	321: [];
	322: [];
	323: [];
	324: [];
	325: [];
	326: [];
	327: [];
	328: [];
	329: [];
	330: [];
	331: [];
	336: [unknown];
	337: [];
	338: [];
	339: [];
	340: [];
	341: [];
	342: [];
	343: [];
};

export function formatClientError<Code extends keyof ClientErrorArguments>(
	code: Code,
	...args: ClientErrorArguments[Code]
): string {
	if (process.env.NODE_ENV !== 'production') {
		switch (code) {
			case 1:
				return formatDevErrorMessage(
					'Maximum update depth exceeded. Octane limits the number of nested updates to prevent infinite loops.',
					args,
				);
			case 2:
				return formatDevErrorMessage(
					'Children.only expected to receive a single element child.',
					args,
				);
			case 3:
				return formatDevErrorMessage(
					'Objects are not valid as an Octane child (found: %s). If you meant to render a collection of children, use an array instead.',
					args,
				);
			case 4:
				return formatDevErrorMessage(
					'cloneElement: the first argument must be an element (from createElement / JSX).',
					args,
				);
			case 5:
				return formatDevErrorMessage(
					'Can only set one of `children` or `props.dangerouslySetInnerHTML`.',
					args,
				);
			case 6:
				return formatDevErrorMessage(
					'`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`',
					args,
				);
			case 7:
				return formatDevErrorMessage(
					'`%s` is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 8:
				return formatDevErrorMessage(
					'`<%s>` is a void element tag and must neither have children nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 9:
				return formatDevErrorMessage(
					'Too many re-renders. Octane limits the number of renders to prevent an infinite loop.',
					args,
				);
			case 10:
				return formatDevErrorMessage(
					"lazy: expected the load() promise to resolve to a component function or a module with a component as its default export, got '%s'",
					args,
				);
			case 11:
				return formatDevErrorMessage(
					"A function wrapped in useEffectEvent can't be called during rendering.",
					args,
				);
			case 12:
				return formatDevErrorMessage('%s(): argument is not a Context nor a thenable', args);
			case 13:
				return formatDevErrorMessage('Multiple errors were thrown during the render flush.', args);
			case 14:
				return formatDevErrorMessage(
					'act(): scheduler did not stabilize after %s iterations — likely an infinite render loop',
					args,
				);
			case 15:
				return formatDevErrorMessage(
					"%s was called without a hook slot. The octane compiler injects per-call-site keys; ensure your project loads this runtime through the Vite plugin (octane/compiler/vite). To call hooks by hand, pass a stable symbol, e.g. useState(0, Symbol.for('my-stable-id')).",
					args,
				);
			case 16:
				return formatDevErrorMessage(
					'Hydrate: `when` must synchronously return a hydration strategy with a valid type.',
					args,
				);
			case 17:
				return formatDevErrorMessage(
					'Hydrate: the compiler-generated child loader did not resolve to a component.',
					args,
				);
			case 18:
				return formatDevErrorMessage(
					'%s(): a React context can only be read inside a React-hosted Octane island (see octane/react); this component is not rendered under one.',
					args,
				);
			case 19:
				return formatDevErrorMessage(
					'A renderer-owned DOM region is missing its universal owner bridge.',
					args,
				);
			case 20:
				return formatDevErrorMessage(
					'bindRendererRegionOwner() must run while a DOM component is rendering.',
					args,
				);
			case 21:
				return formatDevErrorMessage(
					'bindRendererRegionOwner() must be the first call in a renderer-owned DOM root component.',
					args,
				);
			case 22:
				return formatDevErrorMessage('A renderer-owned DOM region requires a live DOM root.', args);
			case 23:
				return formatDevErrorMessage('Server-rendered use() rejected', args);
			case 24:
				return formatDevErrorMessage(
					'Element type is invalid: expected a string (for a built-in element) or a function (for a component), but got: %s.',
					args,
				);
			case 25:
				return formatDevErrorMessage(
					'Octane: internal — a component descriptor reached the de-opt host reconciler (should have been routed through a Block via hostElementBody/componentSlot).',
					args,
				);
			case 26:
				return formatDevErrorMessage(
					'`<%s>` is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 27:
				return formatDevErrorMessage(
					'A hosted foreign-context request escaped its renderer-region owner; the owning bridge is gone or declined it.',
					args,
				);
			case 29:
				return formatDevErrorMessage('Cannot update an unmounted root.', args);
			case 46:
				return formatDevErrorMessage(
					'Expected %s listener to be a function, instead got a value of `%s` type.',
					args,
				);
			case 49:
				return formatDevErrorMessage(
					'FragmentInstance.scrollIntoView() does not support scrollIntoViewOptions. Use the alignToTop boolean instead.',
					args,
				);
			case 50:
				return formatDevErrorMessage('Unclosed server-rendered Fragment descriptor.', args);
			case 58:
				return formatDevErrorMessage('Unsupported native-read compiler/runtime version.', args);
			case 63:
				return formatDevErrorMessage(
					'Target container is not a DOM element. Pass an Element, Document, or DocumentFragment. If document.body is null after document hydration, update the existing document root or render a document shell containing <body>.',
					args,
				);
			case 64:
				return formatDevErrorMessage('Multiple errors were thrown during act.', args);
			case 66:
				return formatDevErrorMessage(
					'An independent Hydrate boundary cannot change ownership after mount.',
					args,
				);
			case 67:
				return formatDevErrorMessage('Signal control identity mismatch for "%s".', args);
			case 72:
				return formatDevErrorMessage(
					'Octane DOM binding text range does not match its template.',
					args,
				);
			case 74:
				return formatDevErrorMessage('Unsupported Octane signal binding ABI.', args);
			case 75:
				return formatDevErrorMessage(
					'Hydration binding leases require a supported fixed native view without structural regions or unsupported writers.',
					args,
				);
			case 76:
				return formatDevErrorMessage(
					'DOM binding hydration leases are supported only by hydrateRoot().',
					args,
				);
			case 77:
				return formatDevErrorMessage(
					'Hydration binding leases require active fixed native views owned by this container.',
					args,
				);
			case 78:
				return formatDevErrorMessage('A hydration binding lease can be claimed only once.', args);
			case 79:
				return formatDevErrorMessage('Unsupported native signal transition.', args);
			case 81:
				return formatDevErrorMessage('An optimistic source needs a live Octane scope.', args);
			case 82:
				return formatDevErrorMessage('Action operation "%s" is no longer writable.', args);
			case 83:
				return formatDevErrorMessage('An optimistic write requires ready source authority.', args);
			case 84:
				return formatDevErrorMessage(
					'An action cannot adopt authority for a different query selection.',
					args,
				);
			case 85:
				return formatDevErrorMessage(
					'Only a writable or query source can adopt an authoritative value.',
					args,
				);
			case 86:
				return formatDevErrorMessage(
					'An action needs current authority to compare receipt revisions.',
					args,
				);
			case 87:
				return formatDevErrorMessage(
					'An authority revision comparator must return a finite number.',
					args,
				);
			case 88:
				return formatDevErrorMessage('The pinned query selection is no longer current.', args);
			case 89:
				return formatDevErrorMessage('optimistic$ requires an Octane signal source.', args);
			case 90:
				return formatDevErrorMessage(
					'An optimistic source cannot use conflicting authority revision policies.',
					args,
				);
			case 91:
				return formatDevErrorMessage(
					'An optimistic subscription needs an active signal owner.',
					args,
				);
			case 92:
				return formatDevErrorMessage(
					'An optimistic write must belong to action$ or use operation.set().',
					args,
				);
			case 93:
				return formatDevErrorMessage('Action operation "%s" may have been accepted.', args);
			case 94:
				return formatDevErrorMessage(
					'action$ requires crypto.randomUUID() for operation identity.',
					args,
				);
			case 95:
				return formatDevErrorMessage('operation.set() requires a signal from optimistic$().', args);
			case 96:
				return formatDevErrorMessage('Action operation "%s" is settled.', args);
			case 97:
				return formatDevErrorMessage(
					'operation.adopt() requires exactly one optimistic source.',
					args,
				);
			case 98:
				return formatDevErrorMessage('The action is settled.', args);
			case 99:
				return formatDevErrorMessage('until() requires a read.', args);
			case 100:
				return formatDevErrorMessage('until() timeout must be a nonnegative number.', args);
			case 101:
				return formatDevErrorMessage('until() requires a pinned optimistic source.', args);
			case 102:
				return formatDevErrorMessage('The action is %s.', args);
			case 103:
				return formatDevErrorMessage('The optimistic owner was retired.', args);
			case 104:
				return formatDevErrorMessage('The pinned optimistic selection is no longer current.', args);
			case 105:
				return formatDevErrorMessage('The optimistic confirmation timed out.', args);
			case 106:
				return formatDevErrorMessage('optimistic$ requires a signal source.', args);
			case 107:
				return formatDevErrorMessage(
					'An authority revision policy must be a comparator function.',
					args,
				);
			case 108:
				return formatDevErrorMessage(
					'action$ requires a handler and an optional nonempty key.',
					args,
				);
			case 109:
				return formatDevErrorMessage('Attempt reads require an Octane signal handle.', args);
			case 110:
				return formatDevErrorMessage('Frozen derived candidates are not supported.', args);
			case 111:
				return formatDevErrorMessage('The derived attempt is no longer active.', args);
			case 112:
				return formatDevErrorMessage('A derived signal cannot read itself.', args);
			case 113:
				return formatDevErrorMessage('Signal "%s" has no selected value.', args);
			case 114:
				return formatDevErrorMessage('An async iterator must return an iteration result.', args);
			case 115:
				return formatDevErrorMessage('The stream completed without yielding a value.', args);
			case 116:
				return formatDevErrorMessage(
					'A signal control requires a native value/checked property and a signal.',
					args,
				);
			case 117:
				return formatDevErrorMessage(
					'This control property already has a signal binding. Dispose it before rebinding.',
					args,
				);
			case 118:
				return formatDevErrorMessage('A signal control subscription must return cleanup.', args);
			case 119:
				return formatDevErrorMessage('A checked signal must contain a boolean.', args);
			case 120:
				return formatDevErrorMessage('A multiple select signal must contain an array.', args);
			case 121:
				return formatDevErrorMessage('A value signal must contain a string.', args);
			case 122:
				return formatDevErrorMessage('derived$ requires a function.', args);
			case 123:
				return formatDevErrorMessage('A signal document owner requires a document.', args);
			case 124:
				return formatDevErrorMessage(
					'A streamed signal hydration owner is already installed.',
					args,
				);
			case 125:
				return formatDevErrorMessage('%s must be a nonempty string.', args);
			case 126:
				return formatDevErrorMessage('A signal seed must match scope "%s" and version 1.', args);
			case 127:
				return formatDevErrorMessage(
					'Signal seeds require unique, valid ready node entries.',
					args,
				);
			case 128:
				return formatDevErrorMessage(
					'An unavailable latest entry cannot contain a ready value or request.',
					args,
				);
			case 129:
				return formatDevErrorMessage('Async seed entries require a query identity.', args);
			case 130:
				return formatDevErrorMessage('Only async seed entries may contain a query identity.', args);
			case 131:
				return formatDevErrorMessage(
					'Signal traceLimit must be an integer from 0 through 10000.',
					args,
				);
			case 132:
				return formatDevErrorMessage('Signal key "%s" already exists in this scope.', args);
			case 133:
				return formatDevErrorMessage('Signal seed kind does not match "%s".', args);
			case 134:
				return formatDevErrorMessage('Signal key "%s" already has kind "%s".', args);
			case 135:
				return formatDevErrorMessage('Candidate frames require live, non-adopting nodes.', args);
			case 136:
				return formatDevErrorMessage(
					'Async derived candidates are not supported by this prototype.',
					args,
				);
			case 137:
				return formatDevErrorMessage('A query resource requires a description.', args);
			case 138:
				return formatDevErrorMessage(
					'Read or write a signal through its owning scope or its handle.',
					args,
				);
			case 139:
				return formatDevErrorMessage('A signal action requires a function.', args);
			case 140:
				return formatDevErrorMessage('Local hook scopes do not create SSR seeds.', args);
			case 141:
				return formatDevErrorMessage(
					'Distinct scopes in one presented graph need distinct scopeKey values.',
					args,
				);
			case 142:
				return formatDevErrorMessage('Local hook scopes do not adopt shared-state seeds.', args);
			case 143:
				return formatDevErrorMessage('The signal adoption lease has been released.', args);
			case 144:
				return formatDevErrorMessage(
					'The presented frame has no compatible ready value for "%s".',
					args,
				);
			case 145:
				return formatDevErrorMessage('The presented query definition does not match "%s".', args);
			case 146:
				return formatDevErrorMessage('Missing adoption frame for signal scope "%s".', args);
			case 147:
				return formatDevErrorMessage('createScope requires scopeKey.', args);
			case 148:
				return formatDevErrorMessage('A direct signal needs an Octane scope.', args);
			case 149:
				return formatDevErrorMessage('A direct derived signal needs an Octane scope.', args);
			case 150:
				return formatDevErrorMessage('A direct query needs an Octane scope.', args);
			case 151:
				return formatDevErrorMessage('Signal scope "%s" has been disposed.', args);
			case 152:
				return formatDevErrorMessage(
					'Signals cannot be changed during a computation, render, or adoption frame.',
					args,
				);
			case 153:
				return formatDevErrorMessage(
					'Signal "%s" depends on its own unfinished computation.',
					args,
				);
			case 154:
				return formatDevErrorMessage('Streamed signal failed with code "%s".', args);
			case 155:
				return formatDevErrorMessage(
					'Initial document signals require an implicit document owner.',
					args,
				);
			case 156:
				return formatDevErrorMessage(
					'Initial document signals must be installed once, before any signal reads or writes.',
					args,
				);
			case 157:
				return formatDevErrorMessage('A document lifecycle requires its document owner.', args);
			case 158:
				return formatDevErrorMessage(
					'A module signal needs an active signal owner. Render it in an Octane root or use runWithSignalOwner().',
					args,
				);
			case 159:
				return formatDevErrorMessage(
					'Module signal identity is assigned by the Octane compiler. Use an explicit key outside compiled code.',
					args,
				);
			case 160:
				return formatDevErrorMessage('Signal declaration options must be an object.', args);
			case 161:
				return formatDevErrorMessage('A signal declaration key must be a nonempty string.', args);
			case 162:
				return formatDevErrorMessage('A signal binding requires a signal handle.', args);
			case 163:
				return formatDevErrorMessage('Only an async signal can be retried.', args);
			case 164:
				return formatDevErrorMessage('Only a writable signal accepts set().', args);
			case 165:
				return formatDevErrorMessage('A signal subscriber must be a function.', args);
			case 166:
				return formatDevErrorMessage('derived$ requires a synchronous computation.', args);
			case 167:
				return formatDevErrorMessage(
					'A completed native render requires a renderer transaction.',
					args,
				);
			case 168:
				return formatDevErrorMessage('Native reads require a renderer transaction.', args);
			case 169:
				return formatDevErrorMessage('A native capture must be accepted before publication.', args);
			case 170:
				return formatDevErrorMessage(
					'Initial document signals require a matching version 1 scope seed.',
					args,
				);
			case 171:
				return formatDevErrorMessage(
					'Initial document signals require unique, valid node entries.',
					args,
				);
			case 172:
				return formatDevErrorMessage(
					'Unavailable initial document entries cannot contain ready data.',
					args,
				);
			case 173:
				return formatDevErrorMessage(
					'Initial document async entries require a query identity.',
					args,
				);
			case 174:
				return formatDevErrorMessage(
					'Only initial document async entries may contain a query identity.',
					args,
				);
			case 175:
				return formatDevErrorMessage(
					'Native signal revisions changed during server rendering.',
					args,
				);
			case 176:
				return formatDevErrorMessage(
					'Native signal revisions changed before server output was accepted.',
					args,
				);
			case 177:
				return formatDevErrorMessage(
					'Native signal revisions changed during server serialization.',
					args,
				);
			case 178:
				return formatDevErrorMessage(
					'A completed native server read has no serializable ready value.',
					args,
				);
			case 179:
				return formatDevErrorMessage('Multiple data scopes claim native server key %s.', args);
			case 180:
				return formatDevErrorMessage('Conflicting native signal seed for %s:%s.', args);
			case 181:
				return formatDevErrorMessage('Invalid native signal hydration manifest.', args);
			case 182:
				return formatDevErrorMessage('Invalid or duplicate native signal hydration scope.', args);
			case 183:
				return formatDevErrorMessage('Invalid initial document signal references.', args);
			case 184:
				return formatDevErrorMessage(
					'Invalid or duplicate initial document signal reference.',
					args,
				);
			case 185:
				return formatDevErrorMessage(
					'Native signal hydration requires its initial document signal seed.',
					args,
				);
			case 186:
				return formatDevErrorMessage(
					'Missing or duplicate initial document signal reference.',
					args,
				);
			case 187:
				return formatDevErrorMessage(
					'Overlapping initial document signal reference and boundary history.',
					args,
				);
			case 188:
				return formatDevErrorMessage('Multiple data scopes claim native hydration key %s.', args);
			case 189:
				return formatDevErrorMessage(
					'A signal owner environment requires current, run, and capture.',
					args,
				);
			case 190:
				return formatDevErrorMessage('A default signal owner requires a provider.', args);
			case 191:
				return formatDevErrorMessage('A signal owner callback is required.', args);
			case 192:
				return formatDevErrorMessage(
					'A server signal query observer requires an observation factory.',
					args,
				);
			case 193:
				return formatDevErrorMessage('query$ requires selector and loader functions.', args);
			case 194:
				return formatDevErrorMessage('Native hydration has no %s seed for %s:%s.', args);
			case 195:
				return formatDevErrorMessage('query requires a nonempty key and a loader function.', args);
			case 196:
				return formatDevErrorMessage('Unsupported signal query kind.', args);
			case 197:
				return formatDevErrorMessage(
					'The streamed signal completed without yielding a value.',
					args,
				);
			case 198:
				return formatDevErrorMessage('A stream query must return an async iterable.', args);
			case 199:
				return formatDevErrorMessage('A stream query returned an invalid iterator.', args);
			case 200:
				return formatDevErrorMessage('A resource must describe a query request.', args);
			case 201:
				return formatDevErrorMessage(
					'Streamed candidates are not supported by this prototype.',
					args,
				);
			case 202:
				return formatDevErrorMessage('Incompatible query definitions use the same key "%s".', args);
			case 203:
				return formatDevErrorMessage('The signal candidate has retired.', args);
			case 204:
				return formatDevErrorMessage('The request description is still pending.', args);
			case 205:
				return formatDevErrorMessage('Frozen scalar candidates are not supported.', args);
			case 206:
				return formatDevErrorMessage('Nested signal candidates are not supported.', args);
			case 207:
				return formatDevErrorMessage('Only live candidate-capable owners are supported.', args);
			case 208:
				return formatDevErrorMessage('Rebase the signal candidate before writing.', args);
			case 209:
				return formatDevErrorMessage('Native signal presentation is not installed.', args);
			case 210:
				return formatDevErrorMessage('The candidate owner changed lifetime.', args);
			case 211:
				return formatDevErrorMessage('Candidate dependency escaped its frame.', args);
			case 212:
				return formatDevErrorMessage('The native read candidate has retired.', args);
			case 213:
				return formatDevErrorMessage(
					'A signal document lifecycle requires a live document and build identity.',
					args,
				);
			case 214:
				return formatDevErrorMessage(
					'Early independent Hydrate intent queue overflow; reload the document.',
					args,
				);
			case 215:
				return formatDevErrorMessage('Invalid independent Hydrate manifest.', args);
			case 216:
				return formatDevErrorMessage('Independent Hydrate boundary identity mismatch.', args);
			case 217:
				return formatDevErrorMessage(
					'Independent Hydrate activation export is not a function.',
					args,
				);
			case 218:
				return formatDevErrorMessage('Invalid independent Hydrate sidecar.', args);
			case 219:
				return formatDevErrorMessage('Independent Hydrate build identity mismatch.', args);
			case 220:
				return formatDevErrorMessage('Independent Hydrate sidecar has no boundary.', args);
			case 221:
				return formatDevErrorMessage('Independent Hydrate boundary already registered.', args);
			case 222:
				return formatDevErrorMessage(
					'Streamed renderer response limits must be positive safe integers.',
					args,
				);
			case 223:
				return formatDevErrorMessage('A streamed renderer frame exceeded its byte budget.', args);
			case 224:
				return formatDevErrorMessage(
					'Streamed renderer delivery exceeded its pending budget.',
					args,
				);
			case 225:
				return formatDevErrorMessage('Streamed renderer delivery timed out.', args);
			case 226:
				return formatDevErrorMessage('Streamed renderer delivery failed.', args);
			case 227:
				return formatDevErrorMessage(
					'An Octane streamed renderer receiver is already installed in this realm.',
					args,
				);
			case 228:
				return formatDevErrorMessage('The pre-module streamed renderer mailbox overflowed.', args);
			case 229:
				return formatDevErrorMessage('Streamed renderer exceeded its open result budget.', args);
			case 230:
				return formatDevErrorMessage('Streamed renderer result timed out.', args);
			case 231:
				return formatDevErrorMessage('Streamed renderer entrypoint was removed.', args);
			case 232:
				return formatDevErrorMessage('The streamed renderer response has no body.', args);
			case 233:
				return formatDevErrorMessage('Malformed streamed renderer frame.', args);
			case 234:
				return formatDevErrorMessage('Streamed renderer response was canceled.', args);
			case 235:
				return formatDevErrorMessage('Streamed renderer response timed out.', args);
			case 236:
				return formatDevErrorMessage(
					'The streamed renderer response exceeded its total byte budget.',
					args,
				);
			case 237:
				return formatDevErrorMessage('The streamed renderer response ended mid-frame.', args);
			case 238:
				return formatDevErrorMessage(
					'The streamed renderer response ended before a result terminal.',
					args,
				);
			case 239:
				return formatDevErrorMessage('Streamed renderer response failed.', args);
			case 240:
				return formatDevErrorMessage('The streamed region range is detached.', args);
			case 241:
				return formatDevErrorMessage('The streamed region range is malformed.', args);
			case 242:
				return formatDevErrorMessage('Duplicate streamed control key "%s".', args);
			case 243:
				return formatDevErrorMessage('A full streamed region must be one balanced range.', args);
			case 244:
				return formatDevErrorMessage('Streamed HTML cannot preserve live control "%s".', args);
			case 245:
				return formatDevErrorMessage('Required streamed region styles are unavailable.', args);
			case 246:
				return formatDevErrorMessage('Historical read-frame adoption failed.', args);
			case 247:
				return formatDevErrorMessage('This region does not support renderer deltas.', args);
			case 248:
				return formatDevErrorMessage('Register the exact current selection first.', args);
			case 249:
				return formatDevErrorMessage('The streamed region markers do not share a parent.', args);
			case 250:
				return formatDevErrorMessage(
					'Streamed region content revisions must be nonnegative safe integers.',
					args,
				);
			case 251:
				return formatDevErrorMessage(
					'Stream receiver limits must be positive safe integers.',
					args,
				);
			case 252:
				return formatDevErrorMessage('Streamed result timed out.', args);
			case 253:
				return formatDevErrorMessage('Invalid streamed selection identity.', args);
			case 254:
				return formatDevErrorMessage('Streamed selection has the wrong authority.', args);
			case 255:
				return formatDevErrorMessage('Cannot attach a result to a stale selection.', args);
			case 256:
				return formatDevErrorMessage('A streamed result already has a consumer.', args);
			case 257:
				return formatDevErrorMessage('Invalid or duplicate streamed result sequence.', args);
			case 258:
				return formatDevErrorMessage('A streamed result must begin with open.', args);
			case 259:
				return formatDevErrorMessage('A streamed result cannot open twice.', args);
			case 260:
				return formatDevErrorMessage('A promise result emitted more than one value.', args);
			case 261:
				return formatDevErrorMessage('A promise result completed without one value.', args);
			case 262:
				return formatDevErrorMessage('Streamed result mailbox exceeded its bound.', args);
			case 263:
				return formatDevErrorMessage('Invalid or duplicate placement sequence.', args);
			case 264:
				return formatDevErrorMessage('Streamed renderer frame failed.', args);
			case 265:
				return formatDevErrorMessage('Streamed receiver was disposed.', args);
			case 266:
				return formatDevErrorMessage(
					'Streamed signal hydration requires buildId and documentId.',
					args,
				);
			case 267:
				return formatDevErrorMessage(
					'The streamed signal selection bootstrap is missing or incompatible.',
					args,
				);
			case 268:
				return formatDevErrorMessage(
					'The pre-module streamed signal selection mailbox overflowed.',
					args,
				);
			case 269:
				return formatDevErrorMessage('A streamed signal selection has the wrong authority.', args);
			case 270:
				return formatDevErrorMessage(
					'Document initialization requires full initial signal scopes.',
					args,
				);
			case 271:
				return formatDevErrorMessage(
					'DOM class groups require a valid compiler-issued class receipt.',
					args,
				);
			case 272:
				return formatDevErrorMessage(
					'A DOM host cannot mix class groups from different binding views.',
					args,
				);
			case 273:
				return formatDevErrorMessage(
					'A DOM class group does not match its compiler-issued receipt.',
					args,
				);
			case 274:
				return formatDevErrorMessage('This DOM class group already has a binding.', args);
			case 275:
				return formatDevErrorMessage('Cannot prepare a disposed DOM class group.', args);
			case 276:
				return formatDevErrorMessage(
					'Cannot commit an outdated DOM class group preparation.',
					args,
				);
			case 277:
				return formatDevErrorMessage(
					'A DOM binding hydration lease must be active and have only one root owner.',
					args,
				);
			case 278:
				return formatDevErrorMessage(
					'A DOM presentation ref must be a callback, object, or ref array.',
					args,
				);
			case 279:
				return formatDevErrorMessage('A native event binding must resolve to a function.', args);
			case 280:
				return formatDevErrorMessage(
					'Conditional hydration requires a compiler-proven caller shape.',
					args,
				);
			case 281:
				return formatDevErrorMessage(
					'Structural hydration leases require compiler-owned native nodes.',
					args,
				);
			case 282:
				return formatDevErrorMessage(
					'Native rest hydration requires an eligible closed child view.',
					args,
				);
			case 283:
				return formatDevErrorMessage(
					'Structural hydration leases do not support lists or opaque regions.',
					args,
				);
			case 284:
				return formatDevErrorMessage('Structural hydration leases require primitive text.', args);
			case 285:
				return formatDevErrorMessage(
					'Structural hydration leases require a supported child view.',
					args,
				);
			case 286:
				return formatDevErrorMessage(
					'DOM presentation cannot adopt mismatched compiler-owned ranges or nodes.',
					args,
				);
			case 287:
				return formatDevErrorMessage(
					'This opaque view cannot be constructed without its external owner.',
					args,
				);
			case 288:
				return formatDevErrorMessage(
					'A DOM presentation projection must return its synchronous scalar values.',
					args,
				);
			case 289:
				return formatDevErrorMessage(
					'A DOM presentation signal text requires a primitive value.',
					args,
				);
			case 290:
				return formatDevErrorMessage(
					'A DOM presentation initializer must return its synchronous scalar values.',
					args,
				);
			case 291:
				return formatDevErrorMessage(
					'A DOM presentation branch projection returned an unknown arm.',
					args,
				);
			case 292:
				return formatDevErrorMessage(
					'A DOM presentation child slot requires a compiler-owned fragment.',
					args,
				);
			case 293:
				return formatDevErrorMessage(
					'A DOM presentation activation must return cleanup or undefined.',
					args,
				);
			case 294:
				return formatDevErrorMessage(
					'DOM presentation requires synchronous getSnapshot() and subscribe() methods.',
					args,
				);
			case 295:
				return formatDevErrorMessage(
					'A DOM presentation mount requires a parent and its optional insertion anchor.',
					args,
				);
			case 296:
				return formatDevErrorMessage(
					'DOM presentation requires a synchronous snapshot, not a thenable.',
					args,
				);
			case 297:
				return formatDevErrorMessage(
					'Hydration binding leases require an adopted fixed native view without structural regions or controls.',
					args,
				);
			case 298:
				return formatDevErrorMessage(
					'This DOM presentation range already has a binding. Dispose it before rebinding.',
					args,
				);
			case 299:
				return formatDevErrorMessage('A DOM presentation subscription must return cleanup.', args);
			case 300:
				return formatDevErrorMessage(
					'A DOM presentation list requires a synchronous iterable.',
					args,
				);
			case 301:
				return formatDevErrorMessage(
					'A DOM presentation list cannot contain duplicate keys.',
					args,
				);
			case 302:
				return formatDevErrorMessage(
					'A DOM control binding requires its compiler-selected adapter.',
					args,
				);
			case 303:
				return formatDevErrorMessage(
					'A constructible class group requires its compiler baseline initializer.',
					args,
				);
			case 304:
				return formatDevErrorMessage('A DOM projection subscription must return cleanup.', args);
			case 305:
				return formatDevErrorMessage(
					'A DOM binding projection group requires a computation.',
					args,
				);
			case 306:
				return formatDevErrorMessage(
					'A DOM presentation key must be a string or finite number.',
					args,
				);
			case 307:
				return formatDevErrorMessage(
					'A DOM presentation key has invalid serialized identity.',
					args,
				);
			case 308:
				return formatDevErrorMessage(
					'Octane DOM bindings: an imported signal accessor performed a live read without a subscription; bind the handle directly or pass an explicit sample through BindingSource.',
					args,
				);
			case 309:
				return formatDevErrorMessage(
					'A DOM binding signal requires the native binding protocol.',
					args,
				);
			case 310:
				return formatDevErrorMessage(
					'A DOM binding signal subscription must return cleanup.',
					args,
				);
			case 311:
				return formatDevErrorMessage(
					'A whole-style DOM binding requires a style object, CSS text or null.',
					args,
				);
			case 312:
				return formatDevErrorMessage('A DOM style subscription must return cleanup.', args);
			case 313:
				return formatDevErrorMessage(
					'adoptBindings() requires an Octane-compiled .tsrx or .tsx call and a supported static view.',
					args,
				);
			case 314:
				return formatDevErrorMessage(
					'mountBindings() requires an Octane-compiled .tsrx or .tsx call.',
					args,
				);
			case 315:
				return formatDevErrorMessage(
					'A DOM class token binding requires one nonempty class token.',
					args,
				);
			case 316:
				return formatDevErrorMessage(
					'This DOM property already has a binding. Dispose it before rebinding.',
					args,
				);
			case 317:
				return formatDevErrorMessage(
					'DOM bindings require the matching compiler-stamped root.',
					args,
				);
			case 318:
				return formatDevErrorMessage(
					'DOM bindings cannot adopt a mismatched static element topology.',
					args,
				);
			case 319:
				return formatDevErrorMessage(
					'DOM bindings cannot adopt an incomplete static element topology.',
					args,
				);
			case 320:
				return formatDevErrorMessage(
					'DOM bindings require unique compiler-issued target addresses.',
					args,
				);
			case 321:
				return formatDevErrorMessage(
					'DOM bindings cannot adopt a mismatched addressed element topology.',
					args,
				);
			case 322:
				return formatDevErrorMessage(
					'DOM bindings cannot adopt an incomplete addressed element topology.',
					args,
				);
			case 323:
				return formatDevErrorMessage('DOM binding text must be a synchronous scalar.', args);
			case 324:
				return formatDevErrorMessage(
					'A whole-style DOM binding requires serialized CSS text or null.',
					args,
				);
			case 325:
				return formatDevErrorMessage(
					'DOM bindings require synchronous getSnapshot() and subscribe() methods.',
					args,
				);
			case 326:
				return formatDevErrorMessage(
					'DOM bindings require a synchronous snapshot, not a thenable.',
					args,
				);
			case 327:
				return formatDevErrorMessage(
					'A DOM binding projection must return its synchronous scalar values.',
					args,
				);
			case 328:
				return formatDevErrorMessage('A DOM binding targets an unknown element.', args);
			case 329:
				return formatDevErrorMessage(
					'A DOM binding subscription must return a cleanup function.',
					args,
				);
			case 330:
				return formatDevErrorMessage('This DOM binding view requires the general adopter.', args);
			case 331:
				return formatDevErrorMessage('Invalid independent Hydrate manifest inputs.', args);
			case 336:
				return formatDevErrorMessage(
					"`<textarea>` children must be text: strings, numbers, or arrays of them. One child was %s. A textarea's content is its default value, so it cannot contain elements; render them outside the textarea or pass a string.",
					args,
				);
			case 337:
				return formatDevErrorMessage(
					'Structural hydration leases do not support @try regions.',
					args,
				);
			case 338:
				return formatDevErrorMessage(
					'Hydration mismatch: a server-rendered range had no closing marker, so the client rendered the boundary or root that contains it instead. Something changed the server HTML after rendering, for example an HTML minifier or proxy that strips comments.',
					args,
				);
			case 339:
				return formatDevErrorMessage(
					"Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client.",
					args,
				);
			case 340:
				return formatDevErrorMessage(
					'There was an error while hydrating, so the nearest Suspense boundary, Hydrate island, or the root rendered on the client instead.',
					args,
				);
			case 341:
				return formatDevErrorMessage(
					'The server could not finish this Suspense boundary, because it suspended during a synchronous render such as renderToString, which cannot wait for data. Switched to client rendering.',
					args,
				);
			case 342:
				return formatDevErrorMessage(
					'A descriptor carried a function form action, but no element factory installed form actions. This is a bug in the Octane compiler.',
					args,
				);
			case 343:
				return formatDevErrorMessage(
					'A keyed list rollback record restored a different shape than it recorded. This is a bug in Octane.',
					args,
				);
			default:
				return formatUnknownDevErrorMessage(code);
		}
	}
	return formatProdErrorMessage(code, args);
}
