// This file is generated by scripts/error-codes/generate.mjs. Do not edit.
import {
	formatDevErrorMessage,
	formatProdErrorMessage,
	formatUnknownDevErrorMessage,
} from './error-message.js';

type ServerErrorArguments = {
	2: [];
	3: [unknown];
	4: [];
	5: [];
	6: [];
	7: [unknown];
	8: [unknown];
	9: [];
	10: [unknown];
	11: [];
	12: [unknown];
	23: [];
	30: [unknown];
	31: [];
	32: [unknown];
	34: [];
	35: [unknown];
	36: [];
	38: [];
	39: [];
	40: [];
	41: [];
	42: [];
	43: [];
	44: [];
	45: [];
	47: [unknown];
	48: [unknown];
	57: [];
	58: [];
	59: [unknown];
	60: [];
	65: [];
	68: [];
	69: [];
	70: [];
	71: [];
	73: [];
	74: [];
	80: [unknown];
	81: [];
	82: [unknown];
	83: [];
	84: [];
	85: [];
	86: [];
	87: [];
	88: [];
	89: [];
	90: [];
	91: [];
	92: [];
	93: [unknown];
	94: [];
	95: [];
	96: [unknown];
	97: [];
	98: [];
	99: [];
	100: [];
	101: [];
	102: [unknown];
	103: [];
	104: [];
	105: [];
	106: [];
	107: [];
	108: [];
	109: [];
	110: [];
	111: [];
	112: [];
	113: [unknown];
	114: [];
	115: [];
	116: [];
	117: [];
	118: [];
	119: [];
	120: [];
	121: [];
	122: [];
	123: [];
	124: [];
	125: [unknown];
	126: [unknown];
	127: [];
	128: [];
	129: [];
	130: [];
	131: [];
	132: [unknown];
	133: [unknown];
	134: [unknown, unknown];
	135: [];
	136: [];
	137: [];
	138: [];
	139: [];
	140: [];
	141: [];
	142: [];
	143: [];
	144: [unknown];
	145: [unknown];
	146: [unknown];
	147: [];
	148: [];
	149: [];
	150: [];
	151: [unknown];
	152: [];
	153: [unknown];
	154: [unknown];
	155: [];
	156: [];
	157: [];
	158: [];
	159: [];
	160: [];
	161: [];
	162: [];
	163: [];
	164: [];
	165: [];
	166: [];
	170: [];
	171: [];
	172: [];
	173: [];
	174: [];
	175: [];
	176: [];
	177: [];
	178: [];
	179: [unknown];
	180: [unknown, unknown];
	181: [];
	182: [];
	183: [];
	184: [];
	185: [];
	186: [];
	187: [];
	188: [unknown];
	189: [];
	190: [];
	191: [];
	192: [];
	193: [];
	194: [unknown, unknown, unknown];
	195: [];
	196: [];
	197: [];
	198: [];
	199: [];
	200: [];
	201: [];
	202: [unknown];
	203: [];
	204: [];
	205: [];
	206: [];
	207: [];
	208: [];
	209: [];
	210: [];
	211: [];
	213: [];
	214: [];
	215: [];
	216: [];
	217: [];
	218: [];
	219: [];
	220: [];
	221: [];
	222: [];
	223: [];
	224: [];
	225: [];
	226: [];
	227: [];
	228: [];
	229: [];
	230: [];
	231: [];
	232: [];
	233: [];
	234: [];
	235: [];
	236: [];
	237: [];
	238: [];
	239: [];
	240: [];
	241: [];
	242: [unknown];
	243: [];
	244: [unknown];
	245: [];
	246: [];
	247: [];
	248: [];
	249: [];
	250: [];
	251: [];
	252: [];
	253: [];
	254: [];
	255: [];
	256: [];
	257: [];
	258: [];
	259: [];
	260: [];
	261: [];
	262: [];
	263: [];
	264: [];
	265: [];
	266: [];
	267: [];
	268: [];
	269: [];
	270: [];
	277: [];
	306: [];
	307: [];
	331: [];
};

export function formatServerError<Code extends keyof ServerErrorArguments>(
	code: Code,
	...args: ServerErrorArguments[Code]
): string {
	if (process.env.NODE_ENV !== 'production') {
		switch (code) {
			case 2:
				return formatDevErrorMessage(
					'Children.only expected to receive a single element child.',
					args,
				);
			case 3:
				return formatDevErrorMessage(
					'Objects are not valid as an Octane child (found: %s). If you meant to render a collection of children, use an array instead.',
					args,
				);
			case 4:
				return formatDevErrorMessage(
					'cloneElement: the first argument must be an element (from createElement / JSX).',
					args,
				);
			case 5:
				return formatDevErrorMessage(
					'Can only set one of `children` or `props.dangerouslySetInnerHTML`.',
					args,
				);
			case 6:
				return formatDevErrorMessage(
					'`props.dangerouslySetInnerHTML` must be in the form `{__html: ...}`',
					args,
				);
			case 7:
				return formatDevErrorMessage(
					'`%s` is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 8:
				return formatDevErrorMessage(
					'`<%s>` is a void element tag and must neither have children nor use `dangerouslySetInnerHTML`.',
					args,
				);
			case 9:
				return formatDevErrorMessage(
					'Too many re-renders. Octane limits the number of renders to prevent an infinite loop.',
					args,
				);
			case 10:
				return formatDevErrorMessage(
					"lazy: expected the load() promise to resolve to a component function or a module with a component as its default export, got '%s'",
					args,
				);
			case 11:
				return formatDevErrorMessage(
					"A function wrapped in useEffectEvent can't be called during rendering.",
					args,
				);
			case 12:
				return formatDevErrorMessage('%s(): argument is not a Context nor a thenable', args);
			case 23:
				return formatDevErrorMessage('Server-rendered use() rejected', args);
			case 30:
				return formatDevErrorMessage('Invalid tag: %s', args);
			case 31:
				return formatDevErrorMessage(
					'If you supply `defaultValue` on a <textarea>, do not pass children.',
					args,
				);
			case 32:
				return formatDevErrorMessage(
					'octane SSR: a use(thenable) did not settle within %sms.',
					args,
				);
			case 34:
				return formatDevErrorMessage(
					'octane SSR: a root suspension no longer has resumable work.',
					args,
				);
			case 35:
				return formatDevErrorMessage(
					'octane SSR: %s root streaming passes completed without producing a shell.',
					args,
				);
			case 36:
				return formatDevErrorMessage(
					'octane SSR: a pending streamed boundary no longer has resumable work; its error escaped to an ancestor that was already flushed.',
					args,
				);
			case 38:
				return formatDevErrorMessage('The stream destination closed.', args);
			case 39:
				return formatDevErrorMessage(
					'octane SSR: destination.write() returned false but the destination cannot emit drain.',
					args,
				);
			case 40:
				return formatDevErrorMessage('The stream destination is closed.', args);
			case 41:
				return formatDevErrorMessage('octane SSR: pipe() may only be called once.', args);
			case 42:
				return formatDevErrorMessage('The render was aborted.', args);
			case 43:
				return formatDevErrorMessage('The stream consumer cancelled.', args);
			case 44:
				return formatDevErrorMessage('The readable stream is closed.', args);
			case 45:
				return formatDevErrorMessage('Server-rendered use() rejected (function)', args);
			case 47:
				return formatDevErrorMessage(
					'octane SSR: exceeded %s suspense passes — a use(thenable) never resolved. If promises are re-created on every render pass (e.g. created in an ancestor render and passed down through props), create them at their use() site or hoist them out of render.',
					args,
				);
			case 48:
				return formatDevErrorMessage(
					'octane SSR: %s consecutive streaming passes completed no boundary — a use(thenable) never resolved. If promises are re-created on every render pass (e.g. created in an ancestor render and passed down through props), create them at their use() site or hoist them out of render.',
					args,
				);
			case 57:
				return formatDevErrorMessage(
					'prerenderToNodeStream requires a Node.js runtime with process.getBuiltinModule; use prerender() in non-Node environments.',
					args,
				);
			case 58:
				return formatDevErrorMessage('Unsupported native-read compiler/runtime version.', args);
			case 59:
				return formatDevErrorMessage('%s requires an active server component.', args);
			case 60:
				return formatDevErrorMessage(
					'A component suspended without a Suspense boundary during synchronous server rendering. Use prerender() or a streaming renderer to await it.',
					args,
				);
			case 65:
				return formatDevErrorMessage(
					"Internal SSR invariant violated: ASYNC_SCOPE is not an extension of the active frame's async scope. Please file an Octane issue.",
					args,
				);
			case 68:
				return formatDevErrorMessage(
					'A signal control cannot join values from different document owners.',
					args,
				);
			case 69:
				return formatDevErrorMessage(
					'Independent Hydrate requires a build manifest in RenderOptions.',
					args,
				);
			case 70:
				return formatDevErrorMessage(
					'Independent Hydrate activation chunk is missing from the build manifest.',
					args,
				);
			case 71:
				return formatDevErrorMessage('Unsupported Octane server signal binding ABI.', args);
			case 73:
				return formatDevErrorMessage('Octane DOM bindings require unique list keys.', args);
			case 74:
				return formatDevErrorMessage('Unsupported Octane signal binding ABI.', args);
			case 80:
				return formatDevErrorMessage(
					'Independent Hydrate cannot activate a `%s` strategy because its lexical parent never runs on the client. Use load(), idle(), visible(), media(), interaction(), or never(), or remove `independent`.',
					args,
				);
			case 81:
				return formatDevErrorMessage('An optimistic source needs a live Octane scope.', args);
			case 82:
				return formatDevErrorMessage('Action operation "%s" is no longer writable.', args);
			case 83:
				return formatDevErrorMessage('An optimistic write requires ready source authority.', args);
			case 84:
				return formatDevErrorMessage(
					'An action cannot adopt authority for a different query selection.',
					args,
				);
			case 85:
				return formatDevErrorMessage(
					'Only a writable or query source can adopt an authoritative value.',
					args,
				);
			case 86:
				return formatDevErrorMessage(
					'An action needs current authority to compare receipt revisions.',
					args,
				);
			case 87:
				return formatDevErrorMessage(
					'An authority revision comparator must return a finite number.',
					args,
				);
			case 88:
				return formatDevErrorMessage('The pinned query selection is no longer current.', args);
			case 89:
				return formatDevErrorMessage('optimistic$ requires an Octane signal source.', args);
			case 90:
				return formatDevErrorMessage(
					'An optimistic source cannot use conflicting authority revision policies.',
					args,
				);
			case 91:
				return formatDevErrorMessage(
					'An optimistic subscription needs an active signal owner.',
					args,
				);
			case 92:
				return formatDevErrorMessage(
					'An optimistic write must belong to action$ or use operation.set().',
					args,
				);
			case 93:
				return formatDevErrorMessage('Action operation "%s" may have been accepted.', args);
			case 94:
				return formatDevErrorMessage(
					'action$ requires crypto.randomUUID() for operation identity.',
					args,
				);
			case 95:
				return formatDevErrorMessage('operation.set() requires a signal from optimistic$().', args);
			case 96:
				return formatDevErrorMessage('Action operation "%s" is settled.', args);
			case 97:
				return formatDevErrorMessage(
					'operation.adopt() requires exactly one optimistic source.',
					args,
				);
			case 98:
				return formatDevErrorMessage('The action is settled.', args);
			case 99:
				return formatDevErrorMessage('until() requires a read.', args);
			case 100:
				return formatDevErrorMessage('until() timeout must be a nonnegative number.', args);
			case 101:
				return formatDevErrorMessage('until() requires a pinned optimistic source.', args);
			case 102:
				return formatDevErrorMessage('The action is %s.', args);
			case 103:
				return formatDevErrorMessage('The optimistic owner was retired.', args);
			case 104:
				return formatDevErrorMessage('The pinned optimistic selection is no longer current.', args);
			case 105:
				return formatDevErrorMessage('The optimistic confirmation timed out.', args);
			case 106:
				return formatDevErrorMessage('optimistic$ requires a signal source.', args);
			case 107:
				return formatDevErrorMessage(
					'An authority revision policy must be a comparator function.',
					args,
				);
			case 108:
				return formatDevErrorMessage(
					'action$ requires a handler and an optional nonempty key.',
					args,
				);
			case 109:
				return formatDevErrorMessage('Attempt reads require an Octane signal handle.', args);
			case 110:
				return formatDevErrorMessage('Frozen derived candidates are not supported.', args);
			case 111:
				return formatDevErrorMessage('The derived attempt is no longer active.', args);
			case 112:
				return formatDevErrorMessage('A derived signal cannot read itself.', args);
			case 113:
				return formatDevErrorMessage('Signal "%s" has no selected value.', args);
			case 114:
				return formatDevErrorMessage('An async iterator must return an iteration result.', args);
			case 115:
				return formatDevErrorMessage('The stream completed without yielding a value.', args);
			case 116:
				return formatDevErrorMessage(
					'A signal control requires a native value/checked property and a signal.',
					args,
				);
			case 117:
				return formatDevErrorMessage(
					'This control property already has a signal binding. Dispose it before rebinding.',
					args,
				);
			case 118:
				return formatDevErrorMessage('A signal control subscription must return cleanup.', args);
			case 119:
				return formatDevErrorMessage('A checked signal must contain a boolean.', args);
			case 120:
				return formatDevErrorMessage('A multiple select signal must contain an array.', args);
			case 121:
				return formatDevErrorMessage('A value signal must contain a string.', args);
			case 122:
				return formatDevErrorMessage('derived$ requires a function.', args);
			case 123:
				return formatDevErrorMessage('A signal document owner requires a document.', args);
			case 124:
				return formatDevErrorMessage(
					'A streamed signal hydration owner is already installed.',
					args,
				);
			case 125:
				return formatDevErrorMessage('%s must be a nonempty string.', args);
			case 126:
				return formatDevErrorMessage('A signal seed must match scope "%s" and version 1.', args);
			case 127:
				return formatDevErrorMessage(
					'Signal seeds require unique, valid ready node entries.',
					args,
				);
			case 128:
				return formatDevErrorMessage(
					'An unavailable latest entry cannot contain a ready value or request.',
					args,
				);
			case 129:
				return formatDevErrorMessage('Async seed entries require a query identity.', args);
			case 130:
				return formatDevErrorMessage('Only async seed entries may contain a query identity.', args);
			case 131:
				return formatDevErrorMessage(
					'Signal traceLimit must be an integer from 0 through 10000.',
					args,
				);
			case 132:
				return formatDevErrorMessage('Signal key "%s" already exists in this scope.', args);
			case 133:
				return formatDevErrorMessage('Signal seed kind does not match "%s".', args);
			case 134:
				return formatDevErrorMessage('Signal key "%s" already has kind "%s".', args);
			case 135:
				return formatDevErrorMessage('Candidate frames require live, non-adopting nodes.', args);
			case 136:
				return formatDevErrorMessage(
					'Async derived candidates are not supported by this prototype.',
					args,
				);
			case 137:
				return formatDevErrorMessage('A query resource requires a description.', args);
			case 138:
				return formatDevErrorMessage(
					'Read or write a signal through its owning scope or its handle.',
					args,
				);
			case 139:
				return formatDevErrorMessage('A signal action requires a function.', args);
			case 140:
				return formatDevErrorMessage('Local hook scopes do not create SSR seeds.', args);
			case 141:
				return formatDevErrorMessage(
					'Distinct scopes in one presented graph need distinct scopeKey values.',
					args,
				);
			case 142:
				return formatDevErrorMessage('Local hook scopes do not adopt shared-state seeds.', args);
			case 143:
				return formatDevErrorMessage('The signal adoption lease has been released.', args);
			case 144:
				return formatDevErrorMessage(
					'The presented frame has no compatible ready value for "%s".',
					args,
				);
			case 145:
				return formatDevErrorMessage('The presented query definition does not match "%s".', args);
			case 146:
				return formatDevErrorMessage('Missing adoption frame for signal scope "%s".', args);
			case 147:
				return formatDevErrorMessage('createScope requires scopeKey.', args);
			case 148:
				return formatDevErrorMessage('A direct signal needs an Octane scope.', args);
			case 149:
				return formatDevErrorMessage('A direct derived signal needs an Octane scope.', args);
			case 150:
				return formatDevErrorMessage('A direct query needs an Octane scope.', args);
			case 151:
				return formatDevErrorMessage('Signal scope "%s" has been disposed.', args);
			case 152:
				return formatDevErrorMessage(
					'Signals cannot be changed during a computation, render, or adoption frame.',
					args,
				);
			case 153:
				return formatDevErrorMessage(
					'Signal "%s" depends on its own unfinished computation.',
					args,
				);
			case 154:
				return formatDevErrorMessage('Streamed signal failed with code "%s".', args);
			case 155:
				return formatDevErrorMessage(
					'Initial document signals require an implicit document owner.',
					args,
				);
			case 156:
				return formatDevErrorMessage(
					'Initial document signals must be installed once, before any signal reads or writes.',
					args,
				);
			case 157:
				return formatDevErrorMessage('A document lifecycle requires its document owner.', args);
			case 158:
				return formatDevErrorMessage(
					'A module signal needs an active signal owner. Render it in an Octane root or use runWithSignalOwner().',
					args,
				);
			case 159:
				return formatDevErrorMessage(
					'Module signal identity is assigned by the Octane compiler. Use an explicit key outside compiled code.',
					args,
				);
			case 160:
				return formatDevErrorMessage('Signal declaration options must be an object.', args);
			case 161:
				return formatDevErrorMessage('A signal declaration key must be a nonempty string.', args);
			case 162:
				return formatDevErrorMessage('A signal binding requires a signal handle.', args);
			case 163:
				return formatDevErrorMessage('Only an async signal can be retried.', args);
			case 164:
				return formatDevErrorMessage('Only a writable signal accepts set().', args);
			case 165:
				return formatDevErrorMessage('A signal subscriber must be a function.', args);
			case 166:
				return formatDevErrorMessage('derived$ requires a synchronous computation.', args);
			case 170:
				return formatDevErrorMessage(
					'Initial document signals require a matching version 1 scope seed.',
					args,
				);
			case 171:
				return formatDevErrorMessage(
					'Initial document signals require unique, valid node entries.',
					args,
				);
			case 172:
				return formatDevErrorMessage(
					'Unavailable initial document entries cannot contain ready data.',
					args,
				);
			case 173:
				return formatDevErrorMessage(
					'Initial document async entries require a query identity.',
					args,
				);
			case 174:
				return formatDevErrorMessage(
					'Only initial document async entries may contain a query identity.',
					args,
				);
			case 175:
				return formatDevErrorMessage(
					'Native signal revisions changed during server rendering.',
					args,
				);
			case 176:
				return formatDevErrorMessage(
					'Native signal revisions changed before server output was accepted.',
					args,
				);
			case 177:
				return formatDevErrorMessage(
					'Native signal revisions changed during server serialization.',
					args,
				);
			case 178:
				return formatDevErrorMessage(
					'A completed native server read has no serializable ready value.',
					args,
				);
			case 179:
				return formatDevErrorMessage('Multiple data scopes claim native server key %s.', args);
			case 180:
				return formatDevErrorMessage('Conflicting native signal seed for %s:%s.', args);
			case 181:
				return formatDevErrorMessage('Invalid native signal hydration manifest.', args);
			case 182:
				return formatDevErrorMessage('Invalid or duplicate native signal hydration scope.', args);
			case 183:
				return formatDevErrorMessage('Invalid initial document signal references.', args);
			case 184:
				return formatDevErrorMessage(
					'Invalid or duplicate initial document signal reference.',
					args,
				);
			case 185:
				return formatDevErrorMessage(
					'Native signal hydration requires its initial document signal seed.',
					args,
				);
			case 186:
				return formatDevErrorMessage(
					'Missing or duplicate initial document signal reference.',
					args,
				);
			case 187:
				return formatDevErrorMessage(
					'Overlapping initial document signal reference and boundary history.',
					args,
				);
			case 188:
				return formatDevErrorMessage('Multiple data scopes claim native hydration key %s.', args);
			case 189:
				return formatDevErrorMessage(
					'A signal owner environment requires current, run, and capture.',
					args,
				);
			case 190:
				return formatDevErrorMessage('A default signal owner requires a provider.', args);
			case 191:
				return formatDevErrorMessage('A signal owner callback is required.', args);
			case 192:
				return formatDevErrorMessage(
					'A server signal query observer requires an observation factory.',
					args,
				);
			case 193:
				return formatDevErrorMessage('query$ requires selector and loader functions.', args);
			case 194:
				return formatDevErrorMessage('Native hydration has no %s seed for %s:%s.', args);
			case 195:
				return formatDevErrorMessage('query requires a nonempty key and a loader function.', args);
			case 196:
				return formatDevErrorMessage('Unsupported signal query kind.', args);
			case 197:
				return formatDevErrorMessage(
					'The streamed signal completed without yielding a value.',
					args,
				);
			case 198:
				return formatDevErrorMessage('A stream query must return an async iterable.', args);
			case 199:
				return formatDevErrorMessage('A stream query returned an invalid iterator.', args);
			case 200:
				return formatDevErrorMessage('A resource must describe a query request.', args);
			case 201:
				return formatDevErrorMessage(
					'Streamed candidates are not supported by this prototype.',
					args,
				);
			case 202:
				return formatDevErrorMessage('Incompatible query definitions use the same key "%s".', args);
			case 203:
				return formatDevErrorMessage('The signal candidate has retired.', args);
			case 204:
				return formatDevErrorMessage('The request description is still pending.', args);
			case 205:
				return formatDevErrorMessage('Frozen scalar candidates are not supported.', args);
			case 206:
				return formatDevErrorMessage('Nested signal candidates are not supported.', args);
			case 207:
				return formatDevErrorMessage('Only live candidate-capable owners are supported.', args);
			case 208:
				return formatDevErrorMessage('Rebase the signal candidate before writing.', args);
			case 209:
				return formatDevErrorMessage('Native signal presentation is not installed.', args);
			case 210:
				return formatDevErrorMessage('The candidate owner changed lifetime.', args);
			case 211:
				return formatDevErrorMessage('Candidate dependency escaped its frame.', args);
			case 213:
				return formatDevErrorMessage(
					'A signal document lifecycle requires a live document and build identity.',
					args,
				);
			case 214:
				return formatDevErrorMessage(
					'Early independent Hydrate intent queue overflow; reload the document.',
					args,
				);
			case 215:
				return formatDevErrorMessage('Invalid independent Hydrate manifest.', args);
			case 216:
				return formatDevErrorMessage('Independent Hydrate boundary identity mismatch.', args);
			case 217:
				return formatDevErrorMessage(
					'Independent Hydrate activation export is not a function.',
					args,
				);
			case 218:
				return formatDevErrorMessage('Invalid independent Hydrate sidecar.', args);
			case 219:
				return formatDevErrorMessage('Independent Hydrate build identity mismatch.', args);
			case 220:
				return formatDevErrorMessage('Independent Hydrate sidecar has no boundary.', args);
			case 221:
				return formatDevErrorMessage('Independent Hydrate boundary already registered.', args);
			case 222:
				return formatDevErrorMessage(
					'Streamed renderer response limits must be positive safe integers.',
					args,
				);
			case 223:
				return formatDevErrorMessage('A streamed renderer frame exceeded its byte budget.', args);
			case 224:
				return formatDevErrorMessage(
					'Streamed renderer delivery exceeded its pending budget.',
					args,
				);
			case 225:
				return formatDevErrorMessage('Streamed renderer delivery timed out.', args);
			case 226:
				return formatDevErrorMessage('Streamed renderer delivery failed.', args);
			case 227:
				return formatDevErrorMessage(
					'An Octane streamed renderer receiver is already installed in this realm.',
					args,
				);
			case 228:
				return formatDevErrorMessage('The pre-module streamed renderer mailbox overflowed.', args);
			case 229:
				return formatDevErrorMessage('Streamed renderer exceeded its open result budget.', args);
			case 230:
				return formatDevErrorMessage('Streamed renderer result timed out.', args);
			case 231:
				return formatDevErrorMessage('Streamed renderer entrypoint was removed.', args);
			case 232:
				return formatDevErrorMessage('The streamed renderer response has no body.', args);
			case 233:
				return formatDevErrorMessage('Malformed streamed renderer frame.', args);
			case 234:
				return formatDevErrorMessage('Streamed renderer response was canceled.', args);
			case 235:
				return formatDevErrorMessage('Streamed renderer response timed out.', args);
			case 236:
				return formatDevErrorMessage(
					'The streamed renderer response exceeded its total byte budget.',
					args,
				);
			case 237:
				return formatDevErrorMessage('The streamed renderer response ended mid-frame.', args);
			case 238:
				return formatDevErrorMessage(
					'The streamed renderer response ended before a result terminal.',
					args,
				);
			case 239:
				return formatDevErrorMessage('Streamed renderer response failed.', args);
			case 240:
				return formatDevErrorMessage('The streamed region range is detached.', args);
			case 241:
				return formatDevErrorMessage('The streamed region range is malformed.', args);
			case 242:
				return formatDevErrorMessage('Duplicate streamed control key "%s".', args);
			case 243:
				return formatDevErrorMessage('A full streamed region must be one balanced range.', args);
			case 244:
				return formatDevErrorMessage('Streamed HTML cannot preserve live control "%s".', args);
			case 245:
				return formatDevErrorMessage('Required streamed region styles are unavailable.', args);
			case 246:
				return formatDevErrorMessage('Historical read-frame adoption failed.', args);
			case 247:
				return formatDevErrorMessage('This region does not support renderer deltas.', args);
			case 248:
				return formatDevErrorMessage('Register the exact current selection first.', args);
			case 249:
				return formatDevErrorMessage('The streamed region markers do not share a parent.', args);
			case 250:
				return formatDevErrorMessage(
					'Streamed region content revisions must be nonnegative safe integers.',
					args,
				);
			case 251:
				return formatDevErrorMessage(
					'Stream receiver limits must be positive safe integers.',
					args,
				);
			case 252:
				return formatDevErrorMessage('Streamed result timed out.', args);
			case 253:
				return formatDevErrorMessage('Invalid streamed selection identity.', args);
			case 254:
				return formatDevErrorMessage('Streamed selection has the wrong authority.', args);
			case 255:
				return formatDevErrorMessage('Cannot attach a result to a stale selection.', args);
			case 256:
				return formatDevErrorMessage('A streamed result already has a consumer.', args);
			case 257:
				return formatDevErrorMessage('Invalid or duplicate streamed result sequence.', args);
			case 258:
				return formatDevErrorMessage('A streamed result must begin with open.', args);
			case 259:
				return formatDevErrorMessage('A streamed result cannot open twice.', args);
			case 260:
				return formatDevErrorMessage('A promise result emitted more than one value.', args);
			case 261:
				return formatDevErrorMessage('A promise result completed without one value.', args);
			case 262:
				return formatDevErrorMessage('Streamed result mailbox exceeded its bound.', args);
			case 263:
				return formatDevErrorMessage('Invalid or duplicate placement sequence.', args);
			case 264:
				return formatDevErrorMessage('Streamed renderer frame failed.', args);
			case 265:
				return formatDevErrorMessage('Streamed receiver was disposed.', args);
			case 266:
				return formatDevErrorMessage(
					'Streamed signal hydration requires buildId and documentId.',
					args,
				);
			case 267:
				return formatDevErrorMessage(
					'The streamed signal selection bootstrap is missing or incompatible.',
					args,
				);
			case 268:
				return formatDevErrorMessage(
					'The pre-module streamed signal selection mailbox overflowed.',
					args,
				);
			case 269:
				return formatDevErrorMessage('A streamed signal selection has the wrong authority.', args);
			case 270:
				return formatDevErrorMessage(
					'Document initialization requires full initial signal scopes.',
					args,
				);
			case 277:
				return formatDevErrorMessage(
					'A DOM binding hydration lease must be active and have only one root owner.',
					args,
				);
			case 306:
				return formatDevErrorMessage(
					'A DOM presentation key must be a string or finite number.',
					args,
				);
			case 307:
				return formatDevErrorMessage(
					'A DOM presentation key has invalid serialized identity.',
					args,
				);
			case 331:
				return formatDevErrorMessage('Invalid independent Hydrate manifest inputs.', args);
			default:
				return formatUnknownDevErrorMessage(code);
		}
	}
	return formatProdErrorMessage(code, args);
}
