// Generated by scripts/generate-tsrx-types.mjs.
import type { PickD3Scale } from '@octanejs/visx/scale';
import type { LegendProps } from './Legend/index.tsrx';
type AnyLinearScale = PickD3Scale<'linear', any>;
export type LegendLinearProps<Scale extends AnyLinearScale> = {
    /** Number of discrete steps to show in the legend. The scale domain is divided into this many intervals. */
    steps?: number;
} & LegendProps<Scale>;
/** Linear scales map from continuous inputs to continuous outputs. */
export default function Linear<Scale extends AnyLinearScale>({ scale, domain: inputDomain, steps, ...restProps }: LegendLinearProps<Scale>): import("react").JSX.Element;
export {};
