// Generated by scripts/generate-tsrx-types.mjs.
import type { PickD3Scale } from '@octanejs/visx/scale';
import type { LegendProps } from './Legend/index.tsrx';
type AnyOrdinalScale = PickD3Scale<'ordinal', any, any>;
export type LegendOrdinalProps<Scale extends AnyOrdinalScale> = LegendProps<Scale>;
/** Ordinal scales map from strings to an Output type. */
export default function Ordinal<Scale extends AnyOrdinalScale>(props: LegendOrdinalProps<Scale>): import("react").JSX.Element;
export {};
