// Generated by scripts/generate-tsrx-types.mjs.
import type { PickD3Scale } from '@octanejs/visx/scale';
import type { LegendProps } from './Legend/index.tsrx';
type AnyQuantileScale = PickD3Scale<'quantile', any>;
type FactoryProps = {
    /** The delimiter string to use between the min and max values in the label (e.g., '-' renders as '0 - 10'). */
    labelDelimiter?: string;
};
export type LegendQuantileProps<Scale extends AnyQuantileScale> = LegendProps<Scale> & FactoryProps;
/** A Quantile scale takes a number input and returns an Output. */
export default function Quantile<Scale extends AnyQuantileScale>({ domain: inputDomain, scale, labelFormat, labelTransform: inputLabelTransform, labelDelimiter, ...restProps }: LegendQuantileProps<Scale>): import("react").JSX.Element;
export {};
