// Generated by scripts/generate-tsrx-types.mjs.
import type { D3Scale } from '@octanejs/visx/scale';
import type { LegendProps } from './Legend/index.tsrx';
type AnySizeScale = D3Scale<number, any, any>;
export type LegendSizeProps<Scale extends AnySizeScale> = {
    /** Number of discrete steps to show in the legend. The scale domain is divided into this many intervals. */
    steps?: number;
} & LegendProps<Scale>;
/**
 * A Size legend component that creates a legend with discrete size intervals.
 * Useful for visualizing continuous numeric data with size-based scales.
 */
export default function Size<Scale extends AnySizeScale>({ scale, domain: inputDomain, steps, labelFormat, labelTransform, ...restProps }: LegendSizeProps<Scale>): import("react").JSX.Element;
export {};
