// Generated by scripts/generate-tsrx-types.mjs.
import type { PickD3Scale } from '@octanejs/visx/scale';
import type { LegendProps } from './Legend/index.tsrx';
import type { LabelFormatterFactory } from '../types';
type AnyThresholdScale = PickD3Scale<'threshold', any, any, any>;
type TransformProps = {
    /** The delimiter string to use between threshold values (e.g., '-' renders as '0 - 10'). */
    labelDelimiter?: string;
    /** The prefix to use for the lower threshold label (e.g., '<' renders as '< 10'). */
    labelLower?: string;
    /** The prefix to use for the upper threshold label (e.g., '>' renders as '> 100'). */
    labelUpper?: string;
};
export type LegendThresholdProps<Scale extends AnyThresholdScale> = LegendProps<Scale> & TransformProps & {
    labelTransform?: LabelFormatterFactory<Scale>;
};
/**
 * A Threshold legend component for threshold scales.
 * Threshold scales map continuous input values to discrete output values based on threshold boundaries.
 * This component displays the threshold ranges with customizable delimiters and labels.
 */
export default function Threshold<Scale extends AnyThresholdScale>({ scale, domain: inputDomain, labelFormat, labelTransform: inputLabelTransform, labelDelimiter, labelLower, labelUpper, ...restProps }: LegendThresholdProps<Scale>): import("react").JSX.Element;
export {};
