/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsrx'
import { Route as IndexRouteImport } from './routes/index.tsrx'
import { Route as BenchmarksRouteImport } from './routes/benchmarks.tsrx'
import { Route as DocsRouteImport } from './routes/docs.tsrx'
import { Route as ErrorsRouteImport } from './routes/errors.tsrx'
import { Route as PlaygroundRouteImport } from './routes/playground.tsrx'
import { Route as DocsIndexRouteImport } from './routes/docs.index.tsrx'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug.tsrx'
import { Route as ErrorsIndexRouteImport } from './routes/errors.index.tsrx'
import { Route as ErrorsCodeRouteImport } from './routes/errors.$code.tsrx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const ErrorsIndexRoute = ErrorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ErrorsRoute,
} as any)
const ErrorsCodeRoute = ErrorsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => ErrorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/docs': typeof DocsRouteWithChildren
  '/errors': typeof ErrorsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/errors/$code': typeof ErrorsCodeRoute
  '/docs/': typeof DocsIndexRoute
  '/errors/': typeof ErrorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/playground': typeof PlaygroundRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/errors/$code': typeof ErrorsCodeRoute
  '/docs': typeof DocsIndexRoute
  '/errors': typeof ErrorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/docs': typeof DocsRouteWithChildren
  '/errors': typeof ErrorsRouteWithChildren
  '/playground': typeof PlaygroundRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/errors/$code': typeof ErrorsCodeRoute
  '/docs/': typeof DocsIndexRoute
  '/errors/': typeof ErrorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/docs'
    | '/errors'
    | '/playground'
    | '/docs/$slug'
    | '/errors/$code'
    | '/docs/'
    | '/errors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/playground'
    | '/docs/$slug'
    | '/errors/$code'
    | '/docs'
    | '/errors'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/docs'
    | '/errors'
    | '/playground'
    | '/docs/$slug'
    | '/errors/$code'
    | '/docs/'
    | '/errors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  DocsRoute: typeof DocsRouteWithChildren
  ErrorsRoute: typeof ErrorsRouteWithChildren
  PlaygroundRoute: typeof PlaygroundRoute
}

declare module '@tanstack/octane-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/errors/': {
      id: '/errors/'
      path: '/'
      fullPath: '/errors/'
      preLoaderRoute: typeof ErrorsIndexRouteImport
      parentRoute: typeof ErrorsRoute
    }
    '/errors/$code': {
      id: '/errors/$code'
      path: '/$code'
      fullPath: '/errors/$code'
      preLoaderRoute: typeof ErrorsCodeRouteImport
      parentRoute: typeof ErrorsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ErrorsRouteChildren {
  ErrorsCodeRoute: typeof ErrorsCodeRoute
  ErrorsIndexRoute: typeof ErrorsIndexRoute
}

const ErrorsRouteChildren: ErrorsRouteChildren = {
  ErrorsCodeRoute: ErrorsCodeRoute,
  ErrorsIndexRoute: ErrorsIndexRoute,
}

const ErrorsRouteWithChildren =
  ErrorsRoute._addFileChildren(ErrorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  DocsRoute: DocsRouteWithChildren,
  ErrorsRoute: ErrorsRouteWithChildren,
  PlaygroundRoute: PlaygroundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/octane-start'
declare module '@tanstack/octane-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
