// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { transform } from 'esbuild';
import { RenderRoute } from '../src/routes.js';
import {
	create_client_entry_source,
	generateServerEntry,
	generateServerManifestEntry,
	normalize_module_reference,
} from '../src/codegen.js';

describe('bundler-neutral app codegen', () => {
	it('keeps stable hydration IDs separate from emitted import specifiers', async () => {
		const source = create_client_entry_source({
			staticEntries: [
				{ id: '/src/Page.tsrx', specifier: '/workspace/src/Page.tsrx' },
				'/src/Layout.tsrx',
			],
			resolveImport: (id) => `/workspace${id}`,
			runtimeModuleId: '@renderer/client',
			generatedBy: '@test/integration',
		});

		expect(source).toContain('"/src/Page.tsrx": () => import("/workspace/src/Page.tsrx")');
		expect(source).toContain('"/src/Layout.tsrx": () => import("/workspace/src/Layout.tsrx")');
		expect(source).toContain('from "@renderer/client"');
		expect(source).toContain('Auto-generated by @test/integration');
		const initializeIndex = source.indexOf('initializeHydrationEventCapture();');
		expect(initializeIndex).toBeGreaterThan(-1);
		expect(initializeIndex).toBeLessThan(source.indexOf('(async () =>'));
		await expect(transform(source, { loader: 'js' })).resolves.toBeDefined();
	});

	it('emits a template-free server manifest with mapped imports', async () => {
		const source = generateServerManifestEntry({
			routes: [new RenderRoute({ path: '/', entry: '/src/Page.tsrx' })],
			octaneConfigPath: '/workspace/octane.config.ts',
			moduleImports: {
				'/src/Page.tsrx': '/workspace/src/Page.tsrx',
			},
			configImportPath: '/workspace/octane.config.ts',
			serverRuntimeModuleId: '@renderer/server',
			staticRuntimeModuleId: '@renderer/static',
		});

		expect(source).toContain('from "/workspace/src/Page.tsrx"');
		expect(source).toContain('"/src/Page.tsrx": _page_0');
		expect(source).toContain('export const manifest =');
		expect(source).toContain('export const rendererDeps =');
		expect(source).not.toContain("readFileSync(join(__dirname, './index.html')");
		expect(source).not.toContain('isMainModule');
		await expect(transform(source, { loader: 'js' })).resolves.toBeDefined();
	});

	it('can load a late client asset map beside the production server entry', () => {
		const source = generateServerEntry({
			routes: [new RenderRoute({ path: '/', entry: '/src/Page.tsrx' })],
			octaneConfigPath: '/workspace/octane.config.ts',
			clientAssetMapFile: 'client-assets.json',
		});
		expect(source).toContain(
			'JSON.parse(readFileSync(join(__dirname, "client-assets.json"), \'utf-8\'))',
		);
	});

	it('normalizes in-root files to stable project module IDs', () => {
		expect(normalize_module_reference('/workspace/src/Page.tsrx', '/workspace')).toBe(
			'/src/Page.tsrx',
		);
		expect(normalize_module_reference('/shared/Page.tsrx', '/workspace')).toBe('/shared/Page.tsrx');
	});
});
