// Generated by scripts/generate-tsrx-types.mjs.
import type { LinkProvidedProps } from './types';
export default function DefaultLink({ link }: LinkProvidedProps<any>): import("react").JSX.Element | null;
