// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
export type NodeProps = {
    cx?: number;
    cy?: number;
    node?: unknown;
};
export default function DefaultNode({ r, fill, node, // Accept but don't use the node prop
...rest }: NodeProps & Omit<Octane.SVGProps<SVGCircleElement>, keyof NodeProps>): import("react").JSX.Element;
