// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
export type NodeProps = {
    cx?: number;
    cy?: number;
    node?: unknown;
};
export default function DefaultNode({ r, fill, node, // Accept but don't use the node prop
...rest }: NodeProps & Omit<SVGProps<SVGCircleElement>, keyof NodeProps>): import("react").JSX.Element;
