// Generated by scripts/generate-tsrx-types.mjs.
import type { FunctionComponent, ComponentClass } from 'react';
import type { LinkProvidedProps } from './types';
export type LinkProps<Link> = {
    /** Array of links to render. */
    links?: Link[];
    /** Component for rendering a single link. */
    linkComponent: FunctionComponent<LinkProvidedProps<Link>> | ComponentClass<LinkProvidedProps<Link>>;
    /** Classname to add to each link parent g element. */
    className?: string;
};
export default function Links<Link>({ links, linkComponent, className }: LinkProps<Link>): import("react").JSX.Element;
