// Generated by scripts/generate-tsrx-types.mjs.
import type { FunctionComponent, ComponentClass } from 'react';
import type { NodeProvidedProps } from './types';
export type NodeProps<Node> = {
    /** Array of links to render. */
    nodes?: Node[];
    /** Component for rendering a single link. */
    nodeComponent: FunctionComponent<NodeProvidedProps<Node>> | ComponentClass<NodeProvidedProps<Node>>;
    /** Classname to add to each node parent g element. */
    className?: string;
    /** Returns the center x coordinate of a node. */
    x?: (d: Node) => number;
    /** Returns the center y coordinate of a node. */
    y?: (d: Node) => number;
};
export default function Nodes<Node>({ nodes, nodeComponent, className, x, // eslint-disable-line @typescript-eslint/no-explicit-any
y, }: NodeProps<Node>): import("react").JSX.Element;
