// Generated by scripts/generate-tsrx-types.mjs.
import type { AnnotationContextType } from '../types';
declare const AnnotationContext: import("octane").Context<AnnotationContextType>;
export default AnnotationContext;
