// Generated by scripts/generate-tsrx-types.mjs.
import type { TextProps as TxtProps } from './types';
export type TextProps = TxtProps;
export default function Text(props: TextProps): import("react").JSX.Element;
