// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
declare const _default: import("octane").ComponentBody<Omit<SVGProps<SVGPathElement>, "ref">, any>;
export default _default;
