// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
declare function AnimatedPath({ d, stroke, fill, ...lineProps }: Omit<Octane.SVGProps<SVGPathElement>, 'ref'>): import("react").JSX.Element;
declare const _default: typeof AnimatedPath & {
    readonly type: typeof AnimatedPath;
    displayName?: string;
};
export default _default;
