// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
declare const _default: import("octane").ComponentBody<Omit<Octane.SVGProps<SVGPathElement>, "ref">, any>;
export default _default;
