// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BarsProps } from '../../../types';
/** Wrapper component which renders a Bars component depending on whether it needs rounded corners. */
export default function AnimatedBars<XScale extends AxisScale, YScale extends AxisScale>(props: BarsProps<XScale, YScale>): import("react").JSX.Element;
