// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BarsProps } from '../../../types';
export default function Bars({ bars, horizontal, xScale, yScale, radius, radiusAll, radiusTop, radiusRight, radiusBottom, radiusLeft, ...restProps }: BarsProps<AxisScale, AxisScale>): import("react").JSX.Element;
