// Generated by scripts/generate-tsrx-types.mjs.
import type { FC, SVGProps } from 'react';
import type { AxisScale } from '@octanejs/visx/axis';
import type { AreaProps, LinePathProps } from '@octanejs/visx/shape';
import type { SeriesProps } from '../../../types';
export type BaseAreaSeriesProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = SeriesProps<XScale, YScale, Datum> & {
    /** Optional accessor to override the baseline value of Area shapes per datum (useful to generate band shapes) when chart is rendered horizontally (vertical line). Defaults to the scale zero value, not compatible with AreaStack. */
    x0Accessor?: SeriesProps<XScale, YScale, Datum>['xAccessor'];
    /** Optional accessor to override the baseline value of Area shapes per datum (useful to generate band shapes). Defaults to the scale zero value, not compatible with AreaStack. */
    y0Accessor?: SeriesProps<XScale, YScale, Datum>['yAccessor'];
    /** Whether to render a Line along value of the Area shape (area is fill only). */
    renderLine?: boolean;
    /** Sets the curve factory (from @octanejs/visx/curve or d3-curve) for the line generator. Defaults to curveLinear. */
    curve?: AreaProps<Datum>['curve'];
    /** Props to be passed to the Line, if rendered. */
    lineProps?: Omit<LinePathProps<Datum> & SVGProps<SVGPathElement>, 'data' | 'x' | 'y' | 'children' | 'defined'>;
    /** Rendered component which is passed path props by BaseAreaSeries after processing. */
    PathComponent?: FC<Omit<SVGProps<SVGPathElement>, 'ref'>> | 'path';
} & Omit<SVGProps<SVGPathElement>, 'x' | 'y' | 'x0' | 'x1' | 'y0' | 'y1' | 'ref'>;
export default function BaseAreaSeriesWithRegisteredData<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(props: BaseAreaSeriesProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
