// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactElement, FC, SVGProps } from 'react';
import type { AxisScale } from '@octanejs/visx/axis';
import type { StackPathConfig, AreaProps } from '@octanejs/visx/shape';
import type { SeriesProps } from '../../../types';
import type { BaseAreaSeriesProps } from './BaseAreaSeries.tsrx';
type AreaStackChildProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = Omit<BaseAreaSeriesProps<XScale, YScale, Datum>, 'PathComponent' | 'curve'>;
export type BaseAreaStackProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = {
    /** `AreaSeries` elements, note we can't strictly enforce this with TS yet. */
    children: ReactElement<AreaStackChildProps<XScale, YScale, Datum>> | ReactElement<AreaStackChildProps<XScale, YScale, Datum>>[];
    /** Rendered component which is passed path props by BaseAreaStack after processing. */
    PathComponent?: FC<Omit<SVGProps<SVGPathElement>, 'ref'>> | 'path';
    /** Sets the curve factory (from @octanejs/visx/curve or d3-curve) for the line generator. Defaults to curveLinear. */
    curve?: AreaProps<Datum>['curve'];
    /** Whether to render a Line along value of the Area shape (area is fill only). */
    renderLine?: boolean;
} & Pick<StackPathConfig<Datum, string>, 'offset' | 'order'> & Pick<SeriesProps<XScale, YScale, Datum>, 'onPointerMove' | 'onPointerOut' | 'onPointerUp' | 'onPointerDown' | 'onBlur' | 'onFocus' | 'enableEvents'>;
declare function BaseAreaStack<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ PathComponent, children, curve, enableEvents, offset, onBlur, onFocus, onPointerMove, onPointerOut, onPointerUp, onPointerDown, order, renderLine, }: BaseAreaStackProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
export default BaseAreaStack;
