// Generated by scripts/generate-tsrx-types.mjs.
import type { FC, SVGProps } from 'react';
import type { LinePathProps } from '@octanejs/visx/shape';
import type { AxisScale } from '@octanejs/visx/axis';
import type { SeriesProps } from '../../../types';
export type BaseLineSeriesProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = SeriesProps<XScale, YScale, Datum> & {
    /** Rendered component which is passed path props by BaseLineSeries after processing. */
    PathComponent?: FC<Omit<SVGProps<SVGPathElement>, 'ref'>> | 'path';
    /** Sets the curve factory (from @octanejs/visx/curve or d3-curve) for the line generator. Defaults to curveLinear. */
    curve?: LinePathProps<Datum>['curve'];
    /** Given a datakey, returns its color. Falls back to theme color if unspecified or if a null-ish value is returned. */
    colorAccessor?: (dataKey: string) => string | undefined | null;
} & Omit<SVGProps<SVGPathElement>, 'x' | 'y' | 'x0' | 'x1' | 'y0' | 'y1' | 'ref'>;
export default function BaseBaseLineSeriesWithRegisteredData<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(props: BaseLineSeriesProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
