// Generated by scripts/generate-tsrx-types.mjs.
import type { FC } from 'react';
import type { AxisScale } from '@octanejs/visx/axis';
import type { BarsProps, SeriesProps } from '../../../types';
export type BaseBarSeriesProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = SeriesProps<XScale, YScale, Datum> & {
    /** Rendered component which is passed BarsProps by BaseBarSeries after processing. */
    BarsComponent: FC<BarsProps<XScale, YScale>>;
    /**
* Specify bar padding when bar thickness does not come from a `band` scale.
* Accepted values are [0, 1], 0 = no padding, 1 = no bar, defaults to 0.1.
*/
    barPadding?: number;
    /** Given a Datum, returns its color. Falls back to theme color if unspecified or if a null-ish value is returned. */
    colorAccessor?: (d: Datum, index: number) => string | null | undefined;
} & Pick<BarsProps<XScale, YScale>, 'radius' | 'radiusAll' | 'radiusTop' | 'radiusRight' | 'radiusBottom' | 'radiusLeft'>;
export default function BaseBarSeriesWithRegisteredData<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(props: BaseBarSeriesProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
