// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactElement, FC } from 'react';
import type { PositionScale, StackPathConfig } from '@octanejs/visx/shape';
import type { BaseBarSeriesProps } from './BaseBarSeries.tsrx';
import type { BarsProps, SeriesProps } from '../../../types';
type BarStackChildProps<XScale extends PositionScale, YScale extends PositionScale, Datum extends object> = Omit<BaseBarSeriesProps<XScale, YScale, Datum>, 'BarsComponent'>;
export type BaseBarStackProps<XScale extends PositionScale, YScale extends PositionScale, Datum extends object> = {
    /** `BarSeries` elements, note we can't strictly enforce this with TS yet. */
    children: ReactElement<BarStackChildProps<XScale, YScale, Datum>> | ReactElement<BarStackChildProps<XScale, YScale, Datum>>[];
    /** Rendered component which is passed BarsProps by BaseBarStack after processing. */
    BarsComponent: FC<BarsProps<XScale, YScale>>;
} & Pick<StackPathConfig<Datum, string>, 'offset' | 'order'> & Pick<SeriesProps<XScale, YScale, Datum>, 'onPointerMove' | 'onPointerOut' | 'onPointerUp' | 'onPointerDown' | 'onBlur' | 'onFocus' | 'enableEvents'>;
declare function BaseBarStack<XScale extends PositionScale, YScale extends PositionScale, Datum extends object>({ children, order, offset, BarsComponent, onBlur, onFocus, onPointerMove, onPointerOut, onPointerUp, onPointerDown, enableEvents, }: BaseBarStackProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
export default BaseBarStack;
