// Generated by scripts/generate-tsrx-types.mjs.
import type { FC } from 'react';
import type { OctaneNode } from 'octane';
import type { PositionScale } from '@octanejs/visx/shape';
import type { BarsProps, SeriesProps } from '../../../types';
export type BaseBarGroupProps<XScale extends PositionScale, YScale extends PositionScale, Datum extends object> = {
    /** `BarSeries` elements */
    children: OctaneNode;
    /** Group band scale padding, [0, 1] where 0 = no padding, 1 = no bar. */
    padding?: number;
    /** Comparator function to sort `dataKeys` within a bar group. By default the DOM rendering order of `BarGroup`s `children` is used. */
    sortBars?: (dataKeyA: string, dataKeyB: string) => number;
    /** Rendered component which is passed BarsProps by BaseBarGroup after processing. */
    BarsComponent: FC<BarsProps<XScale, YScale>>;
} & Pick<SeriesProps<XScale, YScale, Datum>, 'onPointerMove' | 'onPointerOut' | 'onPointerUp' | 'onPointerDown' | 'onBlur' | 'onFocus' | 'enableEvents'>;
export default function BaseBarGroup<XScale extends PositionScale, YScale extends PositionScale, Datum extends object>({ children, padding, sortBars, BarsComponent, onBlur, onFocus, onPointerMove, onPointerOut, onPointerUp, onPointerDown, enableEvents, }: BaseBarGroupProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
