// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { AxisScale } from '@octanejs/visx/axis';
import type { DataContextType, GlyphsProps, SeriesProps } from '../../../types';
export type BaseGlyphSeriesProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = SeriesProps<XScale, YScale, Datum> & {
    /** Given a Datum, returns its color. Falls back to theme color if unspecified or if a null-ish value is returned. */
    colorAccessor?: (d: Datum, index: number) => string | null | undefined;
    /** The size of a `Glyph`, a `number` or a function which takes a `Datum` and returns a `number`. */
    size?: number | ((d: Datum) => number);
    /** Function which handles rendering glyphs. */
    renderGlyphs: (glyphsProps: GlyphsProps<XScale, YScale, Datum>) => OctaneNode;
};
export declare function BaseGlyphSeries<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ colorAccessor, data, dataKey, onBlur, onFocus, onPointerMove, onPointerOut, onPointerUp, onPointerDown, enableEvents, renderGlyphs, size, xAccessor, xScale, yAccessor, yScale, }: BaseGlyphSeriesProps<XScale, YScale, Datum> & Pick<DataContextType<XScale, YScale, Datum>, 'xScale' | 'yScale'>): import("react").JSX.Element;
export default function BaseGlyphSeriesWithRegisteredData<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(props: BaseGlyphSeriesProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
