// Generated by scripts/generate-tsrx-types.mjs.
import type { GlyphProps } from '../../../types';
export default function defaultRenderGlyph<Datum extends object>({ key, color, x, y, size, onBlur, onFocus, onPointerMove, onPointerOut, onPointerUp, }: GlyphProps<Datum>): import("react").JSX.Element;
