// Generated by scripts/generate-tsrx-types.mjs.
/** Return samples along a path, relative to the parent SVG  */
export default function useSamplesAlongPath(restrictToPath?: SVGGeometryElement | null): never[];
