// Generated by scripts/generate-tsrx-types.mjs.
/** biome-ignore-all lint/a11y/noSvgWithoutTitle: "Streamdown icons" */
import type { SVGProps } from './types';
type IconProps = SVGProps<SVGSVGElement>;
export declare const CheckIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const CopyIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const DownloadIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const Loader2Icon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const Maximize2Icon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const RotateCcwIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const XIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const ExternalLinkIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const ZoomInIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const ZoomOutIcon: (props: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
