// Generated by scripts/generate-tsrx-types.mjs.
/** biome-ignore-all lint/a11y/noSvgWithoutTitle: "Streamdown icons" */
import type { SVGProps } from './types';
type IconProps = SVGProps<SVGSVGElement> & {
    size?: number;
};
export declare const CheckIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const CopyIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const DownloadIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const Loader2Icon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const Maximize2Icon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const RotateCcwIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const XIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const ExternalLinkIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const ZoomInIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const ZoomOutIcon: ({ size, ...props }: IconProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
