// Generated by scripts/generate-tsrx-types.mjs.
import { type ComponentBody, type OctaneNode } from 'octane';
import type { SVGProps } from './types';
export type IconComponent = ComponentBody<SVGProps<SVGSVGElement> & {
    size?: number;
}>;
export interface IconMap {
    CheckIcon: IconComponent;
    CopyIcon: IconComponent;
    DownloadIcon: IconComponent;
    ExternalLinkIcon: IconComponent;
    Loader2Icon: IconComponent;
    Maximize2Icon: IconComponent;
    RotateCcwIcon: IconComponent;
    XIcon: IconComponent;
    ZoomInIcon: IconComponent;
    ZoomOutIcon: IconComponent;
}
export declare const defaultIcons: IconMap;
export declare const IconContext: import("octane").Context<IconMap>;
export declare const IconProvider: ({ icons, children, }: {
    icons?: Partial<IconMap>;
    children: OctaneNode;
}) => import("octane/jsx-runtime").Octane.JSX.Element;
export declare const useIcons: () => IconMap;
