// Generated by scripts/generate-tsrx-types.mjs.
import type { ExtraProps } from './markdown.tsrx';
import type { DetailedHTMLProps, ImgHTMLAttributes } from './types';
type ImageComponentProps = DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement> & ExtraProps;
export declare const ImageComponent: ({ node, className, src, alt, onLoad: onLoadProp, onError: onErrorProp, ...props }: ImageComponentProps) => import("octane/jsx-runtime").Octane.JSX.Element | null;
export {};
