// Generated by scripts/generate-tsrx-types.mjs.
interface LinkSafetyModalProps {
    isOpen: boolean;
    onClose: () => void;
    onConfirm: () => void;
    url: string;
}
export declare const LinkSafetyModal: ({ url, isOpen, onClose, onConfirm }: LinkSafetyModalProps) => import("octane/jsx-runtime").Octane.JSX.Element | null;
export {};
