// Generated by scripts/generate-tsrx-types.mjs.
import type { Element, Parents } from 'hast';
import type { Octane } from 'octane/jsx-runtime';
import { type ComponentBody, type ElementDescriptor } from 'octane';
import type { Options as RemarkRehypeOptions } from 'remark-rehype';
import type { PluggableList } from 'unified';
import type { ComponentProps } from './types';
export interface ExtraProps {
    node?: Element | undefined;
}
export type AllowElement = (element: Readonly<Element>, index: number, parent: Readonly<Parents> | undefined) => boolean | null | undefined;
export type UrlTransform = (url: string, key: string, node: Readonly<Element>) => string | null | undefined;
export type Components = {
    [Key in keyof Octane.JSX.IntrinsicElements]?: ComponentBody<Octane.JSX.IntrinsicElements[Key] & ExtraProps> | keyof Octane.JSX.IntrinsicElements;
} & {
    inlineCode?: ComponentBody<ComponentProps<'code'> & ExtraProps>;
    [key: string]: ComponentBody<Record<string, unknown> & ExtraProps> | keyof Octane.JSX.IntrinsicElements | undefined;
};
export interface Options {
    allowElement?: AllowElement;
    allowedElements?: readonly string[];
    children?: string;
    components?: Components;
    disallowedElements?: readonly string[];
    rehypePlugins?: PluggableList;
    remarkPlugins?: PluggableList;
    remarkRehypeOptions?: Readonly<RemarkRehypeOptions>;
    skipHtml?: boolean;
    unwrapDisallowed?: boolean;
    urlTransform?: UrlTransform;
}
export declare const Markdown: (options: Readonly<Options>) => ElementDescriptor<any>;
export declare const defaultUrlTransform: UrlTransform;
