// Generated by scripts/generate-tsrx-types.mjs.
import type { PluginConfig } from './plugin-types';
/**
 * Context for Streamdown plugins
 */
export declare const PluginContext: import("octane").Context<PluginConfig | null>;
/**
 * Hook to access all plugins
 */
export declare const usePlugins: () => PluginConfig | null;
/**
 * Hook to access the code plugin
 */
export declare const useCodePlugin: () => import("./plugin-types").CodeHighlighterPlugin | null;
/**
 * Hook to access the mermaid plugin
 */
export declare const useMermaidPlugin: () => import("./plugin-types").DiagramPlugin | null;
/**
 * Hook to access the math plugin
 */
export declare const useMathPlugin: () => import("./plugin-types").MathPlugin | null;
/**
 * Hook to access the cjk plugin
 */
export declare const useCjkPlugin: () => import("./plugin-types").CjkPlugin | null;
/**
 * Hook to find a custom renderer for a given language
 */
export declare const useCustomRenderer: (language: string) => import("./plugin-types").CustomRenderer | null;
