// Generated by scripts/generate-tsrx-types.mjs.
import { type CnFunction } from './utils';
/**
 * Context for providing a prefix-aware `cn` function to all components.
 * Defaults to the standard `cn` (no prefix) for zero-overhead when unused.
 */
export declare const PrefixContext: import("octane").Context<CnFunction>;
/**
 * Hook to access the prefix-aware `cn` function.
 * When a prefix is set via `<Streamdown prefix="...">`, this returns
 * a `cn` that prepends the prefix to all class names.
 */
export declare const useCn: () => CnFunction;
