// Generated by scripts/generate-tsrx-types.mjs.
export interface StreamdownTranslations {
    close: string;
    copied: string;
    copyCode: string;
    copyLink: string;
    copyTable: string;
    copyTableAsCsv: string;
    copyTableAsMarkdown: string;
    copyTableAsTsv: string;
    downloadDiagram: string;
    downloadDiagramAsMmd: string;
    downloadDiagramAsPng: string;
    downloadDiagramAsSvg: string;
    downloadFile: string;
    downloadImage: string;
    downloadTable: string;
    downloadTableAsCsv: string;
    downloadTableAsMarkdown: string;
    exitFullscreen: string;
    externalLinkWarning: string;
    imageNotAvailable: string;
    mermaidFormatMmd: string;
    mermaidFormatPng: string;
    mermaidFormatSvg: string;
    openExternalLink: string;
    openLink: string;
    tableFormatCsv: string;
    tableFormatMarkdown: string;
    tableFormatTsv: string;
    viewFullscreen: string;
}
export declare const defaultTranslations: StreamdownTranslations;
export declare const TranslationsContext: import("octane").Context<StreamdownTranslations>;
export declare const useTranslations: () => StreamdownTranslations;
