// Generated by scripts/generate-tsrx-types.mjs.
import type { Ref } from 'react';
import type { ElementDescriptor } from 'octane';
import type { Octane } from 'octane/jsx-runtime';
import type { WithBoundingRectsProps } from '@octanejs/visx/bounds';
import type { TooltipProps } from './Tooltip.tsrx';
export type TooltipWithBoundsProps = TooltipProps & Omit<Octane.HTMLAttributes<HTMLDivElement>, keyof TooltipProps> & WithBoundingRectsProps & {
    nodeRef?: Ref<HTMLDivElement>;
};
declare const TooltipWithBoundsComponent: (props: TooltipWithBoundsProps) => ElementDescriptor;
export default TooltipWithBoundsComponent;
