// Generated by scripts/generate-tsrx-types.mjs.
import type { HTMLAttributes, Ref } from 'react';
import type { WithBoundingRectsProps } from '@octanejs/visx/bounds';
import type { TooltipProps } from './Tooltip.tsrx';
export type TooltipWithBoundsProps = TooltipProps & HTMLAttributes<HTMLDivElement> & WithBoundingRectsProps & {
    nodeRef?: Ref<HTMLDivElement>;
};
declare const _default: any;
export default _default;
