// GENERATED-SHAPED consumer type probe — see scripts/typecheck.mjs.
//
// Proves the PUBLISHED subpath surface carries real types. The package
// tsconfig excludes tests/ and src/ never imports its own subpaths, so
// without this file a broken `exports` map, a missing type, or an ambient
// `declare module '*.tsrx'` collapsing everything to `any` would all
// typecheck clean. Each probe fails on an unresolved module (TS2307) AND on
// a resolved-but-`any` binding.

// `0 extends 1 & T` is only true when T is `any` — the standard any-detector.
type IsAny<T> = 0 extends 1 & T ? true : false;
type NotAny<T> = IsAny<T> extends true ? { ERROR: 'resolved to any' } : true;
type Assert<T extends true> = T;

import { Accordion as X0 } from '@octanejs/shadcn/Accordion';
type _0 = Assert<NotAny<typeof X0>>;
import { AlertDialog as X1 } from '@octanejs/shadcn/AlertDialog';
type _1 = Assert<NotAny<typeof X1>>;
import { alertVariants as X2 } from '@octanejs/shadcn/Alert';
type _2 = Assert<NotAny<typeof X2>>;
import { AspectRatio as X3 } from '@octanejs/shadcn/AspectRatio';
type _3 = Assert<NotAny<typeof X3>>;
import { Avatar as X4 } from '@octanejs/shadcn/Avatar';
type _4 = Assert<NotAny<typeof X4>>;
import { badgeVariants as X5 } from '@octanejs/shadcn/Badge';
type _5 = Assert<NotAny<typeof X5>>;
import { Breadcrumb as X6 } from '@octanejs/shadcn/Breadcrumb';
type _6 = Assert<NotAny<typeof X6>>;
import { buttonVariants as X7 } from '@octanejs/shadcn/Button';
type _7 = Assert<NotAny<typeof X7>>;
import { Card as X8 } from '@octanejs/shadcn/Card';
type _8 = Assert<NotAny<typeof X8>>;
import { Checkbox as X9 } from '@octanejs/shadcn/Checkbox';
type _9 = Assert<NotAny<typeof X9>>;
import { Collapsible as X10 } from '@octanejs/shadcn/Collapsible';
type _10 = Assert<NotAny<typeof X10>>;
import { ContextMenu as X11 } from '@octanejs/shadcn/ContextMenu';
type _11 = Assert<NotAny<typeof X11>>;
import { Dialog as X12 } from '@octanejs/shadcn/Dialog';
type _12 = Assert<NotAny<typeof X12>>;
import { DropdownMenu as X13 } from '@octanejs/shadcn/DropdownMenu';
type _13 = Assert<NotAny<typeof X13>>;
import { Empty as X14 } from '@octanejs/shadcn/Empty';
type _14 = Assert<NotAny<typeof X14>>;
import { FieldSet as X15 } from '@octanejs/shadcn/Field';
type _15 = Assert<NotAny<typeof X15>>;
import { HoverCard as X16 } from '@octanejs/shadcn/HoverCard';
type _16 = Assert<NotAny<typeof X16>>;
import { Input as X17 } from '@octanejs/shadcn/Input';
type _17 = Assert<NotAny<typeof X17>>;
import { ItemGroup as X18 } from '@octanejs/shadcn/Item';
type _18 = Assert<NotAny<typeof X18>>;
import { Kbd as X19 } from '@octanejs/shadcn/Kbd';
type _19 = Assert<NotAny<typeof X19>>;
import { Label as X20 } from '@octanejs/shadcn/Label';
type _20 = Assert<NotAny<typeof X20>>;
import { Menubar as X21 } from '@octanejs/shadcn/Menubar';
type _21 = Assert<NotAny<typeof X21>>;
import { NativeSelect as X22 } from '@octanejs/shadcn/NativeSelect';
type _22 = Assert<NotAny<typeof X22>>;
import { NavigationMenu as X23 } from '@octanejs/shadcn/NavigationMenu';
type _23 = Assert<NotAny<typeof X23>>;
import { Pagination as X24 } from '@octanejs/shadcn/Pagination';
type _24 = Assert<NotAny<typeof X24>>;
import { Popover as X25 } from '@octanejs/shadcn/Popover';
type _25 = Assert<NotAny<typeof X25>>;
import { Progress as X26 } from '@octanejs/shadcn/Progress';
type _26 = Assert<NotAny<typeof X26>>;
import { RadioGroup as X27 } from '@octanejs/shadcn/RadioGroup';
type _27 = Assert<NotAny<typeof X27>>;
import { ScrollArea as X28 } from '@octanejs/shadcn/ScrollArea';
type _28 = Assert<NotAny<typeof X28>>;
import { Select as X29 } from '@octanejs/shadcn/Select';
type _29 = Assert<NotAny<typeof X29>>;
import { Separator as X30 } from '@octanejs/shadcn/Separator';
type _30 = Assert<NotAny<typeof X30>>;
import { Sheet as X31 } from '@octanejs/shadcn/Sheet';
type _31 = Assert<NotAny<typeof X31>>;
import { useSidebar as X32 } from '@octanejs/shadcn/Sidebar';
type _32 = Assert<NotAny<typeof X32>>;
import { Skeleton as X33 } from '@octanejs/shadcn/Skeleton';
type _33 = Assert<NotAny<typeof X33>>;
import { Slider as X34 } from '@octanejs/shadcn/Slider';
type _34 = Assert<NotAny<typeof X34>>;
import { Toaster as X35 } from '@octanejs/shadcn/Sonner';
type _35 = Assert<NotAny<typeof X35>>;
import { Spinner as X36 } from '@octanejs/shadcn/Spinner';
type _36 = Assert<NotAny<typeof X36>>;
import { Switch as X37 } from '@octanejs/shadcn/Switch';
type _37 = Assert<NotAny<typeof X37>>;
import { Table as X38 } from '@octanejs/shadcn/Table';
type _38 = Assert<NotAny<typeof X38>>;
import { Tabs as X39 } from '@octanejs/shadcn/Tabs';
type _39 = Assert<NotAny<typeof X39>>;
import { Textarea as X40 } from '@octanejs/shadcn/Textarea';
type _40 = Assert<NotAny<typeof X40>>;
import { ToggleGroup as X41 } from '@octanejs/shadcn/ToggleGroup';
type _41 = Assert<NotAny<typeof X41>>;
import { toggleVariants as X42 } from '@octanejs/shadcn/Toggle';
type _42 = Assert<NotAny<typeof X42>>;
import { TooltipProvider as X43 } from '@octanejs/shadcn/Tooltip';
type _43 = Assert<NotAny<typeof X43>>;
import { Accordion as X44 } from '@octanejs/shadcn/react-aria/Accordion';
type _44 = Assert<NotAny<typeof X44>>;
import { AlertDialogTrigger as X45 } from '@octanejs/shadcn/react-aria/AlertDialog';
type _45 = Assert<NotAny<typeof X45>>;
import { Alert as X46 } from '@octanejs/shadcn/react-aria/Alert';
type _46 = Assert<NotAny<typeof X46>>;
import { AspectRatio as X47 } from '@octanejs/shadcn/react-aria/AspectRatio';
type _47 = Assert<NotAny<typeof X47>>;
import { Avatar as X48 } from '@octanejs/shadcn/react-aria/Avatar';
type _48 = Assert<NotAny<typeof X48>>;
import { badgeVariants as X49 } from '@octanejs/shadcn/react-aria/Badge';
type _49 = Assert<NotAny<typeof X49>>;
import { Breadcrumb as X50 } from '@octanejs/shadcn/react-aria/Breadcrumb';
type _50 = Assert<NotAny<typeof X50>>;
import { buttonVariants as X51 } from '@octanejs/shadcn/react-aria/Button';
type _51 = Assert<NotAny<typeof X51>>;
import { Card as X52 } from '@octanejs/shadcn/react-aria/Card';
type _52 = Assert<NotAny<typeof X52>>;
import { Checkbox as X53 } from '@octanejs/shadcn/react-aria/Checkbox';
type _53 = Assert<NotAny<typeof X53>>;
import { Collapsible as X54 } from '@octanejs/shadcn/react-aria/Collapsible';
type _54 = Assert<NotAny<typeof X54>>;
import { DialogTrigger as X55 } from '@octanejs/shadcn/react-aria/Dialog';
type _55 = Assert<NotAny<typeof X55>>;
import { Empty as X56 } from '@octanejs/shadcn/react-aria/Empty';
type _56 = Assert<NotAny<typeof X56>>;
import { FieldSet as X57 } from '@octanejs/shadcn/react-aria/Field';
type _57 = Assert<NotAny<typeof X57>>;
import { Input as X58 } from '@octanejs/shadcn/react-aria/Input';
type _58 = Assert<NotAny<typeof X58>>;
import { ItemGroup as X59 } from '@octanejs/shadcn/react-aria/Item';
type _59 = Assert<NotAny<typeof X59>>;
import { Kbd as X60 } from '@octanejs/shadcn/react-aria/Kbd';
type _60 = Assert<NotAny<typeof X60>>;
import { Label as X61 } from '@octanejs/shadcn/react-aria/Label';
type _61 = Assert<NotAny<typeof X61>>;
import { NativeSelect as X62 } from '@octanejs/shadcn/react-aria/NativeSelect';
type _62 = Assert<NotAny<typeof X62>>;
import { Pagination as X63 } from '@octanejs/shadcn/react-aria/Pagination';
type _63 = Assert<NotAny<typeof X63>>;
import { PopoverTrigger as X64 } from '@octanejs/shadcn/react-aria/Popover';
type _64 = Assert<NotAny<typeof X64>>;
import { RadioGroup as X65 } from '@octanejs/shadcn/react-aria/RadioGroup';
type _65 = Assert<NotAny<typeof X65>>;
import { ScrollArea as X66 } from '@octanejs/shadcn/react-aria/ScrollArea';
type _66 = Assert<NotAny<typeof X66>>;
import { Separator as X67 } from '@octanejs/shadcn/react-aria/Separator';
type _67 = Assert<NotAny<typeof X67>>;
import { SheetTrigger as X68 } from '@octanejs/shadcn/react-aria/Sheet';
type _68 = Assert<NotAny<typeof X68>>;
import { Skeleton as X69 } from '@octanejs/shadcn/react-aria/Skeleton';
type _69 = Assert<NotAny<typeof X69>>;
import { Slider as X70 } from '@octanejs/shadcn/react-aria/Slider';
type _70 = Assert<NotAny<typeof X70>>;
import { Spinner as X71 } from '@octanejs/shadcn/react-aria/Spinner';
type _71 = Assert<NotAny<typeof X71>>;
import { Switch as X72 } from '@octanejs/shadcn/react-aria/Switch';
type _72 = Assert<NotAny<typeof X72>>;
import { Table as X73 } from '@octanejs/shadcn/react-aria/Table';
type _73 = Assert<NotAny<typeof X73>>;
import { Tabs as X74 } from '@octanejs/shadcn/react-aria/Tabs';
type _74 = Assert<NotAny<typeof X74>>;
import { Textarea as X75 } from '@octanejs/shadcn/react-aria/Textarea';
type _75 = Assert<NotAny<typeof X75>>;
import { toggleVariants as X76 } from '@octanejs/shadcn/react-aria/Toggle';
type _76 = Assert<NotAny<typeof X76>>;
import { cn as X77 } from '@octanejs/shadcn/cn';
type _77 = Assert<NotAny<typeof X77>>;
import { useIsMobile as X78 } from '@octanejs/shadcn/hooks/use-mobile';
type _78 = Assert<NotAny<typeof X78>>;
