// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
import type { LineProps } from '@octanejs/visx/shape';
import type { ScaleInput } from '@octanejs/visx/scale';
import type { CommonGridProps, GridScale } from '../types';
export type GridAngleProps<Scale extends GridScale> = CommonGridProps & {
    /** `@octanejs/visx/scale` or `d3-scale` object used to convert value to angle. */
    scale: Scale;
    /**
* Exact values used to generate angle grid lines using `scale`.
* Overrides `numTicks` if specified.
*/
    tickValues?: ScaleInput<Scale>[];
    /**
* Radius which determines the start position of angle lines.
*/
    innerRadius?: number;
    /**
* Radius which determines the end position of angle lines.
*/
    outerRadius: number;
    /**
* The class name applied to all angle lines.
*/
    lineClassName?: string;
};
export type AllGridAngleProps<Scale extends GridScale> = GridAngleProps<Scale> & Omit<LineProps & Omit<Octane.SVGProps<SVGLineElement>, keyof LineProps | 'children'>, keyof GridAngleProps<Scale>>;
export default function GridAngle<Scale extends GridScale>({ className, innerRadius, left, lineClassName, lineStyle, numTicks, outerRadius, scale, stroke, strokeDasharray, strokeWidth, tickValues, top, children, // Explicitly extract children so it doesn't get spread to Line
...restProps }: AllGridAngleProps<Scale>): import("react").JSX.Element;
