// Generated by scripts/generate-tsrx-types.mjs.
import type { TextProps, WordsWithWidth } from '../types';
export default function useText(props: TextProps): {
    wordsByLines: WordsWithWidth[];
    startDy: string;
    transform: string;
};
