// Generated by scripts/generate-tsrx-types.mjs.
import type { Ref } from 'react';
import type { Octane } from 'octane/jsx-runtime';
import type { OctaneNode } from 'octane';
export type GroupProps = {
    /** Top offset applied to `<g/>`. */
    top?: number;
    /** Left offset applied to `<g/>`. */
    left?: number;
    /** Override `top` and `left` to provide the entire `transform` string. */
    transform?: string;
    /** className to apply to `<g/>`. */
    className?: string;
    children?: OctaneNode;
    /** ref to underlying `<g/>`. */
    innerRef?: Ref<SVGGElement>;
};
export default function Group({ top, left, transform, className, children, innerRef, ...restProps }: GroupProps & Omit<Octane.SVGProps<SVGGElement>, keyof GroupProps>): import("react").JSX.Element;
