// Generated by scripts/generate-tsrx-types.mjs.
import type { ScaleInput } from '@octanejs/visx/scale';
import type { AxisRendererProps, AxisScale, CommonProps } from '../types';
import type { OrientationType } from '../constants/orientation';
export type UseAxisOptions<Scale extends AxisScale> = CommonProps<Scale> & {
    /** Placement of the axis. */
    orientation?: OrientationType;
    /** A d3 or visx scale function. */
    scale: Scale;
    /** Values that determine the number and value of ticks. */
    tickValues?: ScaleInput<Scale>[];
};
export default function useAxis<Scale extends AxisScale>({ hideAxisLine, hideTicks, hideZero, numTicks, orientation, rangePadding, scale, tickFormat, tickLength, tickValues, ...restProps }: UseAxisOptions<Scale>): AxisRendererProps<Scale>;
