// Generated by scripts/generate-tsrx-types.mjs.
import type { Ref } from 'react';
import type { OctaneNode } from 'octane';
import type { Line as LineType } from 'd3-shape';
import type { AddSVGProps, LinePathConfig } from '../types';
export type LinePathProps<Datum> = {
    /** Array of data for which to generate a line shape. */
    data?: Datum[];
    /** React RefObject passed to the path element. */
    innerRef?: Ref<SVGPathElement>;
    /** Override render function which is passed the configured path generator as input. */
    children?: (args: {
        path: LineType<Datum>;
    }) => OctaneNode;
    /** Fill color of the path element. */
    fill?: string;
    /** className applied to path element. */
    className?: string;
} & LinePathConfig<Datum>;
export default function LinePath<Datum>({ children, data, x, y, fill, className, curve, innerRef, defined, ...restProps }: AddSVGProps<LinePathProps<Datum>, SVGPathElement>): import("react").JSX.Element;
