// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { RadialLine } from 'd3-shape';
import type { LinePathProps } from './LinePath.tsrx';
import type { AddSVGProps, RadialLinePathConfig } from '../types';
export type LineRadialProps<Datum> = Pick<LinePathProps<Datum>, 'className' | 'data' | 'fill' | 'innerRef'> & {
    /** Override render function which is passed the configured path generator as input. */
    children?: (args: {
        path: RadialLine<Datum>;
    }) => OctaneNode;
} & RadialLinePathConfig<Datum>;
export default function LineRadial<Datum>({ className, angle, radius, defined, curve, data, innerRef, children, fill, ...restProps }: AddSVGProps<LineRadialProps<Datum>, SVGPathElement>): import("react").JSX.Element;
