// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
import type { OctaneNode } from 'octane';
import type { GetLineSegmentsConfig } from '../util/getSplitLineSegments';
import type { LinePathConfig } from '../types';
/**
 * Per-segment path styles. Octane's `className` composes clsx-style
 * (`ClassValue`), but segment styles are forwarded to `LinePath`'s plain
 * `className?: string` prop, so it stays a string here (matching upstream).
 */
type SplitLinePathSegmentStyles = Omit<Octane.SVGProps<SVGPathElement>, 'x' | 'y' | 'children' | 'className'> & {
    className?: string;
};
export type SplitLinePathRenderer = (renderProps: {
    index: number;
    segment: {
        x: number;
        y: number;
    }[];
    styles?: SplitLinePathSegmentStyles;
}) => OctaneNode;
export type SplitLinePathProps<Datum> = {
    /** Array of data segments, where each segment will be a separate path in the rendered line. */
    segments: Datum[][];
    /** Styles to apply to each segment. If fewer styles are specified than the number of segments, they will be re-used. */
    styles: SplitLinePathSegmentStyles[];
    /** Override render function which is passed the configured path generator as input. */
    children?: SplitLinePathRenderer;
    /** className applied to path element. */
    className?: string;
} & LinePathConfig<Datum> & Pick<GetLineSegmentsConfig, 'segmentation' | 'sampleRate'>;
export default function SplitLinePath<Datum>({ children, className, curve, defined, segmentation, sampleRate, segments, x, y, styles, }: SplitLinePathProps<Datum>): import("react").JSX.Element;
export {};
