// Generated by scripts/generate-tsrx-types.mjs.
import type { LinearGradientProps } from './LinearGradient.tsrx';
/**
 * All props pass through to `<LinearGradient {...props} />`
 */
export default function GradientDarkgreenGreen({ from, to, ...restProps }: LinearGradientProps): import("react").JSX.Element;
