// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
import type { LinearGradientProps } from './LinearGradient.tsrx';
export type RadialGradientProps = Pick<LinearGradientProps, 'id' | 'from' | 'to' | 'fromOffset' | 'fromOpacity' | 'toOffset' | 'toOpacity' | 'rotate' | 'transform' | 'children'> & Octane.SVGProps<SVGRadialGradientElement>;
export default function RadialGradient({ children, id, from, to, fromOffset, fromOpacity, toOffset, toOpacity, rotate, transform, ...restProps }: RadialGradientProps): import("react").JSX.Element;
