// Generated by scripts/generate-tsrx-types.mjs.
/**
 * Default debounce delay in milliseconds before checking if element is still in view
 */
export declare const DEFERRED_RENDER_DEBOUNCE_DELAY = 300;
/**
 * Default root margin for Intersection Observer
 * Starts rendering when element is 200px away from viewport
 */
export declare const DEFERRED_RENDER_ROOT_MARGIN = "300px";
/**
 * Default timeout for requestIdleCallback in milliseconds
 */
export declare const DEFERRED_RENDER_IDLE_TIMEOUT = 500;
export interface UseDeferredRenderOptions {
    /**
 * Debounce delay in milliseconds before checking if still in view
 * @default DEFERRED_RENDER_DEBOUNCE_DELAY
 */
    debounceDelay?: number;
    /**
 * Timeout for requestIdleCallback in milliseconds
 * @default DEFERRED_RENDER_IDLE_TIMEOUT
 */
    idleTimeout?: number;
    /**
 * If true, render immediately without waiting for intersection
 * @default false
 */
    immediate?: boolean;
    /**
 * Root margin for Intersection Observer (e.g., '200px' to start rendering 200px before entering viewport)
 * @default DEFERRED_RENDER_ROOT_MARGIN
 */
    rootMargin?: string;
}
/**
 * Hook for deferred rendering components when they enter the viewport.
 * Uses Intersection Observer + debounce + requestIdleCallback for optimal performance.
 *
 * @param options Configuration options
 * @returns Object containing `shouldRender` flag and `containerRef` to attach to the element
 *
 * @example
 * ```tsx
 * const { shouldRender, containerRef } = useDeferredRender({ immediate: false })
 *
 * return (
 *   <div ref={containerRef}>
 *     {shouldRender && <ExpensiveComponent />}
 *   </div>
 * )
 * ```
 */
export declare function useDeferredRender(options?: UseDeferredRenderOptions): {
    shouldRender: boolean;
    containerRef: {
        current: HTMLDivElement | null;
    };
};
