// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { UseDrag, UseDragOptions, HandlerArgs as HandlerArgsType } from './useDrag.tsrx';
export type HandlerArgs = HandlerArgsType;
export type DragProps = UseDragOptions & {
    /** Children render function which is passed the state of dragging and callbacks for drag start/end/move. */
    children: (args: UseDrag) => OctaneNode;
    /** Width of the drag container. */
    width: number;
    /** Height of the drag container. */
    height: number;
    /** Whether to render an invisible rect below children to capture the drag area as defined by width and height. */
    captureDragArea?: boolean;
    /** If defined, parent controls dragging state. */
    isDragging?: boolean;
};
export default function Drag({ captureDragArea, snapToPointer, children, dx, dy, height, onDragEnd, onDragMove, onDragStart, resetOnStart, width, x, y, isDragging, restrict, restrictToPath, }: DragProps): import("react").JSX.Element;
