import { readFileSync, renameSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const packageDirectory = join(dirname(fileURLToPath(import.meta.url)), '..');
const manifestFile = join(packageDirectory, 'package.json');
const sourceFile = join(packageDirectory, 'src', 'version.ts');
const { version } = JSON.parse(readFileSync(manifestFile, 'utf8'));

if (
	typeof version !== 'string' ||
	!/^\d+\.\d+\.\d+(?:-[\dA-Za-z.-]+)?(?:\+[\dA-Za-z.-]+)?$/.test(version)
) {
	throw new Error('octane: package.json contains an invalid package version');
}

const generated =
	'// This file is generated by packages/octane/scripts/generate-version.mjs.\n' +
	'// Run `pnpm sync` after changing the package version.\n' +
	`export const version: string = '${version}';\n`;
const current = readFileSync(sourceFile, 'utf8');

if (current !== generated) {
	if (process.argv.includes('--check')) {
		console.error('octane: generated version is stale; run `pnpm sync`');
		process.exitCode = 1;
	} else {
		const temporaryFile = `${sourceFile}.${process.pid}.tmp`;
		try {
			writeFileSync(temporaryFile, generated);
			renameSync(temporaryFile, sourceFile);
		} finally {
			rmSync(temporaryFile, { force: true });
		}
	}
}
