// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { DataContextType, DataRegistryEntry } from '../types';
/** Hook that returns an API equivalent to DataRegistry but which updates as needed for use as a hook. */
export default function useDataRegistry<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(initialEntries?: DataRegistryEntry<XScale, YScale, Datum>[]): DataContextType<XScale, YScale, Datum>['dataRegistry'];
