// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { StackPathConfig } from '@octanejs/visx/shape';
import type { AxisScale } from '@octanejs/visx/axis';
import type { CombinedStackData, SeriesProps } from '../types';
type UseStackedData<Datum extends object> = {
    children: OctaneNode;
} & Pick<StackPathConfig<Datum, string>, 'offset' | 'order'>;
export default function useStackedData<XScale extends AxisScale, YScale extends AxisScale, Datum extends object, ChildrenProps extends SeriesProps<XScale, YScale, Datum>>({ children, order, offset, }: UseStackedData<Datum>): {
    seriesChildren: import("react").ReactElement<ChildrenProps, string | import("react").JSXElementConstructor<any>>[];
    dataKeys: string[];
    stackedData: import("d3-shape").Series<CombinedStackData<XScale, YScale>, string>[];
};
export {};
