// Generated by scripts/generate-tsrx-types.mjs.
import type { FocusEvent, PointerEvent } from 'react';
import type { AxisScale } from '@octanejs/visx/axis';
import type { SeriesProps } from '../types';
import type { PointerEventHandlerParams } from './useEventHandlers.tsrx';
export type SeriesEventsParams<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = Pick<SeriesProps<XScale, YScale, Datum>, 'enableEvents' | 'onBlur' | 'onFocus' | 'onPointerMove' | 'onPointerOut' | 'onPointerUp' | 'onPointerDown'> & Pick<PointerEventHandlerParams<XScale, YScale, Datum>, 'dataKey' | 'allowedSources' | 'findNearestDatum'> & {
    /** The source of emitted events. */
    source: string;
};
/** This hook simplifies the logic for initializing Series event emitters + handlers. */
export default function useSeriesEvents<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ dataKey, enableEvents, findNearestDatum, onBlur: onBlurProps, onFocus: onFocusProps, onPointerMove: onPointerMoveProps, onPointerOut: onPointerOutProps, onPointerUp: onPointerUpProps, onPointerDown: onPointerDownProps, source, allowedSources, }: SeriesEventsParams<XScale, YScale, Datum>): {
    onPointerMove: ((event: PointerEvent) => void | undefined) | undefined;
    onFocus: ((event: FocusEvent) => void | undefined) | undefined;
    onBlur: ((event: FocusEvent) => void | undefined) | undefined;
    onPointerOut: ((event: PointerEvent) => void | undefined) | undefined;
    onPointerUp: ((event: PointerEvent) => void | undefined) | undefined;
    onPointerDown: ((event: PointerEvent) => void | undefined) | undefined;
};
