// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps, ReactNode } from 'react';
import type { TooltipProps as BaseTooltipProps, UseTooltipPortalOptions } from '@octanejs/visx/tooltip';
import type { PickD3Scale } from '@octanejs/visx/scale';
import type { GlyphProps as RenderGlyphProps, TooltipContextType } from '../types';
export type RenderTooltipParams<Datum extends object> = TooltipContextType<Datum> & {
    colorScale?: PickD3Scale<'ordinal', string, string>;
};
export interface RenderTooltipGlyphProps<Datum extends object> extends RenderGlyphProps<Datum> {
    glyphStyle?: SVGProps<SVGCircleElement>;
    isNearestDatum: boolean;
}
export type TooltipProps<Datum extends object> = {
    /**
* When TooltipContext.tooltipOpen=true, this function is invoked and if the
* return value is non-null, its content is rendered inside the tooltip container.
* Content will be rendered in an HTML parent.
*/
    /**
* When TooltipContext.tooltipOpen=true, this function is invoked and if the
* return value is non-null, its content is rendered inside the tooltip container.
* Content will be rendered in an HTML parent.
*/
    renderTooltip: (params: RenderTooltipParams<Datum>) => ReactNode;
    /** Function which handles rendering glyphs. */
    renderGlyph?: (params: RenderTooltipGlyphProps<Datum>) => ReactNode;
    /** Whether to snap tooltip + crosshair x-coord to the nearest Datum x-coord instead of the event x-coord. */
    snapTooltipToDatumX?: boolean;
    /** Whether to snap tooltip + crosshair y-coord to the nearest Datum y-coord instead of the event y-coord. */
    snapTooltipToDatumY?: boolean;
    /** Whether to show a vertical line at tooltip position. */
    showVerticalCrosshair?: boolean;
    /** Whether to show a horizontal line at tooltip position. */
    showHorizontalCrosshair?: boolean;
    /** Whether to show a glyph at the tooltip position for the (single) nearest Datum. */
    showDatumGlyph?: boolean;
    /** Whether to show a glyph for the nearest Datum in each series. */
    showSeriesGlyphs?: boolean;
    /** Optional styles for the vertical crosshair, if visible. */
    verticalCrosshairStyle?: SVGProps<SVGLineElement>;
    /** Optional styles for the vertical crosshair, if visible. */
    horizontalCrosshairStyle?: SVGProps<SVGLineElement>;
    /** Optional styles for the point, if visible. */
    glyphStyle?: SVGProps<SVGCircleElement>;
    /**
* Tooltip depends on ResizeObserver, which may be polyfilled globally,
* passed to XYChart, or injected into this component.
*/
    resizeObserverPolyfill?: UseTooltipPortalOptions['polyfill'];
} & Omit<BaseTooltipProps, 'left' | 'top' | 'children'> & Pick<UseTooltipPortalOptions, 'debounce' | 'detectBounds' | 'scroll' | 'zIndex'>;
/**
 * This is a wrapper component which bails early if tooltip is not visible.
 * If scroll detection is enabled in UseTooltipPortalOptions, this avoids re-rendering
 * the component on every scroll. If many charts with Tooltips are rendered on a page,
 * this also avoids creating many resize observers / hitting browser limits.
 */
export default function Tooltip<Datum extends object>(props: TooltipProps<Datum>): import("react").JSX.Element | null;
