// Independent projections of authenticated published and prior native declarations.
export interface ExpectedPublicContracts {
	// @octanejs/tanstack-router.reactUse
	0: never;
	// @octanejs/tanstack-router.useLayoutEffect
	1: 1 | 2 | 3;
	// @octanejs/tanstack-router.createHistory
	2: 1;
	// @octanejs/tanstack-router.createBrowserHistory
	3: 0 | 1;
	// @octanejs/tanstack-router.createHashHistory
	4: 0 | 1;
	// @octanejs/tanstack-router.createMemoryHistory
	5: 0 | 1;
	// @octanejs/tanstack-router.RouterHistory
	6:
		| 'length'
		| 'location'
		| 'subscribers'
		| 'subscribe'
		| 'push'
		| 'replace'
		| 'go'
		| 'back'
		| 'forward'
		| 'canGoBack'
		| 'createHref'
		| 'block'
		| 'flush'
		| 'destroy'
		| 'notify'
		| '_getBlockers'
		| '_ignoreSubscribers'
		| '_ignoreNextBeforeUnload';
	// @octanejs/tanstack-router.HistoryLocation
	7: 'state' | 'href' | 'pathname' | 'search' | 'hash';
	// @octanejs/tanstack-router.ParsedPath
	8: 'href' | 'pathname' | 'search' | 'hash';
	// @octanejs/tanstack-router.HistoryState
	9: '__tempLocation' | '__tempKey' | '__hashScrollIntoViewOptions';
	// @octanejs/tanstack-router.ParsedHistoryState
	10:
		| '__tempLocation'
		| '__tempKey'
		| '__hashScrollIntoViewOptions'
		| 'key'
		| '__TSR_key'
		| '__TSR_index';
	// @octanejs/tanstack-router.HistoryAction
	11: 'PUSH' | 'REPLACE' | 'FORWARD' | 'BACK' | 'GO';
	// @octanejs/tanstack-router.BlockerFnArgs
	12: 'currentLocation' | 'nextLocation' | 'action';
	// @octanejs/tanstack-router.BlockerFn
	13: never;
	// @octanejs/tanstack-router.NavigationBlocker
	14: 'blockerFn' | 'enableBeforeUnload';
	// @octanejs/tanstack-router.createRouter
	15: 1;
	// @octanejs/tanstack-router.Router
	16: 1;
	// @octanejs/tanstack-router.createRoute
	17: 1;
	// @octanejs/tanstack-router.createRootRoute
	18: 0 | 1;
	// @octanejs/tanstack-router.createRootRouteWithContext
	19: 0;
	// @octanejs/tanstack-router.rootRouteWithContext
	20: 0;
	// @octanejs/tanstack-router.createRouteMask
	21: 1;
	// @octanejs/tanstack-router.getRouteApi
	22: 1;
	// @octanejs/tanstack-router.Route
	23: never;
	// @octanejs/tanstack-router.RootRoute
	24: 0 | 1;
	// @octanejs/tanstack-router.RouteApi
	25: 1;
	// @octanejs/tanstack-router.NotFoundRoute
	26: 1;
	// @octanejs/tanstack-router.FileRoute
	27: 0 | 1 | 2;
	// @octanejs/tanstack-router.createFileRoute
	28: 0 | 1;
	// @octanejs/tanstack-router.FileRouteLoader
	29: 1;
	// @octanejs/tanstack-router.LazyRoute
	30: 1;
	// @octanejs/tanstack-router.createLazyRoute
	31: 1;
	// @octanejs/tanstack-router.createLazyFileRoute
	32: 1;
	// @octanejs/tanstack-router.DefaultRouteTypes
	33: 'component';
	// @octanejs/tanstack-router.SyncRouteComponent
	34: never;
	// @octanejs/tanstack-router.AsyncRouteComponent
	35: 'preload';
	// @octanejs/tanstack-router.RouteComponent
	36: 'preload';
	// @octanejs/tanstack-router.RouteTypes
	37: 'component';
	// @octanejs/tanstack-router.ErrorRouteComponent
	38: 'preload';
	// @octanejs/tanstack-router.NotFoundRouteComponent
	39: never;
	// @octanejs/tanstack-router.AnyRootRoute
	40:
		| 'types'
		| 'fullPath'
		| 'path'
		| 'id'
		| 'options'
		| 'to'
		| 'parentRoute'
		| 'useMatch'
		| 'useRouteContext'
		| 'useSearch'
		| 'useParams'
		| 'useLoaderDeps'
		| 'useLoaderData'
		| 'useNavigate'
		| 'Link'
		| 'isRoot'
		| 'children'
		| 'originalIndex'
		| 'rank'
		| 'lazyFn'
		| 'init'
		| 'addChildren'
		| '_addFileChildren'
		| '_addFileTypes'
		| 'updateLoader'
		| 'update'
		| 'lazy'
		| 'redirect';
	// @octanejs/tanstack-router.routerContext
	41: 2 | 3;
	// @octanejs/tanstack-router.getRouterContext
	42: 0;
	// @octanejs/tanstack-router.matchContext
	43: 2 | 3;
	// @octanejs/tanstack-router.useRouter
	44: 0 | 1;
	// @octanejs/tanstack-router.useStore
	45: 1 | 2 | 3 | 4;
	// @octanejs/tanstack-router.useRouterState
	46: 0 | 1;
	// @octanejs/tanstack-router.UseRouterStateOptions
	47: 'router' | 'select' | 'structuralSharing';
	// @octanejs/tanstack-router.UseRouterStateResult
	48: 'value';
	// @octanejs/tanstack-router.useMatch
	49: 1 | 2;
	// @octanejs/tanstack-router.useLocation
	50: 0 | 1 | 2;
	// @octanejs/tanstack-router.useParams
	51: 1 | 2;
	// @octanejs/tanstack-router.useSearch
	52: 1 | 2;
	// @octanejs/tanstack-router.useLoaderData
	53: 1 | 2;
	// @octanejs/tanstack-router.useLoaderDeps
	54: 1 | 2;
	// @octanejs/tanstack-router.useRouteContext
	55: 1 | 2;
	// @octanejs/tanstack-router.useMatches
	56: 0 | 1 | 2;
	// @octanejs/tanstack-router.useParentMatches
	57: 0 | 1 | 2;
	// @octanejs/tanstack-router.useChildMatches
	58: 0 | 1 | 2;
	// @octanejs/tanstack-router.useNavigate
	59: 0 | 1 | 2;
	// @octanejs/tanstack-router.useCanGoBack
	60: 0;
	// @octanejs/tanstack-router.UseLoaderDataBaseOptions
	61: 'select';
	// @octanejs/tanstack-router.UseLoaderDataOptions
	62: 'from' | 'select' | 'structuralSharing' | 'strict';
	// @octanejs/tanstack-router.UseLoaderDataRoute
	63: never;
	// @octanejs/tanstack-router.UseLoaderDepsBaseOptions
	64: 'select';
	// @octanejs/tanstack-router.UseLoaderDepsOptions
	65: 'from' | 'select' | 'structuralSharing' | 'strict';
	// @octanejs/tanstack-router.UseLoaderDepsRoute
	66: never;
	// @octanejs/tanstack-router.UseLocationBaseOptions
	67: 'select';
	// @octanejs/tanstack-router.UseLocationResult
	68: 'value';
	// @octanejs/tanstack-router.UseMatchBaseOptions
	69: 'select' | 'shouldThrow';
	// @octanejs/tanstack-router.UseMatchOptions
	70: 'from' | 'select' | 'structuralSharing' | 'strict' | 'shouldThrow';
	// @octanejs/tanstack-router.UseMatchResult
	71: 'value';
	// @octanejs/tanstack-router.UseMatchRoute
	72: never;
	// @octanejs/tanstack-router.UseMatchesBaseOptions
	73: 'select';
	// @octanejs/tanstack-router.UseMatchesResult
	74: 'value';
	// @octanejs/tanstack-router.UseParamsBaseOptions
	75: 'select' | 'shouldThrow';
	// @octanejs/tanstack-router.UseParamsOptions
	76: 'from' | 'select' | 'structuralSharing' | 'strict' | 'shouldThrow';
	// @octanejs/tanstack-router.UseParamsRoute
	77: never;
	// @octanejs/tanstack-router.UseRouteContextRoute
	78: never;
	// @octanejs/tanstack-router.UseSearchBaseOptions
	79: 'select' | 'shouldThrow';
	// @octanejs/tanstack-router.UseSearchOptions
	80: 'from' | 'select' | 'structuralSharing' | 'strict' | 'shouldThrow';
	// @octanejs/tanstack-router.UseSearchRoute
	81: never;
	// @octanejs/tanstack-router.useAwaited
	82: 1;
	// @octanejs/tanstack-router.AwaitOptions
	83: 'promise';
	// @octanejs/tanstack-router.useLinkProps
	84: 1;
	// @octanejs/tanstack-router.createLink
	85: 1;
	// @octanejs/tanstack-router.linkOptions
	86: 1;
	// @octanejs/tanstack-router.LinkOptionsFn
	87: never;
	// @octanejs/tanstack-router.LinkOptionsFnOptions
	88:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'key'
		| 'params'
		| 'preload'
		| 'onError'
		| 'id'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'style'
		| 'ref'
		| 'children'
		| 'slot'
		| 'title'
		| 'mask'
		| 'target'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps'
		| 'download'
		| 'hrefLang'
		| 'media'
		| 'ping'
		| 'type'
		| 'referrerPolicy'
		| 'defaultChecked'
		| 'defaultValue'
		| 'suppressContentEditableWarning'
		| 'suppressHydrationWarning'
		| 'accessKey'
		| 'autoCapitalize'
		| 'autoFocus'
		| 'className'
		| 'contentEditable'
		| 'contextMenu'
		| 'dir'
		| 'draggable'
		| 'enterKeyHint'
		| 'hidden'
		| 'lang'
		| 'nonce'
		| 'spellCheck'
		| 'tabIndex'
		| 'translate'
		| 'radioGroup'
		| 'role'
		| 'about'
		| 'content'
		| 'datatype'
		| 'inlist'
		| 'prefix'
		| 'property'
		| 'rel'
		| 'resource'
		| 'rev'
		| 'typeof'
		| 'vocab'
		| 'autoCorrect'
		| 'autoSave'
		| 'color'
		| 'itemProp'
		| 'itemScope'
		| 'itemType'
		| 'itemID'
		| 'itemRef'
		| 'results'
		| 'security'
		| 'unselectable'
		| 'inputMode'
		| 'is'
		| 'exportparts'
		| 'part'
		| 'aria-activedescendant'
		| 'aria-atomic'
		| 'aria-autocomplete'
		| 'aria-braillelabel'
		| 'aria-brailleroledescription'
		| 'aria-busy'
		| 'aria-checked'
		| 'aria-colcount'
		| 'aria-colindex'
		| 'aria-colindextext'
		| 'aria-colspan'
		| 'aria-controls'
		| 'aria-current'
		| 'aria-describedby'
		| 'aria-description'
		| 'aria-details'
		| 'aria-disabled'
		| 'aria-dropeffect'
		| 'aria-errormessage'
		| 'aria-expanded'
		| 'aria-flowto'
		| 'aria-grabbed'
		| 'aria-haspopup'
		| 'aria-hidden'
		| 'aria-invalid'
		| 'aria-keyshortcuts'
		| 'aria-label'
		| 'aria-labelledby'
		| 'aria-level'
		| 'aria-live'
		| 'aria-modal'
		| 'aria-multiline'
		| 'aria-multiselectable'
		| 'aria-orientation'
		| 'aria-owns'
		| 'aria-placeholder'
		| 'aria-posinset'
		| 'aria-pressed'
		| 'aria-readonly'
		| 'aria-relevant'
		| 'aria-required'
		| 'aria-roledescription'
		| 'aria-rowcount'
		| 'aria-rowindex'
		| 'aria-rowindextext'
		| 'aria-rowspan'
		| 'aria-selected'
		| 'aria-setsize'
		| 'aria-sort'
		| 'aria-valuemax'
		| 'aria-valuemin'
		| 'aria-valuenow'
		| 'aria-valuetext'
		| 'dangerouslySetInnerHTML'
		| 'onCopy'
		| 'onCopyCapture'
		| 'onCut'
		| 'onCutCapture'
		| 'onPaste'
		| 'onPasteCapture'
		| 'onCompositionEnd'
		| 'onCompositionEndCapture'
		| 'onCompositionStart'
		| 'onCompositionStartCapture'
		| 'onCompositionUpdate'
		| 'onCompositionUpdateCapture'
		| 'onFocus'
		| 'onFocusCapture'
		| 'onBlur'
		| 'onBlurCapture'
		| 'onChange'
		| 'onChangeCapture'
		| 'onBeforeInput'
		| 'onBeforeInputCapture'
		| 'onInput'
		| 'onInputCapture'
		| 'onReset'
		| 'onResetCapture'
		| 'onSubmit'
		| 'onSubmitCapture'
		| 'onInvalid'
		| 'onInvalidCapture'
		| 'onLoad'
		| 'onLoadCapture'
		| 'onErrorCapture'
		| 'onKeyDown'
		| 'onKeyDownCapture'
		| 'onKeyPress'
		| 'onKeyPressCapture'
		| 'onKeyUp'
		| 'onKeyUpCapture'
		| 'onAbort'
		| 'onAbortCapture'
		| 'onCanPlay'
		| 'onCanPlayCapture'
		| 'onCanPlayThrough'
		| 'onCanPlayThroughCapture'
		| 'onDurationChange'
		| 'onDurationChangeCapture'
		| 'onEmptied'
		| 'onEmptiedCapture'
		| 'onEncrypted'
		| 'onEncryptedCapture'
		| 'onEnded'
		| 'onEndedCapture'
		| 'onLoadedData'
		| 'onLoadedDataCapture'
		| 'onLoadedMetadata'
		| 'onLoadedMetadataCapture'
		| 'onLoadStart'
		| 'onLoadStartCapture'
		| 'onPause'
		| 'onPauseCapture'
		| 'onPlay'
		| 'onPlayCapture'
		| 'onPlaying'
		| 'onPlayingCapture'
		| 'onProgress'
		| 'onProgressCapture'
		| 'onRateChange'
		| 'onRateChangeCapture'
		| 'onSeeked'
		| 'onSeekedCapture'
		| 'onSeeking'
		| 'onSeekingCapture'
		| 'onStalled'
		| 'onStalledCapture'
		| 'onSuspend'
		| 'onSuspendCapture'
		| 'onTimeUpdate'
		| 'onTimeUpdateCapture'
		| 'onVolumeChange'
		| 'onVolumeChangeCapture'
		| 'onWaiting'
		| 'onWaitingCapture'
		| 'onAuxClick'
		| 'onAuxClickCapture'
		| 'onClick'
		| 'onClickCapture'
		| 'onContextMenu'
		| 'onContextMenuCapture'
		| 'onDoubleClick'
		| 'onDoubleClickCapture'
		| 'onDrag'
		| 'onDragCapture'
		| 'onDragEnd'
		| 'onDragEndCapture'
		| 'onDragEnter'
		| 'onDragEnterCapture'
		| 'onDragExit'
		| 'onDragExitCapture'
		| 'onDragLeave'
		| 'onDragLeaveCapture'
		| 'onDragOver'
		| 'onDragOverCapture'
		| 'onDragStart'
		| 'onDragStartCapture'
		| 'onDrop'
		| 'onDropCapture'
		| 'onMouseDown'
		| 'onMouseDownCapture'
		| 'onMouseEnter'
		| 'onMouseLeave'
		| 'onMouseMove'
		| 'onMouseMoveCapture'
		| 'onMouseOut'
		| 'onMouseOutCapture'
		| 'onMouseOver'
		| 'onMouseOverCapture'
		| 'onMouseUp'
		| 'onMouseUpCapture'
		| 'onSelect'
		| 'onSelectCapture'
		| 'onTouchCancel'
		| 'onTouchCancelCapture'
		| 'onTouchEnd'
		| 'onTouchEndCapture'
		| 'onTouchMove'
		| 'onTouchMoveCapture'
		| 'onTouchStart'
		| 'onTouchStartCapture'
		| 'onPointerDown'
		| 'onPointerDownCapture'
		| 'onPointerMove'
		| 'onPointerMoveCapture'
		| 'onPointerUp'
		| 'onPointerUpCapture'
		| 'onPointerCancel'
		| 'onPointerCancelCapture'
		| 'onPointerEnter'
		| 'onPointerLeave'
		| 'onPointerOver'
		| 'onPointerOverCapture'
		| 'onPointerOut'
		| 'onPointerOutCapture'
		| 'onGotPointerCapture'
		| 'onGotPointerCaptureCapture'
		| 'onLostPointerCapture'
		| 'onLostPointerCaptureCapture'
		| 'onScroll'
		| 'onScrollCapture'
		| 'onWheel'
		| 'onWheelCapture'
		| 'onAnimationStart'
		| 'onAnimationStartCapture'
		| 'onAnimationEnd'
		| 'onAnimationEndCapture'
		| 'onAnimationIteration'
		| 'onAnimationIterationCapture'
		| 'onTransitionEnd'
		| 'onTransitionEndCapture'
		| 'xmlns'
		| 'onToggle'
		| 'onCancel'
		| 'onClose'
		| 'radiogroup'
		| 'onScrollEnd'
		| 'onScrollEndCapture'
		| 'onBeforeToggle'
		| 'onTransitionCancel'
		| 'onTransitionCancelCapture'
		| 'onTransitionRun'
		| 'onTransitionRunCapture'
		| 'onTransitionStart'
		| 'onTransitionStartCapture'
		| 'onCancelCapture'
		| 'onCloseCapture'
		| 'popover'
		| 'popoverTargetAction'
		| 'popoverTarget'
		| 'inert'
		| 'class'
		| 'for'
		| 'hreflang'
		| 'referrerpolicy'
		| 'accesskey'
		| 'autocapitalize'
		| 'contenteditable'
		| 'contextmenu'
		| 'enterkeyhint'
		| 'spellcheck'
		| 'tabindex'
		| 'autocorrect'
		| 'autosave'
		| 'itemprop'
		| 'itemscope'
		| 'itemtype'
		| 'itemid'
		| 'itemref'
		| 'inputmode'
		| 'popovertargetaction'
		| 'popovertarget';
	// @octanejs/tanstack-router.ActiveLinkOptionProps
	89: 'activeProps' | 'inactiveProps';
	// @octanejs/tanstack-router.ActiveLinkOptions
	90:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| 'target'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps';
	// @octanejs/tanstack-router.CreateLinkProps
	91:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'children'
		| 'mask'
		| 'target'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps';
	// @octanejs/tanstack-router.LinkComponent
	92: never;
	// @octanejs/tanstack-router.LinkComponentProps
	93:
		| 'replace'
		| 'state'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps';
	// @octanejs/tanstack-router.LinkComponentRoute
	94: 'defaultFrom';
	// @octanejs/tanstack-router.LinkProps
	95:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'children'
		| 'mask'
		| 'target'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps';
	// @octanejs/tanstack-router.LinkPropsChildren
	96: 'children';
	// @octanejs/tanstack-router.OctaneAnchorProps
	97:
		| 'href'
		| 'key'
		| 'onError'
		| 'id'
		| 'style'
		| 'ref'
		| 'children'
		| 'slot'
		| 'title'
		| 'target'
		| 'download'
		| 'hrefLang'
		| 'media'
		| 'ping'
		| 'type'
		| 'referrerPolicy'
		| 'defaultChecked'
		| 'defaultValue'
		| 'suppressContentEditableWarning'
		| 'suppressHydrationWarning'
		| 'accessKey'
		| 'autoCapitalize'
		| 'autoFocus'
		| 'className'
		| 'contentEditable'
		| 'contextMenu'
		| 'dir'
		| 'draggable'
		| 'enterKeyHint'
		| 'hidden'
		| 'lang'
		| 'nonce'
		| 'spellCheck'
		| 'tabIndex'
		| 'translate'
		| 'radioGroup'
		| 'role'
		| 'about'
		| 'content'
		| 'datatype'
		| 'inlist'
		| 'prefix'
		| 'property'
		| 'rel'
		| 'resource'
		| 'rev'
		| 'typeof'
		| 'vocab'
		| 'autoCorrect'
		| 'autoSave'
		| 'color'
		| 'itemProp'
		| 'itemScope'
		| 'itemType'
		| 'itemID'
		| 'itemRef'
		| 'results'
		| 'security'
		| 'unselectable'
		| 'inputMode'
		| 'is'
		| 'exportparts'
		| 'part'
		| 'aria-activedescendant'
		| 'aria-atomic'
		| 'aria-autocomplete'
		| 'aria-braillelabel'
		| 'aria-brailleroledescription'
		| 'aria-busy'
		| 'aria-checked'
		| 'aria-colcount'
		| 'aria-colindex'
		| 'aria-colindextext'
		| 'aria-colspan'
		| 'aria-controls'
		| 'aria-current'
		| 'aria-describedby'
		| 'aria-description'
		| 'aria-details'
		| 'aria-disabled'
		| 'aria-dropeffect'
		| 'aria-errormessage'
		| 'aria-expanded'
		| 'aria-flowto'
		| 'aria-grabbed'
		| 'aria-haspopup'
		| 'aria-hidden'
		| 'aria-invalid'
		| 'aria-keyshortcuts'
		| 'aria-label'
		| 'aria-labelledby'
		| 'aria-level'
		| 'aria-live'
		| 'aria-modal'
		| 'aria-multiline'
		| 'aria-multiselectable'
		| 'aria-orientation'
		| 'aria-owns'
		| 'aria-placeholder'
		| 'aria-posinset'
		| 'aria-pressed'
		| 'aria-readonly'
		| 'aria-relevant'
		| 'aria-required'
		| 'aria-roledescription'
		| 'aria-rowcount'
		| 'aria-rowindex'
		| 'aria-rowindextext'
		| 'aria-rowspan'
		| 'aria-selected'
		| 'aria-setsize'
		| 'aria-sort'
		| 'aria-valuemax'
		| 'aria-valuemin'
		| 'aria-valuenow'
		| 'aria-valuetext'
		| 'dangerouslySetInnerHTML'
		| 'onCopy'
		| 'onCopyCapture'
		| 'onCut'
		| 'onCutCapture'
		| 'onPaste'
		| 'onPasteCapture'
		| 'onCompositionEnd'
		| 'onCompositionEndCapture'
		| 'onCompositionStart'
		| 'onCompositionStartCapture'
		| 'onCompositionUpdate'
		| 'onCompositionUpdateCapture'
		| 'onFocus'
		| 'onFocusCapture'
		| 'onBlur'
		| 'onBlurCapture'
		| 'onChange'
		| 'onChangeCapture'
		| 'onBeforeInput'
		| 'onBeforeInputCapture'
		| 'onInput'
		| 'onInputCapture'
		| 'onReset'
		| 'onResetCapture'
		| 'onSubmit'
		| 'onSubmitCapture'
		| 'onInvalid'
		| 'onInvalidCapture'
		| 'onLoad'
		| 'onLoadCapture'
		| 'onErrorCapture'
		| 'onKeyDown'
		| 'onKeyDownCapture'
		| 'onKeyPress'
		| 'onKeyPressCapture'
		| 'onKeyUp'
		| 'onKeyUpCapture'
		| 'onAbort'
		| 'onAbortCapture'
		| 'onCanPlay'
		| 'onCanPlayCapture'
		| 'onCanPlayThrough'
		| 'onCanPlayThroughCapture'
		| 'onDurationChange'
		| 'onDurationChangeCapture'
		| 'onEmptied'
		| 'onEmptiedCapture'
		| 'onEncrypted'
		| 'onEncryptedCapture'
		| 'onEnded'
		| 'onEndedCapture'
		| 'onLoadedData'
		| 'onLoadedDataCapture'
		| 'onLoadedMetadata'
		| 'onLoadedMetadataCapture'
		| 'onLoadStart'
		| 'onLoadStartCapture'
		| 'onPause'
		| 'onPauseCapture'
		| 'onPlay'
		| 'onPlayCapture'
		| 'onPlaying'
		| 'onPlayingCapture'
		| 'onProgress'
		| 'onProgressCapture'
		| 'onRateChange'
		| 'onRateChangeCapture'
		| 'onSeeked'
		| 'onSeekedCapture'
		| 'onSeeking'
		| 'onSeekingCapture'
		| 'onStalled'
		| 'onStalledCapture'
		| 'onSuspend'
		| 'onSuspendCapture'
		| 'onTimeUpdate'
		| 'onTimeUpdateCapture'
		| 'onVolumeChange'
		| 'onVolumeChangeCapture'
		| 'onWaiting'
		| 'onWaitingCapture'
		| 'onAuxClick'
		| 'onAuxClickCapture'
		| 'onClick'
		| 'onClickCapture'
		| 'onContextMenu'
		| 'onContextMenuCapture'
		| 'onDoubleClick'
		| 'onDoubleClickCapture'
		| 'onDrag'
		| 'onDragCapture'
		| 'onDragEnd'
		| 'onDragEndCapture'
		| 'onDragEnter'
		| 'onDragEnterCapture'
		| 'onDragExit'
		| 'onDragExitCapture'
		| 'onDragLeave'
		| 'onDragLeaveCapture'
		| 'onDragOver'
		| 'onDragOverCapture'
		| 'onDragStart'
		| 'onDragStartCapture'
		| 'onDrop'
		| 'onDropCapture'
		| 'onMouseDown'
		| 'onMouseDownCapture'
		| 'onMouseEnter'
		| 'onMouseLeave'
		| 'onMouseMove'
		| 'onMouseMoveCapture'
		| 'onMouseOut'
		| 'onMouseOutCapture'
		| 'onMouseOver'
		| 'onMouseOverCapture'
		| 'onMouseUp'
		| 'onMouseUpCapture'
		| 'onSelect'
		| 'onSelectCapture'
		| 'onTouchCancel'
		| 'onTouchCancelCapture'
		| 'onTouchEnd'
		| 'onTouchEndCapture'
		| 'onTouchMove'
		| 'onTouchMoveCapture'
		| 'onTouchStart'
		| 'onTouchStartCapture'
		| 'onPointerDown'
		| 'onPointerDownCapture'
		| 'onPointerMove'
		| 'onPointerMoveCapture'
		| 'onPointerUp'
		| 'onPointerUpCapture'
		| 'onPointerCancel'
		| 'onPointerCancelCapture'
		| 'onPointerEnter'
		| 'onPointerLeave'
		| 'onPointerOver'
		| 'onPointerOverCapture'
		| 'onPointerOut'
		| 'onPointerOutCapture'
		| 'onGotPointerCapture'
		| 'onGotPointerCaptureCapture'
		| 'onLostPointerCapture'
		| 'onLostPointerCaptureCapture'
		| 'onScroll'
		| 'onScrollCapture'
		| 'onWheel'
		| 'onWheelCapture'
		| 'onAnimationStart'
		| 'onAnimationStartCapture'
		| 'onAnimationEnd'
		| 'onAnimationEndCapture'
		| 'onAnimationIteration'
		| 'onAnimationIterationCapture'
		| 'onTransitionEnd'
		| 'onTransitionEndCapture'
		| 'xmlns'
		| 'onToggle'
		| 'onCancel'
		| 'onClose'
		| 'radiogroup'
		| 'onScrollEnd'
		| 'onScrollEndCapture'
		| 'onBeforeToggle'
		| 'onTransitionCancel'
		| 'onTransitionCancelCapture'
		| 'onTransitionRun'
		| 'onTransitionRunCapture'
		| 'onTransitionStart'
		| 'onTransitionStartCapture'
		| 'onCancelCapture'
		| 'onCloseCapture'
		| 'popover'
		| 'popoverTargetAction'
		| 'popoverTarget'
		| 'inert'
		| 'class'
		| 'for'
		| 'hreflang'
		| 'referrerpolicy'
		| 'accesskey'
		| 'autocapitalize'
		| 'contenteditable'
		| 'contextmenu'
		| 'enterkeyhint'
		| 'spellcheck'
		| 'tabindex'
		| 'autocorrect'
		| 'autosave'
		| 'itemprop'
		| 'itemscope'
		| 'itemtype'
		| 'itemid'
		| 'itemref'
		| 'inputmode'
		| 'popovertargetaction'
		| 'popovertarget';
	// @octanejs/tanstack-router.OctaneRenderable
	98: never;
	// @octanejs/tanstack-router.UseLinkPropsOptions
	99:
		| 'replace'
		| 'state'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps';
	// @octanejs/tanstack-router.useBlocker
	100: 0 | 1 | 2;
	// @octanejs/tanstack-router.Block
	101: 1;
	// @octanejs/tanstack-router.BlockerResolver
	102: 'action' | 'status' | 'reset' | 'next' | 'current' | 'proceed';
	// @octanejs/tanstack-router.ShouldBlockFn
	103: never;
	// @octanejs/tanstack-router.ShouldBlockFnArgs
	104: 'action' | 'next' | 'current';
	// @octanejs/tanstack-router.UseBlockerOpts
	105: 'enableBeforeUnload' | 'disabled' | 'shouldBlockFn' | 'withResolver';
	// @octanejs/tanstack-router.useMatchRoute
	106: 0;
	// @octanejs/tanstack-router.MatchRoute
	107: 1;
	// @octanejs/tanstack-router.UseMatchRouteOptions
	108:
		| 'state'
		| 'search'
		| 'hash'
		| 'caseSensitive'
		| 'fuzzy'
		| 'params'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| 'pending'
		| 'includeSearch';
	// @octanejs/tanstack-router.MakeMatchRouteOptions
	109:
		| 'state'
		| 'search'
		| 'hash'
		| 'caseSensitive'
		| 'fuzzy'
		| 'params'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'children'
		| 'mask'
		| '_fromLocation'
		| 'pending'
		| 'includeSearch';
	// @octanejs/tanstack-router.useElementScrollRestoration
	110: 1;
	// @octanejs/tanstack-router.lazyRouteComponent
	111: 1 | 2;
	// @octanejs/tanstack-router.RouterProvider
	112: 1;
	// @octanejs/tanstack-router.RouterContextProvider
	113: 1;
	// @octanejs/tanstack-router.RouterProps
	114:
		| 'search'
		| 'context'
		| 'serializationAdapters'
		| 'defaultSsr'
		| 'history'
		| 'stringifySearch'
		| 'parseSearch'
		| 'defaultPreload'
		| 'defaultPreloadDelay'
		| 'defaultPreloadIntentProximity'
		| 'defaultPendingMs'
		| 'defaultPendingMinMs'
		| 'defaultStaleTime'
		| 'defaultStaleReloadMode'
		| 'defaultPreloadStaleTime'
		| 'defaultPreloadGcTime'
		| 'defaultViewTransition'
		| 'defaultHashScrollIntoView'
		| 'notFoundMode'
		| 'defaultGcTime'
		| 'caseSensitive'
		| 'routeTree'
		| 'basepath'
		| 'additionalContext'
		| 'dehydrate'
		| 'hydrate'
		| 'routeMasks'
		| 'unmaskOnReload'
		| 'notFoundRoute'
		| 'trailingSlash'
		| 'isServer'
		| 'isShell'
		| 'isPrerendering'
		| 'defaultStructuralSharing'
		| 'pathParamsAllowedCharacters'
		| 'defaultRemountDeps'
		| 'scrollRestoration'
		| 'getScrollRestorationKey'
		| 'scrollRestorationBehavior'
		| 'scrollToTopSelectors'
		| 'disableGlobalCatchBoundary'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'defaultComponent'
		| 'defaultErrorComponent'
		| 'defaultPendingComponent'
		| 'defaultNotFoundComponent'
		| 'Wrap'
		| 'InnerWrap'
		| 'defaultOnCatch'
		| 'router';
	// @octanejs/tanstack-router.Outlet
	115: 0;
	// @octanejs/tanstack-router.Link
	116: 1;
	// @octanejs/tanstack-router.Navigate
	117: 1;
	// @octanejs/tanstack-router.Await
	118: 1;
	// @octanejs/tanstack-router.ScrollRestoration
	119: 0;
	// @octanejs/tanstack-router.Matches
	120: 0;
	// @octanejs/tanstack-router.Match
	121: 1;
	// @octanejs/tanstack-router.CatchBoundary
	122: 'onCatch' | 'errorComponent' | 'children' | 'getResetKey';
	// @octanejs/tanstack-router.ErrorComponent
	123: 1;
	// @octanejs/tanstack-router.CatchNotFound
	124: 1;
	// @octanejs/tanstack-router.DefaultGlobalNotFound
	125: 0;
	// @octanejs/tanstack-router.ClientOnly
	126: 1;
	// @octanejs/tanstack-router.useHydrated
	127: 0 | 1;
	// @octanejs/tanstack-router.HeadContent
	128: 1;
	// @octanejs/tanstack-router.HeadContentProps
	129: 'assetCrossOrigin';
	// @octanejs/tanstack-router.Scripts
	130: 0;
	// @octanejs/tanstack-router.ScriptOnce
	131: 1;
	// @octanejs/tanstack-router.Asset
	132: 1;
	// @octanejs/tanstack-router.AssetProps
	133: 'children' | 'target' | 'tag' | 'attrs' | 'assetKey' | 'nonce' | 'preventScriptHoist';
	// @octanejs/tanstack-router.useTags
	134: 0 | 1;
	// @octanejs/tanstack-router.Html
	135: 3;
	// @octanejs/tanstack-router.HtmlProps
	136: string | number;
	// @octanejs/tanstack-router.Head
	137: 3;
	// @octanejs/tanstack-router.HeadProps
	138: string | number;
	// @octanejs/tanstack-router.Body
	139: 3;
	// @octanejs/tanstack-router.BodyProps
	140: string | number;
	// @octanejs/tanstack-router.OctaneElementAttributes
	141: string;
	// @octanejs/tanstack-router.OctaneScriptAttributes
	142: string;
	// @octanejs/tanstack-router.InferStructuralSharing
	143: never;
	// @octanejs/tanstack-router.ValidateLinkOptions
	144:
		| 'replace'
		| 'state'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity'
		| 'activeProps'
		| 'inactiveProps';
	// @octanejs/tanstack-router.ValidateLinkOptionsArray
	145:
		| number
		| typeof Symbol.iterator
		| typeof Symbol.unscopables
		| 'length'
		| 'toString'
		| 'toLocaleString'
		| 'concat'
		| 'join'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'every'
		| 'some'
		| 'forEach'
		| 'map'
		| 'filter'
		| 'reduce'
		| 'reduceRight'
		| 'find'
		| 'findIndex'
		| 'entries'
		| 'keys'
		| 'values'
		| 'includes'
		| 'flatMap'
		| 'flat'
		| 'at'
		| 'findLast'
		| 'findLastIndex'
		| 'toReversed'
		| 'toSorted'
		| 'toSpliced'
		| 'with';
	// @octanejs/tanstack-router.ValidateUseParamsOptions
	146: 'from' | 'select' | 'structuralSharing' | 'strict' | 'shouldThrow';
	// @octanejs/tanstack-router.ValidateUseSearchOptions
	147: 'from' | 'select' | 'structuralSharing' | 'strict' | 'shouldThrow';
	// @octanejs/tanstack-router.TSR_DEFERRED_PROMISE
	148:
		'toString' | typeof Symbol.toStringTag | typeof Symbol.toPrimitive | 'description' | 'valueOf';
	// @octanejs/tanstack-router.defer
	149: 1 | 2;
	// @octanejs/tanstack-router.DeferredPromiseState
	150: 'data' | 'status';
	// @octanejs/tanstack-router.DeferredPromise
	151:
		| typeof Symbol.toStringTag
		| typeof import('@tanstack/router-core').TSR_DEFERRED_PROMISE
		| 'then'
		| 'catch'
		| 'finally';
	// @octanejs/tanstack-router.invariant
	152: 0;
	// @octanejs/tanstack-router.preloadWarning
	153:
		| number
		| typeof Symbol.iterator
		| 'length'
		| 'replace'
		| 'search'
		| 'toString'
		| 'concat'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'includes'
		| 'at'
		| 'charAt'
		| 'charCodeAt'
		| 'localeCompare'
		| 'match'
		| 'split'
		| 'substring'
		| 'toLowerCase'
		| 'toLocaleLowerCase'
		| 'toUpperCase'
		| 'toLocaleUpperCase'
		| 'trim'
		| 'substr'
		| 'codePointAt'
		| 'endsWith'
		| 'normalize'
		| 'repeat'
		| 'startsWith'
		| 'anchor'
		| 'big'
		| 'blink'
		| 'bold'
		| 'fixed'
		| 'fontcolor'
		| 'fontsize'
		| 'italics'
		| 'link'
		| 'small'
		| 'strike'
		| 'sub'
		| 'sup'
		| 'padStart'
		| 'padEnd'
		| 'trimEnd'
		| 'trimStart'
		| 'trimLeft'
		| 'trimRight'
		| 'matchAll'
		| 'replaceAll'
		| 'isWellFormed'
		| 'toWellFormed'
		| 'valueOf';
	// @octanejs/tanstack-router.IsRequiredParams
	154: true;
	// @octanejs/tanstack-router.AddTrailingSlash
	155: `${{ value: string } & string}/`;
	// @octanejs/tanstack-router.RemoveTrailingSlashes
	156: 'value';
	// @octanejs/tanstack-router.AddLeadingSlash
	157: 'value';
	// @octanejs/tanstack-router.RemoveLeadingSlashes
	158: 'value';
	// @octanejs/tanstack-router.ActiveOptions
	159: 'includeSearch' | 'exact' | 'includeHash' | 'explicitUndefined';
	// @octanejs/tanstack-router.LinkOptionsProps
	160:
		'preload' | 'target' | 'activeOptions' | 'preloadDelay' | 'disabled' | 'preloadIntentProximity';
	// @octanejs/tanstack-router.ResolveCurrentPath
	161: never;
	// @octanejs/tanstack-router.ResolveParentPath
	162: '/example/example';
	// @octanejs/tanstack-router.ResolveRelativePath
	163: '/example';
	// @octanejs/tanstack-router.FindDescendantToPaths
	164: string | number | symbol;
	// @octanejs/tanstack-router.InferDescendantToPaths
	165: string;
	// @octanejs/tanstack-router.RelativeToPath
	166: '/example' | `/example/${string}`;
	// @octanejs/tanstack-router.RelativeToParentPath
	167: '/example' | `/example/${string}`;
	// @octanejs/tanstack-router.RelativeToCurrentPath
	168: '.' | '/example' | `/example/${string}`;
	// @octanejs/tanstack-router.AbsoluteToPath
	169: string | number | symbol;
	// @octanejs/tanstack-router.RelativeToPathAutoComplete
	170: string | number | symbol;
	// @octanejs/tanstack-router.NavigateOptions
	171:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument';
	// @octanejs/tanstack-router.ToOptions
	172:
		| 'state'
		| 'search'
		| 'hash'
		| 'params'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation';
	// @octanejs/tanstack-router.ToMaskOptions
	173: 'state' | 'search' | 'hash' | 'unmaskOnReload' | 'params' | 'to' | 'from' | 'unsafeRelative';
	// @octanejs/tanstack-router.ToSubOptions
	174: 'state' | 'search' | 'hash' | 'params' | 'to' | 'from' | 'unsafeRelative';
	// @octanejs/tanstack-router.ResolveRoute
	175: string | number | symbol;
	// @octanejs/tanstack-router.SearchParamOptions
	176: 'search';
	// @octanejs/tanstack-router.PathParamOptions
	177: 'params';
	// @octanejs/tanstack-router.ToPathOption
	178: string;
	// @octanejs/tanstack-router.LinkOptions
	179:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'preload'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| 'target'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'activeOptions'
		| 'preloadDelay'
		| 'disabled'
		| 'preloadIntentProximity';
	// @octanejs/tanstack-router.MakeOptionalPathParams
	180: 'params';
	// @octanejs/tanstack-router.FromPathOption
	181: string;
	// @octanejs/tanstack-router.MakeOptionalSearchParams
	182: 'search';
	// @octanejs/tanstack-router.MaskOptions
	183: 'mask' | '_fromLocation';
	// @octanejs/tanstack-router.ToSubOptionsProps
	184: 'state' | 'hash' | 'to' | 'from' | 'unsafeRelative';
	// @octanejs/tanstack-router.RequiredToOptions
	185: 'to';
	// @octanejs/tanstack-router.RouteToPath
	186: string | number | symbol;
	// @octanejs/tanstack-router.TrailingSlashOptionByRouter
	187: 'never';
	// @octanejs/tanstack-router.ParseRoute
	188:
		| 'types'
		| 'fullPath'
		| 'path'
		| 'id'
		| 'options'
		| 'to'
		| 'parentRoute'
		| 'useMatch'
		| 'useRouteContext'
		| 'useSearch'
		| 'useParams'
		| 'useLoaderDeps'
		| 'useLoaderData'
		| 'useNavigate'
		| 'Link'
		| 'isRoot'
		| 'children'
		| 'originalIndex'
		| 'rank'
		| 'lazyFn'
		| 'init'
		| 'addChildren'
		| '_addFileChildren'
		| '_addFileTypes'
		| 'updateLoader'
		| 'update'
		| 'lazy'
		| 'redirect';
	// @octanejs/tanstack-router.CodeRouteToPath
	189: string | number | symbol;
	// @octanejs/tanstack-router.RouteIds
	190: '__root__';
	// @octanejs/tanstack-router.FullSearchSchema
	191: never;
	// @octanejs/tanstack-router.FullSearchSchemaInput
	192: never;
	// @octanejs/tanstack-router.AllParams
	193: never;
	// @octanejs/tanstack-router.RouteById
	194: never;
	// @octanejs/tanstack-router.AllContext
	195: never;
	// @octanejs/tanstack-router.RoutePaths
	196: '/';
	// @octanejs/tanstack-router.RoutesById
	197: '__root__';
	// @octanejs/tanstack-router.RoutesByPath
	198: '/';
	// @octanejs/tanstack-router.AllLoaderData
	199: undefined;
	// @octanejs/tanstack-router.RouteByPath
	200: never;
	// @octanejs/tanstack-router.InferFileRouteTypes
	201: never;
	// @octanejs/tanstack-router.FileRouteTypes
	202: 'fullPaths' | 'id' | 'to' | 'fileRoutesByFullPath' | 'fileRoutesById' | 'fileRoutesByTo';
	// @octanejs/tanstack-router.FileRoutesByPath
	203: never;
	// @octanejs/tanstack-router.CreateFileRoute
	204: never;
	// @octanejs/tanstack-router.LazyRouteOptions
	205: 'component' | 'errorComponent' | 'notFoundComponent' | 'pendingComponent';
	// @octanejs/tanstack-router.CreateLazyFileRoute
	206: never;
	// @octanejs/tanstack-router.ParsedLocation
	207:
		| 'state'
		| 'href'
		| 'pathname'
		| 'search'
		| 'hash'
		| 'unmaskOnReload'
		| 'searchStr'
		| 'maskedLocation'
		| 'publicHref'
		| 'external';
	// @octanejs/tanstack-router.Manifest
	208: 'scriptFormat' | 'inlineStyle' | 'routes';
	// @octanejs/tanstack-router.ServerManifest
	209: 'inlineCss' | 'scriptFormat' | 'routes';
	// @octanejs/tanstack-router.ManifestRoute
	210: 'scripts' | 'filePath' | 'preloads' | 'css';
	// @octanejs/tanstack-router.ManifestRouteAssets
	211: 'scripts' | 'preloads' | 'css';
	// @octanejs/tanstack-router.ServerManifestRoute
	212: 'scripts' | 'filePath' | 'preloads' | 'css';
	// @octanejs/tanstack-router.ManifestCssLink
	213: never;
	// @octanejs/tanstack-router.ManifestInlineCss
	214: 'children' | 'attrs';
	// @octanejs/tanstack-router.ServerManifestInlineCss
	215: 'styles' | 'templates';
	// @octanejs/tanstack-router.InlineCssTemplate
	216: 'strings' | 'urls';
	// @octanejs/tanstack-router.ManifestScript
	217: 'children' | 'attrs';
	// @octanejs/tanstack-router.RouterManagedTag
	218: 'children' | 'tag' | 'attrs';
	// @octanejs/tanstack-router.RouterManagedTitleTag
	219: 'children' | 'tag' | 'attrs';
	// @octanejs/tanstack-router.RouterManagedMetaTag
	220: 'children' | 'tag' | 'attrs';
	// @octanejs/tanstack-router.RouterManagedInlineCssTag
	221: 'children' | 'tag' | 'attrs' | 'inlineCss';
	// @octanejs/tanstack-router.RouterManagedScriptTag
	222: 'children' | 'tag' | 'attrs';
	// @octanejs/tanstack-router.RouterManagedLinkTag
	223: 'children' | 'tag' | 'attrs';
	// @octanejs/tanstack-router.RouterManagedStyleTag
	224: 'children' | 'tag' | 'attrs' | 'inlineCss';
	// @octanejs/tanstack-router.AssetCrossOrigin
	225: 'anonymous' | 'use-credentials';
	// @octanejs/tanstack-router.AssetCrossOriginConfig
	226: never;
	// @octanejs/tanstack-router.ManifestAssetLink
	227: never;
	// @octanejs/tanstack-router.ScriptFormat
	228: 'module' | 'iife';
	// @octanejs/tanstack-router.DEV_STYLES_ATTR
	229:
		| number
		| typeof Symbol.iterator
		| 'length'
		| 'replace'
		| 'search'
		| 'toString'
		| 'concat'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'includes'
		| 'at'
		| 'charAt'
		| 'charCodeAt'
		| 'localeCompare'
		| 'match'
		| 'split'
		| 'substring'
		| 'toLowerCase'
		| 'toLocaleLowerCase'
		| 'toUpperCase'
		| 'toLocaleUpperCase'
		| 'trim'
		| 'substr'
		| 'codePointAt'
		| 'endsWith'
		| 'normalize'
		| 'repeat'
		| 'startsWith'
		| 'anchor'
		| 'big'
		| 'blink'
		| 'bold'
		| 'fixed'
		| 'fontcolor'
		| 'fontsize'
		| 'italics'
		| 'link'
		| 'small'
		| 'strike'
		| 'sub'
		| 'sup'
		| 'padStart'
		| 'padEnd'
		| 'trimEnd'
		| 'trimStart'
		| 'trimLeft'
		| 'trimRight'
		| 'matchAll'
		| 'replaceAll'
		| 'isWellFormed'
		| 'toWellFormed'
		| 'valueOf';
	// @octanejs/tanstack-router.appendUniqueUserTags
	230: 2;
	// @octanejs/tanstack-router.createInlineCssStyleAsset
	231: 1;
	// @octanejs/tanstack-router.getAssetCrossOrigin
	232: 2;
	// @octanejs/tanstack-router.getManifestScriptFormat
	233: 1;
	// @octanejs/tanstack-router.getScriptPreloadAttrs
	234: 2 | 3;
	// @octanejs/tanstack-router.getStylesheetHref
	235: 1;
	// @octanejs/tanstack-router.resolveManifestAssetLink
	236: 1;
	// @octanejs/tanstack-router.resolveManifestCssLink
	237: 1;
	// @octanejs/tanstack-router.isMatch
	238: 2;
	// @octanejs/tanstack-router._getAssetMatches
	239: 1;
	// @octanejs/tanstack-router._getRenderedMatches
	240: 1;
	// @octanejs/tanstack-router.AnyMatchAndValue
	241: 'match' | 'value';
	// @octanejs/tanstack-router.FindValueByIndex
	242: never;
	// @octanejs/tanstack-router.FindValueByKey
	243: never;
	// @octanejs/tanstack-router.CreateMatchAndValue
	244: 'match' | 'value';
	// @octanejs/tanstack-router.NextMatchAndValue
	245: 'match' | 'value';
	// @octanejs/tanstack-router.IsMatchKeyOf
	246: 'value';
	// @octanejs/tanstack-router.IsMatchPath
	247: '/examplevalue';
	// @octanejs/tanstack-router.IsMatchResult
	248: never;
	// @octanejs/tanstack-router.IsMatchParse
	249: 'path' | 'result';
	// @octanejs/tanstack-router.IsMatch
	250: 'path' | 'result';
	// @octanejs/tanstack-router.RouteMatch
	251:
		| 'pathname'
		| 'search'
		| 'context'
		| 'ssr'
		| 'fullPath'
		| 'error'
		| 'params'
		| 'preload'
		| 'headers'
		| 'scripts'
		| 'staticData'
		| 'loaderDeps'
		| 'id'
		| 'links'
		| 'headScripts'
		| 'meta'
		| 'styles'
		| 'routeId'
		| 'loaderData'
		| 'status'
		| 'index'
		| '_strictParams'
		| 'isFetching'
		| 'paramsError'
		| 'searchError'
		| 'updatedAt'
		| '_strictSearch'
		| 'abortController'
		| 'cause'
		| 'invalid'
		| '_notFound'
		| '__beforeLoadContext';
	// @octanejs/tanstack-router.RouteMatchExtensions
	252: 'scripts' | 'links' | 'headScripts' | 'meta' | 'styles' | '__beforeLoadContext';
	// @octanejs/tanstack-router.MakeRouteMatchUnion
	253:
		| 'pathname'
		| 'search'
		| 'context'
		| 'ssr'
		| 'fullPath'
		| 'error'
		| 'params'
		| 'preload'
		| 'headers'
		| 'scripts'
		| 'staticData'
		| 'loaderDeps'
		| 'id'
		| 'links'
		| 'headScripts'
		| 'meta'
		| 'styles'
		| 'routeId'
		| 'loaderData'
		| 'status'
		| 'index'
		| '_strictParams'
		| 'isFetching'
		| 'paramsError'
		| 'searchError'
		| 'updatedAt'
		| '_strictSearch'
		| 'abortController'
		| 'cause'
		| 'invalid'
		| '_notFound'
		| '__beforeLoadContext';
	// @octanejs/tanstack-router.MakeRouteMatch
	254:
		| 'pathname'
		| 'search'
		| 'context'
		| 'ssr'
		| 'fullPath'
		| 'error'
		| 'params'
		| 'preload'
		| 'headers'
		| 'scripts'
		| 'staticData'
		| 'loaderDeps'
		| 'id'
		| 'links'
		| 'headScripts'
		| 'meta'
		| 'styles'
		| 'routeId'
		| 'loaderData'
		| 'status'
		| 'index'
		| '_strictParams'
		| 'isFetching'
		| 'paramsError'
		| 'searchError'
		| 'updatedAt'
		| '_strictSearch'
		| 'abortController'
		| 'cause'
		| 'invalid'
		| '_notFound'
		| '__beforeLoadContext';
	// @octanejs/tanstack-router.AnyRouteMatch
	255:
		| 'pathname'
		| 'search'
		| 'context'
		| 'ssr'
		| 'fullPath'
		| 'error'
		| 'params'
		| 'preload'
		| 'headers'
		| 'scripts'
		| 'staticData'
		| 'loaderDeps'
		| 'id'
		| 'links'
		| 'headScripts'
		| 'meta'
		| 'styles'
		| 'routeId'
		| 'loaderData'
		| 'status'
		| 'index'
		| '_strictParams'
		| 'isFetching'
		| 'paramsError'
		| 'searchError'
		| 'updatedAt'
		| '_strictSearch'
		| 'abortController'
		| 'cause'
		| 'invalid'
		| '_notFound'
		| '__beforeLoadContext';
	// @octanejs/tanstack-router.MakeRouteMatchFromRoute
	256:
		| 'pathname'
		| 'search'
		| 'context'
		| 'ssr'
		| 'fullPath'
		| 'error'
		| 'params'
		| 'preload'
		| 'headers'
		| 'scripts'
		| 'staticData'
		| 'loaderDeps'
		| 'id'
		| 'links'
		| 'headScripts'
		| 'meta'
		| 'styles'
		| 'routeId'
		| 'loaderData'
		| 'status'
		| 'index'
		| '_strictParams'
		| 'isFetching'
		| 'paramsError'
		| 'searchError'
		| 'updatedAt'
		| '_strictSearch'
		| 'abortController'
		| 'cause'
		| 'invalid'
		| '_notFound'
		| '__beforeLoadContext';
	// @octanejs/tanstack-router.MatchRouteOptions
	257: 'caseSensitive' | 'fuzzy' | 'pending' | 'includeSearch';
	// @octanejs/tanstack-router.joinPaths
	258: 1;
	// @octanejs/tanstack-router.cleanPath
	259: 1;
	// @octanejs/tanstack-router.trimPathLeft
	260: 1;
	// @octanejs/tanstack-router.trimPathRight
	261: 1;
	// @octanejs/tanstack-router.trimPath
	262: 1;
	// @octanejs/tanstack-router.removeTrailingSlash
	263: 2;
	// @octanejs/tanstack-router.exactPathTest
	264: 3;
	// @octanejs/tanstack-router.resolvePath
	265: 1;
	// @octanejs/tanstack-router.interpolatePath
	266: 1;
	// @octanejs/tanstack-router.encode
	267: 1 | 2;
	// @octanejs/tanstack-router.decode
	268: 1;
	// @octanejs/tanstack-router.rootRouteId
	269:
		| number
		| typeof Symbol.iterator
		| 'length'
		| 'replace'
		| 'search'
		| 'toString'
		| 'concat'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'includes'
		| 'at'
		| 'charAt'
		| 'charCodeAt'
		| 'localeCompare'
		| 'match'
		| 'split'
		| 'substring'
		| 'toLowerCase'
		| 'toLocaleLowerCase'
		| 'toUpperCase'
		| 'toLocaleUpperCase'
		| 'trim'
		| 'substr'
		| 'codePointAt'
		| 'endsWith'
		| 'normalize'
		| 'repeat'
		| 'startsWith'
		| 'anchor'
		| 'big'
		| 'blink'
		| 'bold'
		| 'fixed'
		| 'fontcolor'
		| 'fontsize'
		| 'italics'
		| 'link'
		| 'small'
		| 'strike'
		| 'sub'
		| 'sup'
		| 'padStart'
		| 'padEnd'
		| 'trimEnd'
		| 'trimStart'
		| 'trimLeft'
		| 'trimRight'
		| 'matchAll'
		| 'replaceAll'
		| 'isWellFormed'
		| 'toWellFormed'
		| 'valueOf';
	// @octanejs/tanstack-router.RootRouteId
	270: '__root__';
	// @octanejs/tanstack-router.BaseRoute
	271: never;
	// @octanejs/tanstack-router.BaseRouteApi
	272: 1;
	// @octanejs/tanstack-router.BaseRootRoute
	273: 0 | 1;
	// @octanejs/tanstack-router.AnyPathParams
	274: never;
	// @octanejs/tanstack-router.SearchSchemaInput
	275: '__TSearchSchemaInput__';
	// @octanejs/tanstack-router.AnyContext
	276: never;
	// @octanejs/tanstack-router.RouteContext
	277: never;
	// @octanejs/tanstack-router.PreloadableObj
	278: 'preload';
	// @octanejs/tanstack-router.RoutePathOptions
	279: never;
	// @octanejs/tanstack-router.StaticDataRouteOption
	280: never;
	// @octanejs/tanstack-router.RoutePathOptionsIntersection
	281: 'path' | 'id';
	// @octanejs/tanstack-router.SearchFilter
	282: never;
	// @octanejs/tanstack-router.SearchMiddlewareContext
	283: 'search' | 'meta' | 'next';
	// @octanejs/tanstack-router.SearchMiddleware
	284: never;
	// @octanejs/tanstack-router.ResolveId
	285: '/example';
	// @octanejs/tanstack-router.InferFullSearchSchema
	286: never;
	// @octanejs/tanstack-router.InferFullSearchSchemaInput
	287: never;
	// @octanejs/tanstack-router.InferAllParams
	288: never;
	// @octanejs/tanstack-router.InferAllContext
	289: never;
	// @octanejs/tanstack-router.MetaDescriptor
	290: never;
	// @octanejs/tanstack-router.RouteLinkEntry
	291: never;
	// @octanejs/tanstack-router.SearchValidator
	292: never;
	// @octanejs/tanstack-router.AnySearchValidator
	293: never;
	// @octanejs/tanstack-router.DefaultSearchValidator
	294: never;
	// @octanejs/tanstack-router.ErrorRouteProps
	295: 'error' | 'reset' | 'info';
	// @octanejs/tanstack-router.ErrorComponentProps
	296: 'error' | 'reset' | 'info';
	// @octanejs/tanstack-router.DefaultErrorBoundaryTypes
	297: 'error';
	// @octanejs/tanstack-router.ErrorBoundaryTypes
	298: 'error';
	// @octanejs/tanstack-router.NotFoundRouteProps
	299: 'data' | 'isNotFound' | 'routeId';
	// @octanejs/tanstack-router.ResolveParams
	300: never;
	// @octanejs/tanstack-router.ParseParamsFn
	301: never;
	// @octanejs/tanstack-router.StringifyParamsFn
	302: never;
	// @octanejs/tanstack-router.ParamsOptions
	303: 'params' | 'parseParams' | 'stringifyParams';
	// @octanejs/tanstack-router.UpdatableStaticRouteOption
	304: 'staticData';
	// @octanejs/tanstack-router.ContextReturnType
	305: never;
	// @octanejs/tanstack-router.ContextAsyncReturnType
	306: never;
	// @octanejs/tanstack-router.ResolveRouteContext
	307: never;
	// @octanejs/tanstack-router.ResolveLoaderData
	308: undefined;
	// @octanejs/tanstack-router.RoutePrefix
	309: '/example/example';
	// @octanejs/tanstack-router.TrimPath
	310: 'example';
	// @octanejs/tanstack-router.TrimPathLeft
	311: 'example';
	// @octanejs/tanstack-router.TrimPathRight
	312: '/example';
	// @octanejs/tanstack-router.ResolveSearchSchemaFnInput
	313: never;
	// @octanejs/tanstack-router.ResolveSearchSchemaInput
	314: never;
	// @octanejs/tanstack-router.ResolveSearchSchemaFn
	315: never;
	// @octanejs/tanstack-router.ResolveSearchSchema
	316: never;
	// @octanejs/tanstack-router.ResolveFullSearchSchema
	317: never;
	// @octanejs/tanstack-router.ResolveFullSearchSchemaInput
	318: never;
	// @octanejs/tanstack-router.ResolveAllContext
	319:
		| 'subscribers'
		| 'subscribe'
		| 'state'
		| 'history'
		| 'routeTree'
		| 'basepath'
		| 'isServer'
		| 'isShell'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'options'
		| 'update'
		| 'startTransition'
		| 'shouldViewTransition'
		| '_lifecycleEnd'
		| '_tx'
		| '_flights'
		| '_preloads'
		| '_preflight'
		| '_handoff'
		| '_pending'
		| '_serverResult'
		| '_rendered'
		| '_refreshRoute'
		| '_replaceRouteChunk'
		| 'tempLocationKey'
		| '_scroll'
		| '_cache'
		| '_committed'
		| 'stores'
		| 'batch'
		| 'latestLocation'
		| '_pendingLocation'
		| 'routesById'
		| 'routesByPath'
		| 'processedTree'
		| 'resolvePathCache'
		| 'pathParamsDecoder'
		| 'updateLatestLocation'
		| 'buildRouteTree'
		| 'setRoutes'
		| 'emit'
		| 'parseLocation'
		| 'resolvePathWithBase'
		| 'matchRoutes'
		| 'getMatchedRoutes'
		| 'buildLocation'
		| '_commitPromise'
		| 'commitLocation'
		| 'buildAndCommitLocation'
		| 'navigate'
		| 'load'
		| 'startViewTransition'
		| 'invalidate'
		| 'resolveRedirect'
		| 'clearCache'
		| 'loadRouteChunk'
		| 'preloadRoute'
		| 'matchRoute'
		| 'serverSsr'
		| 'serverSsrLifecycle';
	// @octanejs/tanstack-router.BeforeLoadContextParameter
	320:
		| 'subscribers'
		| 'subscribe'
		| 'state'
		| 'history'
		| 'routeTree'
		| 'basepath'
		| 'isServer'
		| 'isShell'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'options'
		| 'update'
		| 'startTransition'
		| 'shouldViewTransition'
		| '_lifecycleEnd'
		| '_tx'
		| '_flights'
		| '_preloads'
		| '_preflight'
		| '_handoff'
		| '_pending'
		| '_serverResult'
		| '_rendered'
		| '_refreshRoute'
		| '_replaceRouteChunk'
		| 'tempLocationKey'
		| '_scroll'
		| '_cache'
		| '_committed'
		| 'stores'
		| 'batch'
		| 'latestLocation'
		| '_pendingLocation'
		| 'routesById'
		| 'routesByPath'
		| 'processedTree'
		| 'resolvePathCache'
		| 'pathParamsDecoder'
		| 'updateLatestLocation'
		| 'buildRouteTree'
		| 'setRoutes'
		| 'emit'
		| 'parseLocation'
		| 'resolvePathWithBase'
		| 'matchRoutes'
		| 'getMatchedRoutes'
		| 'buildLocation'
		| '_commitPromise'
		| 'commitLocation'
		| 'buildAndCommitLocation'
		| 'navigate'
		| 'load'
		| 'startViewTransition'
		| 'invalidate'
		| 'resolveRedirect'
		| 'clearCache'
		| 'loadRouteChunk'
		| 'preloadRoute'
		| 'matchRoute'
		| 'serverSsr'
		| 'serverSsrLifecycle';
	// @octanejs/tanstack-router.RouteContextParameter
	321:
		| 'subscribers'
		| 'subscribe'
		| 'state'
		| 'history'
		| 'routeTree'
		| 'basepath'
		| 'isServer'
		| 'isShell'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'options'
		| 'update'
		| 'startTransition'
		| 'shouldViewTransition'
		| '_lifecycleEnd'
		| '_tx'
		| '_flights'
		| '_preloads'
		| '_preflight'
		| '_handoff'
		| '_pending'
		| '_serverResult'
		| '_rendered'
		| '_refreshRoute'
		| '_replaceRouteChunk'
		| 'tempLocationKey'
		| '_scroll'
		| '_cache'
		| '_committed'
		| 'stores'
		| 'batch'
		| 'latestLocation'
		| '_pendingLocation'
		| 'routesById'
		| 'routesByPath'
		| 'processedTree'
		| 'resolvePathCache'
		| 'pathParamsDecoder'
		| 'updateLatestLocation'
		| 'buildRouteTree'
		| 'setRoutes'
		| 'emit'
		| 'parseLocation'
		| 'resolvePathWithBase'
		| 'matchRoutes'
		| 'getMatchedRoutes'
		| 'buildLocation'
		| '_commitPromise'
		| 'commitLocation'
		| 'buildAndCommitLocation'
		| 'navigate'
		| 'load'
		| 'startViewTransition'
		| 'invalidate'
		| 'resolveRedirect'
		| 'clearCache'
		| 'loadRouteChunk'
		| 'preloadRoute'
		| 'matchRoute'
		| 'serverSsr'
		| 'serverSsrLifecycle';
	// @octanejs/tanstack-router.ResolveAllParamsFromParent
	322: 'value';
	// @octanejs/tanstack-router.AnyRoute
	323:
		| 'types'
		| 'fullPath'
		| 'path'
		| 'id'
		| 'options'
		| 'to'
		| 'parentRoute'
		| 'useMatch'
		| 'useRouteContext'
		| 'useSearch'
		| 'useParams'
		| 'useLoaderDeps'
		| 'useLoaderData'
		| 'useNavigate'
		| 'Link'
		| 'isRoot'
		| 'children'
		| 'rank'
		| 'lazyFn'
		| 'init'
		| 'addChildren'
		| '_addFileChildren'
		| '_addFileTypes'
		| 'update'
		| 'lazy'
		| 'redirect';
	// @octanejs/tanstack-router.FullSearchSchemaOption
	324: 'search';
	// @octanejs/tanstack-router.RemountDepsOptions
	325: 'search' | 'params' | 'loaderDeps' | 'routeId';
	// @octanejs/tanstack-router.MakeRemountDepsOptionsUnion
	326: 'search' | 'params' | 'loaderDeps' | 'routeId';
	// @octanejs/tanstack-router.ResolveFullPath
	327: '/example';
	// @octanejs/tanstack-router.AnyRouteWithContext
	328:
		| 'types'
		| 'fullPath'
		| 'path'
		| 'id'
		| 'options'
		| 'to'
		| 'parentRoute'
		| 'useMatch'
		| 'useRouteContext'
		| 'useSearch'
		| 'useParams'
		| 'useLoaderDeps'
		| 'useLoaderData'
		| 'useNavigate'
		| 'Link'
		| 'isRoot'
		| 'children'
		| 'rank'
		| 'lazyFn'
		| 'init'
		| 'addChildren'
		| '_addFileChildren'
		| '_addFileTypes'
		| 'update'
		| 'lazy'
		| 'redirect';
	// @octanejs/tanstack-router.RouteOptions
	329:
		| 'search'
		| 'context'
		| 'caseSensitive'
		| 'ssr'
		| 'component'
		| 'params'
		| 'parseParams'
		| 'stringifyParams'
		| 'getParentRoute'
		| 'wrapInSuspense'
		| 'pendingMs'
		| 'pendingMinMs'
		| 'staleTime'
		| 'gcTime'
		| 'preload'
		| 'preloadStaleTime'
		| 'preloadGcTime'
		| 'preSearchFilters'
		| 'postSearchFilters'
		| 'onCatch'
		| 'onError'
		| 'onEnter'
		| 'onStay'
		| 'onLeave'
		| 'headers'
		| 'head'
		| 'scripts'
		| 'codeSplitGroupings'
		| 'staticData'
		| 'errorComponent'
		| 'notFoundComponent'
		| 'pendingComponent'
		| 'loader'
		| 'validateSearch'
		| 'shouldReload'
		| 'beforeLoad'
		| 'loaderDeps'
		| 'remountDeps';
	// @octanejs/tanstack-router.FileBaseRouteOptions
	330:
		| 'context'
		| 'ssr'
		| 'params'
		| 'parseParams'
		| 'stringifyParams'
		| 'loader'
		| 'validateSearch'
		| 'shouldReload'
		| 'beforeLoad'
		| 'loaderDeps'
		| 'remountDeps';
	// @octanejs/tanstack-router.BaseRouteOptions
	331:
		| 'context'
		| 'ssr'
		| 'params'
		| 'parseParams'
		| 'stringifyParams'
		| 'getParentRoute'
		| 'loader'
		| 'validateSearch'
		| 'shouldReload'
		| 'beforeLoad'
		| 'loaderDeps'
		| 'remountDeps';
	// @octanejs/tanstack-router.UpdatableRouteOptions
	332:
		| 'search'
		| 'caseSensitive'
		| 'component'
		| 'wrapInSuspense'
		| 'pendingMs'
		| 'pendingMinMs'
		| 'staleTime'
		| 'gcTime'
		| 'preload'
		| 'preloadStaleTime'
		| 'preloadGcTime'
		| 'preSearchFilters'
		| 'postSearchFilters'
		| 'onCatch'
		| 'onError'
		| 'onEnter'
		| 'onStay'
		| 'onLeave'
		| 'headers'
		| 'head'
		| 'scripts'
		| 'codeSplitGroupings'
		| 'staticData'
		| 'errorComponent'
		| 'notFoundComponent'
		| 'pendingComponent';
	// @octanejs/tanstack-router.LoaderStaleReloadMode
	333: 'background' | 'blocking';
	// @octanejs/tanstack-router.RouteLoaderFn
	334: never;
	// @octanejs/tanstack-router.RouteLoaderEntry
	335: never;
	// @octanejs/tanstack-router.LoaderFnContext
	336:
		| 'location'
		| 'context'
		| 'params'
		| 'preload'
		| 'abortController'
		| 'cause'
		| 'navigate'
		| 'deps'
		| 'parentMatchPromise'
		| 'route';
	// @octanejs/tanstack-router.RouteContextFn
	337: never;
	// @octanejs/tanstack-router.ContextOptions
	338:
		| 'location'
		| 'params'
		| 'preload'
		| 'routeId'
		| 'abortController'
		| 'cause'
		| 'buildLocation'
		| 'navigate'
		| 'matches';
	// @octanejs/tanstack-router.RouteContextOptions
	339:
		| 'location'
		| 'context'
		| 'params'
		| 'preload'
		| 'routeId'
		| 'abortController'
		| 'cause'
		| 'buildLocation'
		| 'navigate'
		| 'deps'
		| 'matches';
	// @octanejs/tanstack-router.SsrContextOptions
	340: 'location' | 'search' | 'params' | 'matches';
	// @octanejs/tanstack-router.BeforeLoadContextOptions
	341:
		| 'location'
		| 'search'
		| 'context'
		| 'params'
		| 'preload'
		| 'routeId'
		| 'abortController'
		| 'cause'
		| 'buildLocation'
		| 'navigate'
		| 'matches';
	// @octanejs/tanstack-router.RootRouteOptions
	342:
		| 'search'
		| 'context'
		| 'ssr'
		| 'component'
		| 'wrapInSuspense'
		| 'pendingMs'
		| 'pendingMinMs'
		| 'staleTime'
		| 'gcTime'
		| 'preload'
		| 'preloadStaleTime'
		| 'preloadGcTime'
		| 'preSearchFilters'
		| 'postSearchFilters'
		| 'onCatch'
		| 'onError'
		| 'onEnter'
		| 'onStay'
		| 'onLeave'
		| 'headers'
		| 'head'
		| 'scripts'
		| 'codeSplitGroupings'
		| 'staticData'
		| 'errorComponent'
		| 'notFoundComponent'
		| 'pendingComponent'
		| 'loader'
		| 'validateSearch'
		| 'shouldReload'
		| 'beforeLoad'
		| 'loaderDeps'
		| 'remountDeps'
		| 'shellComponent';
	// @octanejs/tanstack-router.RootRouteOptionsExtensions
	343: 'shellComponent';
	// @octanejs/tanstack-router.UpdatableRouteOptionsExtensions
	344: 'component' | 'errorComponent' | 'notFoundComponent' | 'pendingComponent';
	// @octanejs/tanstack-router.RouteConstraints
	345:
		| 'TParentRoute'
		| 'TPath'
		| 'TFullPath'
		| 'TCustomId'
		| 'TId'
		| 'TSearchSchema'
		| 'TFullSearchSchema'
		| 'TParams'
		| 'TAllParams'
		| 'TParentContext'
		| 'TRouteContext'
		| 'TAllContext'
		| 'TRouterContext'
		| 'TChildren'
		| 'TRouteTree';
	// @octanejs/tanstack-router.RouteTypesById
	346: string | number | symbol;
	// @octanejs/tanstack-router.RouteMask
	347: 'state' | 'search' | 'hash' | 'routeTree' | 'unmaskOnReload' | 'params' | 'to' | 'from';
	// @octanejs/tanstack-router.RouteExtensions
	348:
		| 'fullPath'
		| 'id'
		| 'useMatch'
		| 'useRouteContext'
		| 'useSearch'
		| 'useParams'
		| 'useLoaderDeps'
		| 'useLoaderData'
		| 'useNavigate'
		| 'Link';
	// @octanejs/tanstack-router.RouteLazyFn
	349: never;
	// @octanejs/tanstack-router.RouteAddChildrenFn
	350: never;
	// @octanejs/tanstack-router.RouteAddFileChildrenFn
	351: never;
	// @octanejs/tanstack-router.RouteAddFileTypesFn
	352: never;
	// @octanejs/tanstack-router.ResolveOptionalParams
	353: never;
	// @octanejs/tanstack-router.ResolveRequiredParams
	354: never;
	// @octanejs/tanstack-router.FilebaseRouteOptionsInterface
	355:
		| 'context'
		| 'ssr'
		| 'loader'
		| 'validateSearch'
		| 'shouldReload'
		| 'beforeLoad'
		| 'loaderDeps'
		| 'remountDeps';
	// @octanejs/tanstack-router.createNonReactiveMutableStore
	356: 1;
	// @octanejs/tanstack-router.createNonReactiveReadonlyStore
	357: 1;
	// @octanejs/tanstack-router.RouterBatchFn
	358: never;
	// @octanejs/tanstack-router.RouterReadableStore
	359: 'get';
	// @octanejs/tanstack-router.GetStoreConfig
	360: never;
	// @octanejs/tanstack-router.RouterStores
	361:
		| 'location'
		| 'status'
		| 'matches'
		| 'resolvedLocation'
		| 'ids'
		| '__store'
		| 'byRoute'
		| 'getMatchStore'
		| 'setMatches';
	// @octanejs/tanstack-router.RouterWritableStore
	362: 'set' | 'get';
	// @octanejs/tanstack-router.defaultSerializeError
	363: 1;
	// @octanejs/tanstack-router.getLocationChangeInfo
	364: 1 | 2;
	// @octanejs/tanstack-router.RouterCore
	365: 'prototype';
	// @octanejs/tanstack-router.lazyFn
	366: 1 | 2;
	// @octanejs/tanstack-router.SearchParamError
	367: 0 | 1 | 2;
	// @octanejs/tanstack-router.PathParamError
	368: 0 | 1 | 2;
	// @octanejs/tanstack-router.getInitialRouterState
	369: 1;
	// @octanejs/tanstack-router.trailingSlashOptions
	370: 'always' | 'never' | 'preserve';
	// @octanejs/tanstack-router.ViewTransitionOptions
	371: 'types';
	// @octanejs/tanstack-router.TrailingSlashOption
	372: 'always' | 'never' | 'preserve';
	// @octanejs/tanstack-router.Register
	373: never;
	// @octanejs/tanstack-router.AnyRouter
	374:
		| 'subscribers'
		| 'subscribe'
		| 'state'
		| 'history'
		| 'routeTree'
		| 'basepath'
		| 'isServer'
		| 'isShell'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'options'
		| 'update'
		| 'startTransition'
		| 'shouldViewTransition'
		| '_lifecycleEnd'
		| '_tx'
		| '_flights'
		| '_preloads'
		| '_preflight'
		| '_handoff'
		| '_pending'
		| '_serverResult'
		| '_rendered'
		| '_refreshRoute'
		| '_replaceRouteChunk'
		| 'tempLocationKey'
		| '_scroll'
		| '_cache'
		| '_committed'
		| 'stores'
		| 'batch'
		| 'latestLocation'
		| '_pendingLocation'
		| 'routesById'
		| 'routesByPath'
		| 'processedTree'
		| 'resolvePathCache'
		| 'pathParamsDecoder'
		| 'updateLatestLocation'
		| 'buildRouteTree'
		| 'setRoutes'
		| 'emit'
		| 'parseLocation'
		| 'resolvePathWithBase'
		| 'matchRoutes'
		| 'getMatchedRoutes'
		| 'buildLocation'
		| '_commitPromise'
		| 'commitLocation'
		| 'buildAndCommitLocation'
		| 'navigate'
		| 'load'
		| 'startViewTransition'
		| 'invalidate'
		| 'resolveRedirect'
		| 'clearCache'
		| 'loadRouteChunk'
		| 'preloadRoute'
		| 'matchRoute'
		| 'serverSsr'
		| 'serverSsrLifecycle';
	// @octanejs/tanstack-router.AnyRouterWithContext
	375:
		| 'subscribers'
		| 'subscribe'
		| 'state'
		| 'history'
		| 'routeTree'
		| 'basepath'
		| 'isServer'
		| 'isShell'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'options'
		| 'update'
		| 'startTransition'
		| 'shouldViewTransition'
		| '_lifecycleEnd'
		| '_tx'
		| '_flights'
		| '_preloads'
		| '_preflight'
		| '_handoff'
		| '_pending'
		| '_serverResult'
		| '_rendered'
		| '_refreshRoute'
		| '_replaceRouteChunk'
		| 'tempLocationKey'
		| '_scroll'
		| '_cache'
		| '_committed'
		| 'stores'
		| 'batch'
		| 'latestLocation'
		| '_pendingLocation'
		| 'routesById'
		| 'routesByPath'
		| 'processedTree'
		| 'resolvePathCache'
		| 'pathParamsDecoder'
		| 'updateLatestLocation'
		| 'buildRouteTree'
		| 'setRoutes'
		| 'emit'
		| 'parseLocation'
		| 'resolvePathWithBase'
		| 'matchRoutes'
		| 'getMatchedRoutes'
		| 'buildLocation'
		| '_commitPromise'
		| 'commitLocation'
		| 'buildAndCommitLocation'
		| 'navigate'
		| 'load'
		| 'startViewTransition'
		| 'invalidate'
		| 'resolveRedirect'
		| 'clearCache'
		| 'loadRouteChunk'
		| 'preloadRoute'
		| 'matchRoute'
		| 'serverSsr'
		| 'serverSsrLifecycle';
	// @octanejs/tanstack-router.RegisteredRouter
	376:
		| 'subscribers'
		| 'subscribe'
		| 'state'
		| 'history'
		| 'routeTree'
		| 'basepath'
		| 'isServer'
		| 'isShell'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'options'
		| 'update'
		| 'startTransition'
		| 'shouldViewTransition'
		| '_lifecycleEnd'
		| '_tx'
		| '_flights'
		| '_preloads'
		| '_preflight'
		| '_handoff'
		| '_pending'
		| '_serverResult'
		| '_rendered'
		| '_refreshRoute'
		| '_replaceRouteChunk'
		| 'tempLocationKey'
		| '_scroll'
		| '_cache'
		| '_committed'
		| 'stores'
		| 'batch'
		| 'latestLocation'
		| '_pendingLocation'
		| 'routesById'
		| 'routesByPath'
		| 'processedTree'
		| 'resolvePathCache'
		| 'pathParamsDecoder'
		| 'updateLatestLocation'
		| 'buildRouteTree'
		| 'setRoutes'
		| 'emit'
		| 'parseLocation'
		| 'resolvePathWithBase'
		| 'matchRoutes'
		| 'getMatchedRoutes'
		| 'buildLocation'
		| '_commitPromise'
		| 'commitLocation'
		| 'buildAndCommitLocation'
		| 'navigate'
		| 'load'
		| 'startViewTransition'
		| 'invalidate'
		| 'resolveRedirect'
		| 'clearCache'
		| 'loadRouteChunk'
		| 'preloadRoute'
		| 'matchRoute'
		| 'serverSsr'
		| 'serverSsrLifecycle';
	// @octanejs/tanstack-router.RouterState
	377: 'location' | 'status' | 'matches' | 'resolvedLocation' | 'isLoading';
	// @octanejs/tanstack-router.BuildNextOptions
	378:
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| '_isNavigate';
	// @octanejs/tanstack-router.RouterListener
	379: 'eventType' | 'fn';
	// @octanejs/tanstack-router.RouterEvent
	380: 'type' | 'fromLocation' | 'toLocation' | 'pathChanged' | 'hrefChanged' | 'hashChanged';
	// @octanejs/tanstack-router.ListenerFn
	381: never;
	// @octanejs/tanstack-router.RouterEvents
	382:
		| 'onLoad'
		| 'onBeforeNavigate'
		| 'onBeforeLoad'
		| 'onResolved'
		| 'onBeforeRouteMount'
		| 'onRendered';
	// @octanejs/tanstack-router.MatchRoutesOpts
	383: 'throwOnError';
	// @octanejs/tanstack-router.RouterOptionsExtensions
	384:
		| 'defaultComponent'
		| 'defaultErrorComponent'
		| 'defaultPendingComponent'
		| 'defaultNotFoundComponent'
		| 'Wrap'
		| 'InnerWrap'
		| 'defaultOnCatch';
	// @octanejs/tanstack-router.DefaultRemountDepsFn
	385: never;
	// @octanejs/tanstack-router.PreloadRouteFn
	386: never;
	// @octanejs/tanstack-router.MatchRouteFn
	387: never;
	// @octanejs/tanstack-router.RouterContextOptions
	388: 'context';
	// @octanejs/tanstack-router.RouterOptions
	389:
		| 'search'
		| 'context'
		| 'serializationAdapters'
		| 'defaultSsr'
		| 'history'
		| 'stringifySearch'
		| 'parseSearch'
		| 'defaultPreload'
		| 'defaultPreloadDelay'
		| 'defaultPreloadIntentProximity'
		| 'defaultPendingMs'
		| 'defaultPendingMinMs'
		| 'defaultStaleTime'
		| 'defaultStaleReloadMode'
		| 'defaultPreloadStaleTime'
		| 'defaultPreloadGcTime'
		| 'defaultViewTransition'
		| 'defaultHashScrollIntoView'
		| 'notFoundMode'
		| 'defaultGcTime'
		| 'caseSensitive'
		| 'routeTree'
		| 'basepath'
		| 'additionalContext'
		| 'dehydrate'
		| 'hydrate'
		| 'routeMasks'
		| 'unmaskOnReload'
		| 'notFoundRoute'
		| 'trailingSlash'
		| 'isServer'
		| 'isShell'
		| 'isPrerendering'
		| 'defaultStructuralSharing'
		| 'pathParamsAllowedCharacters'
		| 'defaultRemountDeps'
		| 'scrollRestoration'
		| 'getScrollRestorationKey'
		| 'scrollRestorationBehavior'
		| 'scrollToTopSelectors'
		| 'disableGlobalCatchBoundary'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'defaultComponent'
		| 'defaultErrorComponent'
		| 'defaultPendingComponent'
		| 'defaultNotFoundComponent'
		| 'Wrap'
		| 'InnerWrap'
		| 'defaultOnCatch';
	// @octanejs/tanstack-router.RouterConstructorOptions
	390:
		| 'search'
		| 'context'
		| 'history'
		| 'stringifySearch'
		| 'parseSearch'
		| 'defaultPreload'
		| 'defaultPreloadDelay'
		| 'defaultPreloadIntentProximity'
		| 'defaultPendingMs'
		| 'defaultPendingMinMs'
		| 'defaultStaleTime'
		| 'defaultStaleReloadMode'
		| 'defaultPreloadStaleTime'
		| 'defaultPreloadGcTime'
		| 'defaultViewTransition'
		| 'defaultHashScrollIntoView'
		| 'notFoundMode'
		| 'defaultGcTime'
		| 'caseSensitive'
		| 'routeTree'
		| 'basepath'
		| 'additionalContext'
		| 'dehydrate'
		| 'hydrate'
		| 'routeMasks'
		| 'unmaskOnReload'
		| 'notFoundRoute'
		| 'trailingSlash'
		| 'isServer'
		| 'isShell'
		| 'isPrerendering'
		| 'defaultStructuralSharing'
		| 'pathParamsAllowedCharacters'
		| 'defaultRemountDeps'
		| 'scrollRestoration'
		| 'getScrollRestorationKey'
		| 'scrollRestorationBehavior'
		| 'scrollToTopSelectors'
		| 'disableGlobalCatchBoundary'
		| 'protocolAllowlist'
		| 'rewrite'
		| 'origin'
		| 'ssr'
		| 'defaultComponent'
		| 'defaultErrorComponent'
		| 'defaultPendingComponent'
		| 'defaultNotFoundComponent'
		| 'Wrap'
		| 'InnerWrap'
		| 'defaultOnCatch';
	// @octanejs/tanstack-router.UpdateFn
	391: never;
	// @octanejs/tanstack-router.ParseLocationFn
	392: never;
	// @octanejs/tanstack-router.InvalidateFn
	393: never;
	// @octanejs/tanstack-router.ControllablePromise
	394: typeof Symbol.toStringTag | 'then' | 'catch' | 'finally' | 'resolve' | 'reject';
	// @octanejs/tanstack-router.InjectedHtmlEntry
	395: typeof Symbol.toStringTag | 'then' | 'catch' | 'finally';
	// @octanejs/tanstack-router.EmitFn
	396: never;
	// @octanejs/tanstack-router.LoadFn
	397: never;
	// @octanejs/tanstack-router.SubscribeFn
	398: never;
	// @octanejs/tanstack-router.CommitLocationFn
	399: never;
	// @octanejs/tanstack-router.GetMatchRoutesFn
	400: never;
	// @octanejs/tanstack-router.MatchRoutesFn
	401: never;
	// @octanejs/tanstack-router.StartTransitionFn
	402: never;
	// @octanejs/tanstack-router.LoadRouteChunkFn
	403: never;
	// @octanejs/tanstack-router.ClearCacheFn
	404: never;
	// @octanejs/tanstack-router.CreateRouterFn
	405: never;
	// @octanejs/tanstack-router.SSROption
	406: false | true | 'data-only';
	// @octanejs/tanstack-router.MatchLocation
	407: 'caseSensitive' | 'fuzzy' | 'to' | 'from';
	// @octanejs/tanstack-router.CommitLocationOptions
	408:
		| 'replace'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker';
	// @octanejs/tanstack-router.NavigateFn
	409: never;
	// @octanejs/tanstack-router.BuildLocationFn
	410: never;
	// @octanejs/tanstack-router.retainSearchParams
	411: 1;
	// @octanejs/tanstack-router.stripSearchParams
	412: never;
	// @octanejs/tanstack-router.defaultParseSearch
	413: 1;
	// @octanejs/tanstack-router.defaultStringifySearch
	414: 1;
	// @octanejs/tanstack-router.parseSearchWith
	415: 1;
	// @octanejs/tanstack-router.stringifySearchWith
	416: 1 | 2;
	// @octanejs/tanstack-router.SearchSerializer
	417: never;
	// @octanejs/tanstack-router.SearchParser
	418: never;
	// @octanejs/tanstack-router.OptionalStructuralSharing
	419: 'structuralSharing';
	// @octanejs/tanstack-router.functionalUpdate
	420: 2;
	// @octanejs/tanstack-router.hasKeys
	421: 1;
	// @octanejs/tanstack-router.replaceEqualDeep
	422: 2 | 3 | 4;
	// @octanejs/tanstack-router.isPlainObject
	423: 1;
	// @octanejs/tanstack-router.isPlainArray
	424: 1;
	// @octanejs/tanstack-router.deepEqual
	425: 2 | 3;
	// @octanejs/tanstack-router.createControlledPromise
	426: 0 | 1;
	// @octanejs/tanstack-router.isModuleNotFoundError
	427: 1;
	// @octanejs/tanstack-router.DEFAULT_PROTOCOL_ALLOWLIST
	428:
		| number
		| typeof Symbol.iterator
		| typeof Symbol.unscopables
		| 'length'
		| 'push'
		| 'toString'
		| 'toLocaleString'
		| 'concat'
		| 'join'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'every'
		| 'some'
		| 'forEach'
		| 'map'
		| 'filter'
		| 'reduce'
		| 'reduceRight'
		| 'find'
		| 'findIndex'
		| 'entries'
		| 'keys'
		| 'values'
		| 'includes'
		| 'flatMap'
		| 'flat'
		| 'at'
		| 'findLast'
		| 'findLastIndex'
		| 'toReversed'
		| 'toSorted'
		| 'toSpliced'
		| 'with'
		| 'pop'
		| 'reverse'
		| 'shift'
		| 'sort'
		| 'splice'
		| 'unshift'
		| 'fill'
		| 'copyWithin';
	// @octanejs/tanstack-router.escapeHtml
	429: 1;
	// @octanejs/tanstack-router.getUrlScheme
	430: 1;
	// @octanejs/tanstack-router.isDangerousProtocol
	431: 2;
	// @octanejs/tanstack-router.buildDevStylesUrl
	432: 2;
	// @octanejs/tanstack-router.NoInfer
	433: 'value';
	// @octanejs/tanstack-router.IsAny
	434: 'value';
	// @octanejs/tanstack-router.PickAsRequired
	435: 'value';
	// @octanejs/tanstack-router.PickRequired
	436: 'value';
	// @octanejs/tanstack-router.PickOptional
	437: never;
	// @octanejs/tanstack-router.WithoutEmpty
	438: 'value';
	// @octanejs/tanstack-router.Expand
	439: 'value';
	// @octanejs/tanstack-router.DeepPartial
	440: 'value';
	// @octanejs/tanstack-router.MakeDifferenceOptional
	441: 'value';
	// @octanejs/tanstack-router.IsUnion
	442: false;
	// @octanejs/tanstack-router.IsNonEmptyObject
	443: true;
	// @octanejs/tanstack-router.Assign
	444: 'value';
	// @octanejs/tanstack-router.IntersectAssign
	445: 'value';
	// @octanejs/tanstack-router.Timeout
	446:
		| typeof Symbol.dispose
		| typeof Symbol.toPrimitive
		| 'ref'
		| 'close'
		| 'hasRef'
		| 'refresh'
		| 'unref'
		| '_onTimeout';
	// @octanejs/tanstack-router.Updater
	447: never;
	// @octanejs/tanstack-router.NonNullableUpdater
	448: never;
	// @octanejs/tanstack-router.StringLiteral
	449: never;
	// @octanejs/tanstack-router.ThrowOrOptional
	450: 'value';
	// @octanejs/tanstack-router.ThrowConstraint
	451: true;
	// @octanejs/tanstack-router.ControlledPromise
	452:
		| typeof Symbol.toStringTag
		| 'value'
		| 'status'
		| 'then'
		| 'catch'
		| 'finally'
		| 'resolve'
		| 'reject';
	// @octanejs/tanstack-router.ExtractObjects
	453: 'value';
	// @octanejs/tanstack-router.PartialMergeAllObject
	454: 'value';
	// @octanejs/tanstack-router.MergeAllPrimitive
	455: never;
	// @octanejs/tanstack-router.ExtractPrimitives
	456: never;
	// @octanejs/tanstack-router.PartialMergeAll
	457: 'value';
	// @octanejs/tanstack-router.Constrain
	458: 'value';
	// @octanejs/tanstack-router.ConstrainLiteral
	459: 'value';
	// @octanejs/tanstack-router.UnionToIntersection
	460: 'value';
	// @octanejs/tanstack-router.MergeAllObjects
	461: 'value';
	// @octanejs/tanstack-router.MergeAll
	462: 'value';
	// @octanejs/tanstack-router.ValidateJSON
	463: 'value';
	// @octanejs/tanstack-router.StrictOrFrom
	464: 'from' | 'strict';
	// @octanejs/tanstack-router.LooseReturnType
	465: never;
	// @octanejs/tanstack-router.LooseAsyncReturnType
	466: never;
	// @octanejs/tanstack-router.Awaitable
	467: never;
	// @octanejs/tanstack-router.StandardSchemaValidatorProps
	468: 'types' | 'validate';
	// @octanejs/tanstack-router.StandardSchemaValidator
	469: '~standard';
	// @octanejs/tanstack-router.AnyStandardSchemaValidator
	470: '~standard';
	// @octanejs/tanstack-router.StandardSchemaValidatorTypes
	471: 'input' | 'output';
	// @octanejs/tanstack-router.AnyStandardSchemaValidateSuccess
	472: 'value' | 'issues';
	// @octanejs/tanstack-router.AnyStandardSchemaValidateFailure
	473: 'issues';
	// @octanejs/tanstack-router.AnyStandardSchemaValidateIssue
	474: 'message';
	// @octanejs/tanstack-router.AnyStandardSchemaValidateInput
	475: 'value';
	// @octanejs/tanstack-router.AnyStandardSchemaValidate
	476: never;
	// @octanejs/tanstack-router.ValidatorObj
	477: 'parse';
	// @octanejs/tanstack-router.AnyValidatorObj
	478: 'parse';
	// @octanejs/tanstack-router.ValidatorAdapter
	479: 'types' | 'parse';
	// @octanejs/tanstack-router.AnyValidatorAdapter
	480: 'types' | 'parse';
	// @octanejs/tanstack-router.AnyValidatorFn
	481: never;
	// @octanejs/tanstack-router.ValidatorFn
	482: never;
	// @octanejs/tanstack-router.Validator
	483: never;
	// @octanejs/tanstack-router.AnyValidator
	484: never;
	// @octanejs/tanstack-router.AnySchema
	485: never;
	// @octanejs/tanstack-router.DefaultValidator
	486: never;
	// @octanejs/tanstack-router.ResolveSearchValidatorInputFn
	487: never;
	// @octanejs/tanstack-router.ResolveSearchValidatorInput
	488: never;
	// @octanejs/tanstack-router.ResolveValidatorInputFn
	489: undefined;
	// @octanejs/tanstack-router.ResolveValidatorInput
	490: undefined;
	// @octanejs/tanstack-router.ResolveValidatorOutputFn
	491: never;
	// @octanejs/tanstack-router.ResolveValidatorOutput
	492: never;
	// @octanejs/tanstack-router.UseRouteContextBaseOptions
	493: 'select';
	// @octanejs/tanstack-router.UseRouteContextOptions
	494: 'from' | 'select' | 'strict';
	// @octanejs/tanstack-router.UseRouteContextResult
	495: 'value';
	// @octanejs/tanstack-router.UseSearchResult
	496: 'value';
	// @octanejs/tanstack-router.ResolveUseSearch
	497: string | number | symbol;
	// @octanejs/tanstack-router.UseParamsResult
	498: 'value';
	// @octanejs/tanstack-router.ResolveUseParams
	499: string | number | symbol;
	// @octanejs/tanstack-router.UseNavigateResult
	500: never;
	// @octanejs/tanstack-router.UseLoaderDepsResult
	501: 'value';
	// @octanejs/tanstack-router.ResolveUseLoaderDeps
	502: string | number | symbol;
	// @octanejs/tanstack-router.UseLoaderDataResult
	503: 'value';
	// @octanejs/tanstack-router.ResolveUseLoaderData
	504: string | number | symbol;
	// @octanejs/tanstack-router.Redirect
	505:
		| 'headers'
		| 'options'
		| 'body'
		| 'text'
		| 'type'
		| 'status'
		| 'url'
		| 'ok'
		| 'redirected'
		| 'statusText'
		| 'clone'
		| 'bodyUsed'
		| 'arrayBuffer'
		| 'blob'
		| 'bytes'
		| 'formData'
		| 'json';
	// @octanejs/tanstack-router.RedirectOptions
	506:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'headers'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'code'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'statusCode'
		| 'throw';
	// @octanejs/tanstack-router.RedirectOptionsRoute
	507:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'headers'
		| 'to'
		| 'unsafeRelative'
		| 'code'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'statusCode'
		| 'throw';
	// @octanejs/tanstack-router.RedirectFnRoute
	508: never;
	// @octanejs/tanstack-router.ResolvedRedirect
	509:
		| 'headers'
		| 'options'
		| 'body'
		| 'text'
		| 'type'
		| 'status'
		| 'url'
		| 'ok'
		| 'redirected'
		| 'statusText'
		| 'clone'
		| 'bodyUsed'
		| 'arrayBuffer'
		| 'blob'
		| 'bytes'
		| 'formData'
		| 'json';
	// @octanejs/tanstack-router.AnyRedirect
	510:
		| 'headers'
		| 'options'
		| 'body'
		| 'text'
		| 'type'
		| 'status'
		| 'url'
		| 'ok'
		| 'redirected'
		| 'statusText'
		| 'clone'
		| 'bodyUsed'
		| 'arrayBuffer'
		| 'blob'
		| 'bytes'
		| 'formData'
		| 'json';
	// @octanejs/tanstack-router.redirect
	511: 1;
	// @octanejs/tanstack-router.isRedirect
	512: 1;
	// @octanejs/tanstack-router.isResolvedRedirect
	513: 1;
	// @octanejs/tanstack-router.parseRedirect
	514: 1;
	// @octanejs/tanstack-router.NotFoundError
	515: 'headers' | 'data' | 'routeId' | 'throw' | 'global' | '_global';
	// @octanejs/tanstack-router.isNotFound
	516: 1;
	// @octanejs/tanstack-router.notFound
	517: 0 | 1;
	// @octanejs/tanstack-router.defaultGetScrollRestorationKey
	518: 1;
	// @octanejs/tanstack-router.getElementScrollRestorationEntry
	519: 2;
	// @octanejs/tanstack-router.storageKey
	520:
		| number
		| typeof Symbol.iterator
		| 'length'
		| 'replace'
		| 'search'
		| 'toString'
		| 'concat'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'includes'
		| 'at'
		| 'charAt'
		| 'charCodeAt'
		| 'localeCompare'
		| 'match'
		| 'split'
		| 'substring'
		| 'toLowerCase'
		| 'toLocaleLowerCase'
		| 'toUpperCase'
		| 'toLocaleUpperCase'
		| 'trim'
		| 'substr'
		| 'codePointAt'
		| 'endsWith'
		| 'normalize'
		| 'repeat'
		| 'startsWith'
		| 'anchor'
		| 'big'
		| 'blink'
		| 'bold'
		| 'fixed'
		| 'fontcolor'
		| 'fontsize'
		| 'italics'
		| 'link'
		| 'small'
		| 'strike'
		| 'sub'
		| 'sup'
		| 'padStart'
		| 'padEnd'
		| 'trimEnd'
		| 'trimStart'
		| 'trimLeft'
		| 'trimRight'
		| 'matchAll'
		| 'replaceAll'
		| 'isWellFormed'
		| 'toWellFormed'
		| 'valueOf';
	// @octanejs/tanstack-router.setupScrollRestoration
	521: 1 | 2;
	// @octanejs/tanstack-router.ScrollRestorationOptions
	522: 'getKey' | 'scrollBehavior';
	// @octanejs/tanstack-router.ScrollRestorationEntry
	523: 'scrollX' | 'scrollY';
	// @octanejs/tanstack-router.ValidateFromPath
	524: string;
	// @octanejs/tanstack-router.ValidateToPath
	525: string | number | symbol;
	// @octanejs/tanstack-router.ValidateSearch
	526: 'search';
	// @octanejs/tanstack-router.ValidateParams
	527: 'params';
	// @octanejs/tanstack-router.InferFrom
	528: string;
	// @octanejs/tanstack-router.InferTo
	529: undefined;
	// @octanejs/tanstack-router.InferMaskTo
	530: '';
	// @octanejs/tanstack-router.InferMaskFrom
	531: string;
	// @octanejs/tanstack-router.ValidateNavigateOptions
	532:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument';
	// @octanejs/tanstack-router.ValidateNavigateOptionsArray
	533:
		| number
		| typeof Symbol.iterator
		| typeof Symbol.unscopables
		| 'length'
		| 'toString'
		| 'toLocaleString'
		| 'concat'
		| 'join'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'every'
		| 'some'
		| 'forEach'
		| 'map'
		| 'filter'
		| 'reduce'
		| 'reduceRight'
		| 'find'
		| 'findIndex'
		| 'entries'
		| 'keys'
		| 'values'
		| 'includes'
		| 'flatMap'
		| 'flat'
		| 'at'
		| 'findLast'
		| 'findLastIndex'
		| 'toReversed'
		| 'toSorted'
		| 'toSpliced'
		| 'with';
	// @octanejs/tanstack-router.ValidateRedirectOptions
	534:
		| 'replace'
		| 'state'
		| 'href'
		| 'search'
		| 'hash'
		| 'params'
		| 'headers'
		| 'to'
		| 'from'
		| 'unsafeRelative'
		| 'code'
		| 'mask'
		| '_fromLocation'
		| 'hashScrollIntoView'
		| 'resetScroll'
		| 'startTransition'
		| 'viewTransition'
		| 'ignoreBlocker'
		| 'reloadDocument'
		| 'statusCode'
		| 'throw';
	// @octanejs/tanstack-router.ValidateRedirectOptionsArray
	535:
		| number
		| typeof Symbol.iterator
		| typeof Symbol.unscopables
		| 'length'
		| 'toString'
		| 'toLocaleString'
		| 'concat'
		| 'join'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'every'
		| 'some'
		| 'forEach'
		| 'map'
		| 'filter'
		| 'reduce'
		| 'reduceRight'
		| 'find'
		| 'findIndex'
		| 'entries'
		| 'keys'
		| 'values'
		| 'includes'
		| 'flatMap'
		| 'flat'
		| 'at'
		| 'findLast'
		| 'findLastIndex'
		| 'toReversed'
		| 'toSorted'
		| 'toSpliced'
		| 'with';
	// @octanejs/tanstack-router.ValidateId
	536: string | number | symbol;
	// @octanejs/tanstack-router.InferStrict
	537: true;
	// @octanejs/tanstack-router.InferShouldThrow
	538: true;
	// @octanejs/tanstack-router.InferSelected
	539: never;
	// @octanejs/tanstack-router.ValidateUseSearchResult
	540: string | number | symbol;
	// @octanejs/tanstack-router.ValidateUseParamsResult
	541: string | number | symbol;
	// @octanejs/tanstack-router.AnySerializationAdapter
	542: 'key' | '~types' | 'extends' | 'test' | 'toSerializable' | 'fromSerializable';
	// @octanejs/tanstack-router.SerializationAdapter
	543: 'key' | '~types' | 'extends' | 'test' | 'toSerializable' | 'fromSerializable';
	// @octanejs/tanstack-router.ValidateSerializableInput
	544: 'value';
	// @octanejs/tanstack-router.SerializerExtensions
	545: 'ReadableStream';
	// @octanejs/tanstack-router.ValidateSerializable
	546: 'value';
	// @octanejs/tanstack-router.RegisteredSerializableInput
	547: never;
	// @octanejs/tanstack-router.SerializableExtensions
	548:
		| 'string'
		| 'number'
		| 'bigint'
		| 'boolean'
		| 'undefined'
		| 'null'
		| 'Date'
		| 'Uint8Array'
		| 'RawStream'
		| 'TsrSerializable'
		| 'void';
	// @octanejs/tanstack-router.DefaultSerializable
	549:
		| 'string'
		| 'number'
		| 'bigint'
		| 'boolean'
		| 'undefined'
		| 'null'
		| 'Date'
		| 'Uint8Array'
		| 'RawStream'
		| 'TsrSerializable'
		| 'void';
	// @octanejs/tanstack-router.Serializable
	550: never;
	// @octanejs/tanstack-router.TSR_SERIALIZABLE
	551: import('@tanstack/router-core').TSR_SERIALIZABLE;
	// @octanejs/tanstack-router.TsrSerializable
	552: import('@tanstack/router-core').TSR_SERIALIZABLE;
	// @octanejs/tanstack-router.SerializationError
	553: keyof import('@tanstack/router-core').SerializationError<'/example'>;
	// @octanejs/tanstack-router.createSerializationAdapter
	554: 1;
	// @octanejs/tanstack-router.makeSerovalPlugin
	555: 1;
	// @octanejs/tanstack-router.makeSsrSerovalPlugin
	556: 2;
	// @octanejs/tanstack-router.defaultSerovalPlugins
	557:
		| number
		| typeof Symbol.iterator
		| typeof Symbol.unscopables
		| 'length'
		| 'push'
		| 'toString'
		| 'toLocaleString'
		| 'concat'
		| 'join'
		| 'slice'
		| 'indexOf'
		| 'lastIndexOf'
		| 'every'
		| 'some'
		| 'forEach'
		| 'map'
		| 'filter'
		| 'reduce'
		| 'reduceRight'
		| 'find'
		| 'findIndex'
		| 'entries'
		| 'keys'
		| 'values'
		| 'includes'
		| 'flatMap'
		| 'flat'
		| 'at'
		| 'findLast'
		| 'findLastIndex'
		| 'toReversed'
		| 'toSorted'
		| 'toSpliced'
		| 'with'
		| 'pop'
		| 'reverse'
		| 'shift'
		| 'sort'
		| 'splice'
		| 'unshift'
		| 'fill'
		| 'copyWithin';
	// @octanejs/tanstack-router.RawStream
	558: 1 | 2;
	// @octanejs/tanstack-router.createRawStreamRPCPlugin
	559: 1;
	// @octanejs/tanstack-router.createRawStreamDeserializePlugin
	560: 1;
	// @octanejs/tanstack-router.OnRawStreamCallback
	561: never;
	// @octanejs/tanstack-router.RawStreamHint
	562: 'text' | 'binary';
	// @octanejs/tanstack-router.RawStreamOptions
	563: 'hint';
	// @octanejs/tanstack-router.composeRewrites
	564: 1;
	// @octanejs/tanstack-router.executeRewriteInput
	565: 2;
	// @octanejs/tanstack-router.LocationRewrite
	566: 'input' | 'output';
	// @octanejs/tanstack-router.LocationRewriteFunction
	567: never;
	// @octanejs/tanstack-router.RouterConfigOptions
	568: 'serializationAdapters' | 'defaultSsr';
	// @octanejs/tanstack-router.RouterConfig
	569: 'serializationAdapters' | 'defaultSsr' | '~types';
	// @octanejs/tanstack-router.RouterConfigTypes
	570: 'serializationAdapters' | 'defaultSsr';
	// @octanejs/tanstack-router.createRouterConfig
	571: 1;
	// @octanejs/tanstack-router.AnyRouterConfig
	572: 'serializationAdapters' | 'defaultSsr' | '~types';
	// @octanejs/tanstack-router/history.createHistory
	573: 1;
	// @octanejs/tanstack-router/history.createBrowserHistory
	574: 0 | 1;
	// @octanejs/tanstack-router/history.createHashHistory
	575: 0 | 1;
	// @octanejs/tanstack-router/history.createMemoryHistory
	576: 0 | 1;
	// @octanejs/tanstack-router/history.normalizeProtocolRelative
	577: 1;
	// @octanejs/tanstack-router/history.parseHref
	578: 2;
	// @octanejs/tanstack-router/history.NavigateOptions
	579: 'ignoreBlocker';
	// @octanejs/tanstack-router/history.RouterHistory
	580:
		| 'length'
		| 'location'
		| 'subscribers'
		| 'subscribe'
		| 'push'
		| 'replace'
		| 'go'
		| 'back'
		| 'forward'
		| 'canGoBack'
		| 'createHref'
		| 'block'
		| 'flush'
		| 'destroy'
		| 'notify'
		| '_getBlockers'
		| '_ignoreSubscribers'
		| '_ignoreNextBeforeUnload';
	// @octanejs/tanstack-router/history.HistoryLocation
	581: 'state' | 'href' | 'pathname' | 'search' | 'hash';
	// @octanejs/tanstack-router/history.ParsedPath
	582: 'href' | 'pathname' | 'search' | 'hash';
	// @octanejs/tanstack-router/history.HistoryState
	583: '__tempLocation' | '__tempKey' | '__hashScrollIntoViewOptions';
	// @octanejs/tanstack-router/history.ParsedHistoryState
	584:
		| '__tempLocation'
		| '__tempKey'
		| '__hashScrollIntoViewOptions'
		| 'key'
		| '__TSR_key'
		| '__TSR_index';
	// @octanejs/tanstack-router/history.HistoryAction
	585: 'PUSH' | 'REPLACE' | 'FORWARD' | 'BACK' | 'GO';
	// @octanejs/tanstack-router/history.BlockerFnArgs
	586: 'currentLocation' | 'nextLocation' | 'action';
	// @octanejs/tanstack-router/history.BlockerFn
	587: never;
	// @octanejs/tanstack-router/history.NavigationBlocker
	588: 'blockerFn' | 'enableBeforeUnload';
	// @octanejs/tanstack-router/ssr/server.RouterServer
	589: 1;
	// @octanejs/tanstack-router/ssr/server.defaultRenderHandler
	590: 1;
	// @octanejs/tanstack-router/ssr/server.defaultStreamHandler
	591: 1;
	// @octanejs/tanstack-router/ssr/server.renderRouterToStream
	592: 1;
	// @octanejs/tanstack-router/ssr/server.renderRouterToString
	593: 1;
	// @octanejs/tanstack-router/ssr/server.createRequestHandler
	594: 1;
	// @octanejs/tanstack-router/ssr/server.waitForRequest
	595: 2 | 3;
	// @octanejs/tanstack-router/ssr/server.RequestHandler
	596: never;
	// @octanejs/tanstack-router/ssr/server.bindSsrResponseToRequest
	597: 3;
	// @octanejs/tanstack-router/ssr/server.createSsrStreamResponse
	598: 2;
	// @octanejs/tanstack-router/ssr/server.defineHandlerCallback
	599: 1;
	// @octanejs/tanstack-router/ssr/server.disposeSsrResponse
	600: 1 | 2;
	// @octanejs/tanstack-router/ssr/server.disposeSsrResponseDetached
	601: 1 | 2 | 3;
	// @octanejs/tanstack-router/ssr/server.isSsrResponse
	602: 1;
	// @octanejs/tanstack-router/ssr/server.normalizeSsrResponse
	603: 1;
	// @octanejs/tanstack-router/ssr/server.replaceSsrResponse
	604: 2 | 3;
	// @octanejs/tanstack-router/ssr/server.stripSsrResponseBody
	605: 1 | 2;
	// @octanejs/tanstack-router/ssr/server.HandlerCallback
	606: never;
	// @octanejs/tanstack-router/ssr/server.HandlerCallbackResult
	607: never;
	// @octanejs/tanstack-router/ssr/server.SsrResponse
	608: 'response' | 'serverSsrCleanup';
	// @octanejs/tanstack-router/ssr/server.transformPipeableStreamWithRouter
	609: 2 | 3;
	// @octanejs/tanstack-router/ssr/server.transformStreamWithRouter
	610: 2 | 3;
	// @octanejs/tanstack-router/ssr/server.transformReadableStreamWithRouter
	611: 2 | 3;
	// @octanejs/tanstack-router/ssr/server.TransformStreamWithRouterOptions
	612: 'onAbort' | 'signal' | 'timeoutMs' | 'lifetimeMs';
	// @octanejs/tanstack-router/ssr/server.attachRouterServerSsrUtils
	613: 1;
	// @octanejs/tanstack-router/ssr/server.getNormalizedURL
	614: 1 | 2;
	// @octanejs/tanstack-router/ssr/server.getOrigin
	615: 1;
	// @octanejs/tanstack-router/ssr/client.RouterClient
	616: 1;
	// @octanejs/tanstack-router/ssr/client.mergeHeaders
	617: number;
	// @octanejs/tanstack-router/ssr/client.json
	618: 1 | 2;
	// @octanejs/tanstack-router/ssr/client.JsonResponse
	619:
		| 'headers'
		| 'body'
		| 'text'
		| 'type'
		| 'status'
		| 'url'
		| 'ok'
		| 'redirected'
		| 'statusText'
		| 'clone'
		| 'bodyUsed'
		| 'arrayBuffer'
		| 'blob'
		| 'bytes'
		| 'formData'
		| 'json';
	// @octanejs/tanstack-router/ssr/client.hydrate
	620: 1;
	// @octanejs/tanstack-router/ssr/client.TsrSsrGlobal
	621:
		'router' | 'p' | 'buffer' | 'h' | 'e' | 'c' | 't' | 'initialized' | 'hydrated' | 'streamEnded';
	// @octanejs/tanstack-router/ssr/client.DehydratedMatch
	622: 'ssr' | 'i' | 's' | 'u' | 'g' | 'e' | 'l';
	// @octanejs/tanstack-router/ssr/client.DehydratedRouter
	623: 'manifest' | 'matches' | 'dehydratedData';
	// @octanejs/tanstack-router/generator-plugin.maskOctaneRouteSource
	624: 1 | 2;
	// @octanejs/tanstack-router/generator-plugin.octaneRouteGeneratorPlugin
	625: 0;
	// @octanejs/tanstack-router/generator-plugin.TransformRouteSourceOptions
	626: 'source' | 'filename' | 'node';
	// @octanejs/tanstack-router/generator-plugin.FormatRouteOptions
	627: 'source' | 'node';
	// @octanejs/tanstack-router/generator-plugin.OctaneRouteGeneratorPlugin
	628: 'name' | 'transformRouteSource' | 'formatRoute';
}
