// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentType } from 'react';
import type { ChartA11yAnnouncerProps } from './components/ChartA11yAnnouncer.tsrx';
import type { ChartA11yDataTableProps } from './components/ChartA11yDataTable.tsrx';
import type { ChartA11yMode, ChartA11yPointFocus } from './keyboard/stateMachine';
import type { ChartA11yConfig, ChartA11yIds, ChartA11yPointProps, ChartA11ySeriesProps, ChartA11ySvgProps } from './types';
import type { UseChartKeyboardNavPointProps, UseChartKeyboardNavSvgProps } from './useChartKeyboardNav.tsrx';
export type { ChartA11yMode } from './keyboard/stateMachine';
export type UseChartA11ySvgProps = ChartA11ySvgProps & UseChartKeyboardNavSvgProps;
export type UseChartA11yPointProps = Partial<ChartA11yPointProps> & UseChartKeyboardNavPointProps;
export type UseChartA11yDataTableProps<Datum> = Pick<ChartA11yDataTableProps<Datum>, 'className' | 'style' | 'visible'>;
export type UseChartA11yAnnouncerProps = Omit<ChartA11yAnnouncerProps, 'message'>;
export type UseChartA11yResult<Datum> = {
    id: string;
    ids: ChartA11yIds;
    svgProps: UseChartA11ySvgProps;
    getSeriesProps: (seriesIndex: number) => ChartA11ySeriesProps;
    getPointProps: (seriesIndex: number, index: number) => UseChartA11yPointProps;
    descriptionId: string;
    description: string;
    DataTable: ComponentType<UseChartA11yDataTableProps<Datum>>;
    Announcer: ComponentType<UseChartA11yAnnouncerProps>;
    announce: (message: string) => void;
    mode: ChartA11yMode;
    focusedPoint: ChartA11yPointFocus | null;
};
export declare function useChartA11y<Datum>(config: ChartA11yConfig<Datum>): UseChartA11yResult<Datum>;
