// Generated by scripts/generate-tsrx-types.mjs.
import type { KeyboardEvent, RefCallback } from 'react';
import type { ChartA11yConfig } from './types';
import type { ChartA11yKeyboardState, ChartA11yPointFocus } from './keyboard/stateMachine';
export type UseChartKeyboardNavConfig<Datum> = Pick<ChartA11yConfig<Datum>, 'data' | 'keyboardNavEnabled' | 'locale' | 'onPointFocus' | 'pointDescriptionThreshold' | 'series'> & {
    onKeyboardHelp?: (message: string) => void;
};
export type UseChartKeyboardNavSvgProps = {
    tabIndex?: 0;
    onKeyDown?: (event: KeyboardEvent<SVGSVGElement>) => void;
    ref: RefCallback<SVGSVGElement>;
};
export type UseChartKeyboardNavPointProps = {
    ref: RefCallback<SVGElement>;
    tabIndex: 0 | -1;
    onFocus: () => void;
    'data-a11y-focused'?: boolean;
};
export type UseChartKeyboardNavResult = {
    svgProps: UseChartKeyboardNavSvgProps;
    getPointProps: (seriesIndex: number, index: number) => UseChartKeyboardNavPointProps;
    mode: ChartA11yKeyboardState['mode'];
    focusedPoint: ChartA11yPointFocus | null;
    focusPoint: (point: ChartA11yPointFocus | null) => void;
};
export declare function useChartKeyboardNav<Datum>({ data, keyboardNavEnabled, locale, onKeyboardHelp, onPointFocus, pointDescriptionThreshold, series, }: UseChartKeyboardNavConfig<Datum>): UseChartKeyboardNavResult;
