// Generated by scripts/generate-tsrx-types.mjs.
import type { AccessorInput } from '../accessors/normalizeAccessor';
export type DomainType = 'linear' | 'time' | 'band';
export type LinearDomain = readonly [number, number];
export type TimeDomain = readonly [Date, Date];
export type BandDomain = readonly string[];
export type DomainForType<T extends DomainType> = T extends 'band' ? BandDomain : T extends 'time' ? TimeDomain : LinearDomain;
export type UseDomainOptions<D, V, T extends DomainType> = {
    accessor: AccessorInput<D, V>;
    data: readonly D[];
    type: T;
};
export default function useDomain<D, V, T extends DomainType>({ accessor, data, type, }: UseDomainOptions<D, V, T>): DomainForType<T>;
