// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactNode } from 'react';
export type PortalProps = {
    /** Optional z-index to set on the Portal. */
    zIndex?: number | string;
    /** Content to render in the Portal. */
    children: NonNullable<ReactNode>;
};
/** Render within a portal using a declarative component API. */
export default function Portal({ zIndex, children }: PortalProps): import("octane").PortalDescriptor | null;
