// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactElement, FunctionComponent, HTMLProps, ComponentType } from 'react';
import type { UseTooltipParams } from '../hooks/useTooltip.tsrx';
export type WithTooltipProvidedProps<TooltipData> = UseTooltipParams<TooltipData>;
type WithTooltipContainerProps = HTMLProps<HTMLDivElement>;
type RenderTooltipContainer = (children: ReactElement, containerProps?: WithTooltipContainerProps) => ReactElement;
export default function withTooltip<BaseComponentProps = {}, TooltipData = {}>(BaseComponent: ComponentType<BaseComponentProps & WithTooltipProvidedProps<TooltipData>>, containerProps?: WithTooltipContainerProps, renderContainer?: RenderTooltipContainer): FunctionComponent<BaseComponentProps>;
export {};
