// Generated by scripts/generate-tsrx-types.mjs.
import type { AnimationTrajectory } from '@octanejs/visx/react-spring';
import type { BaseGridProps } from './BaseGrid.tsrx';
export type AnimatedGridProps = Omit<BaseGridProps, 'GridRowsComponent' | 'GridColumnsComponent'> & {
    /** Animation trajectory of grid lines. */
    animationTrajectory?: AnimationTrajectory;
};
export default function AnimatedGrid({ animationTrajectory, ...props }: AnimatedGridProps): import("react").JSX.Element;
