// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentBody } from 'octane';
import type { CommonGridProps, AllGridRowsProps, GridColumnsProps } from '@octanejs/visx/grid';
import type { AxisScale } from '@octanejs/visx/axis';
export type BaseGridProps = {
    /** Whether to render GridRows. */
    rows?: boolean;
    /** Whether to render GridColumns. */
    columns?: boolean;
    /** Rendered GridRows component which is passed GridRowProps by BaseGrid. */
    GridRowsComponent: ComponentBody<AllGridRowsProps<AxisScale>>;
    /** Rendered GridColumns component which is passed GridColumnsProps by BaseGrid. */
    GridColumnsComponent: ComponentBody<GridColumnsProps<AxisScale>>;
} & CommonGridProps;
/** Component that handles all  */
export default function BaseGrid({ rows, columns, GridRowsComponent, GridColumnsComponent, ...props }: BaseGridProps): import("react").JSX.Element;
