// Generated by scripts/generate-tsrx-types.mjs.
import type { BaseGridProps } from './BaseGrid.tsrx';
export type GridProps = Omit<BaseGridProps, 'GridRowsComponent' | 'GridColumnsComponent'>;
export default function Grid(props: GridProps): import("react").JSX.Element;
