// Generated by scripts/generate-tsrx-types.mjs.
type StateUpdate<P, S> = Partial<S> | S | ((state: Readonly<S>, props: Readonly<P>) => Partial<S> | S);
/**
 * Small lifecycle adapter for the nine class implementations retained by Visx
 * upstream. Classes are controller objects only; Octane always renders the
 * functional wrapper returned by legacyComponent.
 */
export declare class Component<P = Record<string, never>, S = any> {
    props: Readonly<P>;
    state: Readonly<S>;
    __applyUpdate?: (update: StateUpdate<P, S>, callback?: () => void) => void;
    constructor(props: P);
    setState(update: StateUpdate<P, S>, callback?: () => void): void;
    forceUpdate(callback?: () => void): void;
}
export declare class PureComponent<P = Record<string, never>, S = any> extends Component {
}
export declare function createRef<T>(): {
    current: T | null;
};
type LegacyController = Component<any, any> & {
    render: () => unknown;
    componentDidMount?: () => void;
    componentDidUpdate?: (previousProps: Readonly<any>, previousState: Readonly<any>) => void;
    componentWillUnmount?: () => void;
};
type LegacyConstructor = {
    new (props: any): LegacyController;
    defaultProps?: Record<string, unknown>;
    displayName?: string;
    name?: string;
};
export declare function legacyComponent<C extends LegacyConstructor>(Controller: C): ((props: ConstructorParameters<C>[0] & {
    ref?: unknown;
}) => any) & {
    displayName?: string;
    defaultProps: C['defaultProps'];
};
export {};
