// Generated by scripts/generate-tsrx-types.mjs.
type AnyRecord = Record<string, any>;
export declare class SpringValue<T> {
    private readonly value;
    constructor(value: T);
    get(): T;
    to<U>(interpolator: (value: T) => U): DerivedValue<U>;
}
declare class DerivedValue<T> {
    private readonly read;
    constructor(read: () => T);
    get(): T;
}
export declare const animated: Record<string, (props: AnyRecord) => unknown>;
export declare function to<T extends readonly unknown[], R>(inputs: T, interpolator: (...values: {
    [K in keyof T]: T[K] extends SpringValue<infer V> ? V : T[K];
}) => R): DerivedValue<R>;
export declare function useSpring(config: AnyRecord): AnyRecord;
/**
 * React-spring-compatible transition projection. It keeps leaving entries for
 * one animation frame and interpolates numeric style fields in one hook cell,
 * so keyed Visx series retain their enter/update/leave behavior without hooks
 * inside item loops.
 */
export declare function useTransition(items: any[], config: AnyRecord): (renderer: (style: AnyRecord, item: any, state: {
    key: any;
}, index: number) => unknown) => unknown[];
export {};
