// Generated by scripts/generate-tsrx-types.mjs.
export type RectReadOnly = {
    x: number;
    y: number;
    width: number;
    height: number;
    top: number;
    right: number;
    bottom: number;
    left: number;
};
export type ResizeObserverConstructor = new (callback: ResizeObserverCallback) => Pick<ResizeObserver, 'observe' | 'unobserve' | 'disconnect'>;
export type Options = {
    debounce?: number | {
        scroll?: number;
        resize?: number;
    };
    scroll?: boolean;
    polyfill?: ResizeObserverConstructor;
    offsetSize?: boolean;
};
export default function useMeasure(options?: Options): readonly [(element: HTMLElement | SVGElement | null) => void, RectReadOnly, () => void];
