// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentType, RefObject } from 'react';
type rectShape = {
    top: number;
    right: number;
    bottom: number;
    left: number;
    width: number;
    height: number;
};
export type WithBoundingRectsProps = {
    getRects?: () => {
        rect: rectShape;
        parentRect: rectShape;
    };
    rect?: rectShape;
    parentRect?: rectShape;
    nodeRef?: RefObject<HTMLElement>;
};
export default function withBoundingRects<Props extends object = {}>(BaseComponent: ComponentType<Props>): ComponentType<Props>;
export {};
