// Generated by scripts/generate-tsrx-types.mjs.
import { Component } from '../internal/legacy.tsrx';
import type { PointerEvent, SVGProps, ReactNode } from 'react';
import type { HandlerArgs as DragArgs } from '@octanejs/visx/drag';
import type { BrushHandleRenderProps } from './BrushHandle.tsrx';
import type { MarginShape, Point, BrushShape, ResizeTriggerAreas, PartialBrushStartEnd, BrushingType, BrushPageOffset } from './types';
type PointerHandlerEvent = PointerEvent<SVGRectElement>;
export type BaseBrushProps = {
    brushDirection?: 'horizontal' | 'vertical' | 'both';
    initialBrushPosition?: PartialBrushStartEnd;
    width: number;
    height: number;
    left: number;
    top: number;
    inheritedMargin?: MarginShape;
    onChange?: (state: BaseBrushState) => void;
    handleSize: number;
    resizeTriggerAreas?: ResizeTriggerAreas[];
    onBrushStart?: (start: BaseBrushState['start']) => void;
    onBrushEnd?: (state: BaseBrushState) => void;
    selectedBoxStyle: SVGProps<SVGRectElement>;
    onMouseLeave?: (event: PointerHandlerEvent) => void;
    onMouseUp?: (event: PointerHandlerEvent) => void;
    onMouseMove?: (event: PointerHandlerEvent) => void;
    onClick?: (event: PointerHandlerEvent) => void;
    clickSensitivity: number;
    disableDraggingSelection: boolean;
    disableDraggingOverlay?: boolean;
    resetOnEnd?: boolean;
    useWindowMoveEvents?: boolean;
    renderBrushHandle?: (props: BrushHandleRenderProps) => ReactNode;
};
export type BaseBrushState = BrushShape & {
    activeHandle: ResizeTriggerAreas | null;
    isBrushing: boolean;
    brushPageOffset?: BrushPageOffset;
    brushingType?: BrushingType;
};
export type UpdateBrush = BaseBrushState | ((prevState: Readonly<BaseBrushState>, props: Readonly<BaseBrushProps>) => BaseBrushState);
export declare class BaseBrush extends Component {
    constructor(props: BaseBrushProps);
    private mouseUpTime;
    private mouseDownTime;
    static defaultProps: {
        brushDirection: string;
        inheritedMargin: {
            left: number;
            top: number;
            right: number;
            bottom: number;
        };
        onChange: null;
        handleSize: number;
        resizeTriggerAreas: string[];
        onBrushStart: null;
        onBrushEnd: null;
        onMouseLeave: null;
        onMouseUp: null;
        onMouseMove: null;
        onClick: null;
        disableDraggingSelection: boolean;
        disableDraggingOverlay: boolean;
        clickSensitivity: number;
        resetOnEnd: boolean;
        initialBrushPosition: null;
        useWindowMoveEvents: boolean;
        renderBrushHandles: null;
    };
    getIdleState: () => {
        start: {
            x: number;
            y: number;
        };
        end: {
            x: number;
            y: number;
        };
        extent: {
            x0: number;
            x1: number;
            y0: number;
            y1: number;
        };
        bounds: {
            x0: number;
            x1: never;
            y0: number;
            y1: never;
        };
        isBrushing: boolean;
        brushPageOffset: undefined;
        activeHandle: null;
        brushingType: undefined;
    };
    componentDidUpdate(prevProps: BaseBrushProps): void;
    componentDidMount(): void;
    componentWillUnmount(): void;
    handleWindowPointerUp: () => void;
    handleWindowPointerMove: (event: MouseEvent) => void;
    debouncedHandleWindowPointerMove: (...args: any[]) => void;
    getExtent: (start: Partial<Point>, end: Partial<Point>) => {
        x0: number;
        x1: number;
        y0: number;
        y1: number;
    };
    handleDragStart: (draw: DragArgs) => void;
    handleBrushStart: (drag: DragArgs) => void;
    handleDragMove: (drag: DragArgs) => void;
    handleDragEnd: () => void;
    getBrushWidth: () => number;
    getBrushHeight: () => number;
    handles: () => Partial<{ [key in ResizeTriggerAreas]: {
        x: number;
        y: number;
        height: number;
        width: number;
    }; }>;
    corners: () => Partial<{ [key in ResizeTriggerAreas]: {
        x: number;
        y: number;
        width: number;
        height: number;
    }; }>;
    updateBrush: (updater: UpdateBrush) => void;
    reset: () => void;
    handleBrushingTypeChange: (type?: BrushingType, brushPageOffset?: BrushPageOffset) => void;
    render(): import("react").JSX.Element;
}
declare const _default: ((props: BaseBrushProps & {
    ref?: unknown;
}) => any) & {
    displayName?: string;
    defaultProps: {
        brushDirection: string;
        inheritedMargin: {
            left: number;
            top: number;
            right: number;
            bottom: number;
        };
        onChange: null;
        handleSize: number;
        resizeTriggerAreas: string[];
        onBrushStart: null;
        onBrushEnd: null;
        onMouseLeave: null;
        onMouseUp: null;
        onMouseMove: null;
        onClick: null;
        disableDraggingSelection: boolean;
        disableDraggingOverlay: boolean;
        clickSensitivity: number;
        resetOnEnd: boolean;
        initialBrushPosition: null;
        useWindowMoveEvents: boolean;
        renderBrushHandles: null;
    };
};
export default _default;
