// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
import type { Octane } from 'octane/jsx-runtime';
type BrushOverlayProps = {
    width: number;
    height: number;
    style?: CSSProperties;
} & Pick<Octane.SVGProps<SVGRectElement>, 'onClick' | 'onDoubleClick' | 'onPointerDown' | 'onPointerLeave' | 'onPointerMove' | 'onPointerUp'>;
export default function BrushOverlay(props: BrushOverlayProps): import("react").JSX.Element;
export {};
