// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties, PointerEvent } from 'react';
type BrushOverlayProps = {
    width: number;
    height: number;
    style?: CSSProperties;
    onClick?: (event: PointerEvent<SVGRectElement>) => void;
    onDoubleClick?: (event: PointerEvent<SVGRectElement>) => void;
    onPointerDown?: (event: PointerEvent<SVGRectElement>) => void;
    onPointerLeave?: (event: PointerEvent<SVGRectElement>) => void;
    onPointerMove?: (event: PointerEvent<SVGRectElement>) => void;
    onPointerUp?: (event: PointerEvent<SVGRectElement>) => void;
};
export default function BrushOverlay(props: BrushOverlayProps): import("react").JSX.Element;
export {};
