// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
import type { BaseBrushState as BrushState, UpdateBrush } from './BaseBrush.tsrx';
import type { ResizeTriggerAreas } from './types';
export type BrushCornerProps = {
    stageWidth: number;
    stageHeight: number;
    brush: BrushState;
    updateBrush: (update: UpdateBrush) => void;
    onBrushEnd?: (brush: BrushState) => void;
    type: ResizeTriggerAreas;
    style?: CSSProperties;
    corner: {
        x: number;
        y: number;
        width: number;
        height: number;
    };
};
export type BrushCornerState = {};
declare const _default: ((props: Record<string, never> & {
    ref?: unknown;
}) => any) & {
    displayName?: string;
    defaultProps: {
        style: {};
    };
};
export default _default;
