// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps, PointerEvent } from 'react';
import type { HandlerArgs as DragArgs } from '@octanejs/visx/drag';
import type { BaseBrushState as BrushState, UpdateBrush } from './BaseBrush.tsrx';
import type { BrushPageOffset, BrushingType } from './types';
type PointerHandler = (event: PointerEvent<SVGRectElement>) => void;
export type BrushSelectionProps = {
    width: number;
    height: number;
    stageWidth: number;
    stageHeight: number;
    brush: BrushState;
    updateBrush: (update: UpdateBrush) => void;
    onMoveSelectionChange?: (type?: BrushingType, options?: BrushPageOffset) => void;
    onBrushStart?: (brush: DragArgs) => void;
    onBrushEnd?: (brush: BrushState) => void;
    disableDraggingSelection: boolean;
    onMouseLeave: PointerHandler;
    onMouseMove: PointerHandler;
    onMouseUp: PointerHandler;
    onClick: PointerHandler;
    selectedBoxStyle: SVGProps<SVGRectElement>;
    isControlled?: boolean;
    isDragInProgress?: boolean;
};
declare const _default: ((props: Record<string, never> & {
    ref?: unknown;
}) => any) & {
    displayName?: string;
    defaultProps: {
        onMouseLeave: null;
        onMouseUp: null;
        onMouseMove: null;
        onClick: null;
    };
};
export default _default;
