// Generated by scripts/generate-tsrx-types.mjs.
import type { JSX as ReactJSX } from 'react';
import type { OctaneNode } from 'octane';
import type { CSSVarStyle, VisxThemeDefinition } from '../tokens/types';
export type ThemeScopeElement = keyof ReactJSX.IntrinsicElements;
interface BaseThemeScopeProps {
    className?: string;
    style?: CSSVarStyle;
    children: OctaneNode;
}
interface AutoThemeScopeProps extends BaseThemeScopeProps {
    theme?: 'auto';
    as?: ThemeScopeElement | false;
}
interface EmittingThemeScopeProps extends BaseThemeScopeProps {
    theme: 'light' | 'dark' | VisxThemeDefinition;
    as?: ThemeScopeElement;
}
export type ThemeScopeProps = AutoThemeScopeProps | EmittingThemeScopeProps;
export default function ThemeScope({ as, children, className, style, theme, }: ThemeScopeProps): import("octane").ElementDescriptor<null> | import("octane").ElementDescriptor<{
    className: string | undefined;
    style: CSSVarStyle | undefined;
}>;
export {};
