// Generated by scripts/generate-tsrx-types.mjs.
import type { ScaleConfig } from '@octanejs/visx/scale';
import type { OctaneNode } from 'octane';
import type { AxisScaleOutput } from '@octanejs/visx/axis';
import type { ResizeObserverPolyfill } from '@octanejs/visx/responsive';
import type { XYChartTheme } from '../types';
import type { Dimensions } from '../hooks/useDimensions.tsrx';
/** Props that can be passed to initialize/update the provider config. */
export type DataProviderProps<XScaleConfig extends ScaleConfig<AxisScaleOutput, any, any>, YScaleConfig extends ScaleConfig<AxisScaleOutput, any, any>> = {
    initialDimensions?: Partial<Dimensions>;
    theme?: XYChartTheme;
    xScale: XScaleConfig;
    yScale: YScaleConfig;
    children: OctaneNode;
    horizontal?: boolean | 'auto';
    /**
 * Optionally set the resizeObserverPolyfill context, which will be available to
 * ParentSize, Tooltip, and AnnotationLabel components.
 */
    resizeObserverPolyfill?: ResizeObserverPolyfill;
};
export default function DataProvider<XScaleConfig extends ScaleConfig<AxisScaleOutput>, YScaleConfig extends ScaleConfig<AxisScaleOutput>, Datum extends object>({ initialDimensions, theme: propsTheme, xScale: xScaleConfig, yScale: yScaleConfig, children, horizontal: initialHorizontal, resizeObserverPolyfill, }: DataProviderProps<XScaleConfig, YScaleConfig>): import("react").JSX.Element;
