// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactNode } from 'react';
/** Provider for EventEmitterContext. */
export default function EventEmitterProvider({ children }: {
    children: ReactNode;
}): import("react").JSX.Element;
