// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
/** Provider for EventEmitterContext. */
export default function EventEmitterProvider({ children }: {
    children: OctaneNode;
}): import("react").JSX.Element;
