// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactNode } from 'react';
import type { XYChartTheme } from '../types';
export type ThemeProviderProps = {
    theme?: XYChartTheme;
    children: ReactNode;
};
export default function ThemeProvider({ theme, children }: ThemeProviderProps): import("react").JSX.Element;
