// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
import type { XYChartTheme } from '../types';
export type ThemeProviderProps = {
    theme?: XYChartTheme;
    children: OctaneNode;
};
export default function ThemeProvider({ theme, children }: ThemeProviderProps): import("react").JSX.Element;
