// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
type TooltipProviderProps = {
    /** Debounce time for when `hideTooltip` is invoked. */
    hideTooltipDebounceMs?: number;
    children: OctaneNode;
};
/** Simple wrapper around useTooltip, to provide tooltip data via context. */
export default function TooltipProvider<Datum extends object>({ hideTooltipDebounceMs, children, }: TooltipProviderProps): import("react").JSX.Element;
export {};
