// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisRendererProps, AxisScale } from '../types';
export default function AxisRenderer<Scale extends AxisScale>({ axisFromPoint, axisLineClassName, axisToPoint, hideAxisLine, hideTicks, horizontal, label, labelClassName, labelOffset, labelProps, orientation, scale, stroke, strokeDasharray, strokeWidth, tickClassName, tickComponent, tickLineProps, tickLabelProps, tickLength, tickStroke, tickTransform, ticks, ticksComponent, }: AxisRendererProps<Scale>): import("react").JSX.Element;
