// Generated by scripts/generate-tsrx-types.mjs.
import type { SharedAxisProps, AxisScale } from '../types';
import type { OrientationType } from '../constants/orientation';
export type AxisProps<Scale extends AxisScale> = SharedAxisProps<Scale> & {
    orientation?: OrientationType;
};
export default function Axis<Scale extends AxisScale>({ children, axisClassName, hideAxisLine, hideTicks, hideZero, innerRef, left, numTicks, orientation, rangePadding, scale, tickFormat, tickLength, tickValues, top, ...restProps }: AxisProps<Scale>): import("react").JSX.Element;
