// Generated by scripts/generate-tsrx-types.mjs.
import type { SharedAxisProps, AxisScale } from '../types';
export type AxisTopProps<Scale extends AxisScale> = SharedAxisProps<Scale>;
export declare const topTickLabelProps: {
    readonly dy: "-0.75em";
    readonly fill: "#222";
    readonly fontFamily: "Arial";
    readonly fontSize: 10;
    readonly textAnchor: "middle";
};
export default function AxisTop<Scale extends AxisScale>({ axisClassName, labelOffset, tickLength, tickLabelProps, ...restProps }: AxisTopProps<Scale>): import("react").JSX.Element;
