// Generated by scripts/generate-tsrx-types.mjs.
import type { TicksRendererProps, AxisScale } from '../types';
export default function Ticks<Scale extends AxisScale>({ hideTicks, horizontal, orientation, tickClassName, tickComponent, tickLabelProps: allTickLabelProps, tickStroke, tickTransform, ticks, strokeWidth, tickLineProps, }: TicksRendererProps<Scale>): import("react").JSX.Element[];
