// Generated by scripts/generate-tsrx-types.mjs.
import type { Octane } from 'octane/jsx-runtime';
import type { LineSubjectProps } from '@octanejs/visx/annotation';
export type AnnotationLineSubjectProps = Omit<LineSubjectProps, 'min' | 'max'> & {
    min?: number;
    max?: number;
};
/** AnnotationLineSubject which provides color and dimensions from context. */
export default function AnnotationLineSubject({ min, max, ...props }: AnnotationLineSubjectProps & Omit<Octane.SVGProps<SVGLineElement>, keyof AnnotationLineSubjectProps>): import("react").JSX.Element;
