// Generated by scripts/generate-tsrx-types.mjs.
import type { CircleSubjectProps } from '@octanejs/visx/annotation';
export type AnnotationSubjectCircleProps = CircleSubjectProps;
/** AnnotationSubjectCircle which provides color from theme. */
export default function AnnotationCircleSubject(props: AnnotationSubjectCircleProps): import("react").JSX.Element;
