// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BaseAnnotationProps } from './private/BaseAnnotation.tsrx';
export type AnnotationProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = {
    editable?: boolean;
} & Omit<BaseAnnotationProps<XScale, YScale, Datum>, 'AnnotationComponent'>;
export default function Annotation<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ editable, ...props }: AnnotationProps<XScale, YScale, Datum>): import("react").JSX.Element;
