// Generated by scripts/generate-tsrx-types.mjs.
import type { LabelProps as BaseLabelProps } from '@octanejs/visx/annotation';
export type AnnotationLabelProps = BaseLabelProps;
/** AnnotationLabel which provides text styles from theme. */
export default function AnnotationLabel(props: AnnotationLabelProps): import("react").JSX.Element;
