// Generated by scripts/generate-tsrx-types.mjs.
import type { ConnectorProps as BaseConnectorProps } from '@octanejs/visx/annotation';
export type AnnotationConnectorProps = BaseConnectorProps;
/** AnnotationConnector which provides color from theme. */
export default function AnnotationConnector(props: AnnotationConnectorProps): import("react").JSX.Element;
