// Adapted from react-hook-form@7.88.0 src/types/events.ts for Octane.
export type EventType =
	| 'focus'
	| 'blur'
	| 'change'
	| 'changeText'
	| 'valueChange'
	| 'contentSizeChange'
	| 'endEditing'
	| 'keyPress'
	| 'submitEditing'
	| 'layout'
	| 'selectionChange'
	| 'longPress'
	| 'press'
	| 'pressIn'
	| 'pressOut'
	| 'momentumScrollBegin'
	| 'momentumScrollEnd'
	| 'scroll'
	| 'scrollBeginDrag'
	| 'scrollEndDrag'
	| 'load'
	| 'error'
	| 'progress'
	| 'custom';
