// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
export interface TableCopyDropdownProps {
    children?: OctaneNode;
    className?: string;
    onCopy?: (format: 'csv' | 'tsv' | 'md') => void;
    onError?: (error: Error) => void;
    timeout?: number;
}
export declare const TableCopyDropdown: ({ children, className, onCopy, onError, timeout, }: TableCopyDropdownProps) => import("octane/jsx-runtime").Octane.JSX.Element;
