// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
export interface TableDownloadButtonProps {
    children?: OctaneNode;
    className?: string;
    filename?: string;
    format?: 'csv' | 'markdown';
    onDownload?: () => void;
    onError?: (error: Error) => void;
}
export declare const TableDownloadButton: ({ children, className, onDownload, onError, format, filename, }: TableDownloadButtonProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export interface TableDownloadDropdownProps {
    children?: OctaneNode;
    className?: string;
    onDownload?: (format: 'csv' | 'markdown') => void;
    onError?: (error: Error) => void;
}
export declare const TableDownloadDropdown: ({ children, className, onDownload, onError, }: TableDownloadDropdownProps) => import("octane/jsx-runtime").Octane.JSX.Element;
