// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
interface TableFullscreenButtonProps {
    children: OctaneNode;
    className?: string;
    showCopy?: boolean;
    showDownload?: boolean;
}
export declare const TableFullscreenButton: ({ children, className, showCopy, showDownload, }: TableFullscreenButtonProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
