// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentProps } from '../types';
type TableProps = ComponentProps<'table'> & {
    showControls?: boolean;
    showCopy?: boolean;
    showDownload?: boolean;
    showFullscreen?: boolean;
};
export declare const Table: ({ children, className, showControls, showCopy, showDownload, showFullscreen, ...props }: TableProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
