// Generated by scripts/generate-tsrx-types.mjs.
export type MarginShape = {
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
};
export type RequiredMarginShape = Required<MarginShape>;
export type UseChartDimensionsOptions = {
    /** Outer SVG width. */
    width?: number;
    /** Outer SVG height. */
    height?: number;
    /** Margins reserved around the drawable chart area. */
    margin?: MarginShape;
};
export type ChartDimensions = {
    width: number;
    height: number;
    margin: RequiredMarginShape;
    innerWidth: number;
    innerHeight: number;
    /** Alias for innerWidth, matching common visx example naming. */
    xMax: number;
    /** Alias for innerHeight, matching common visx example naming. */
    yMax: number;
};
export default function useChartDimensions({ width, height, margin }?: UseChartDimensionsOptions): ChartDimensions;
