// Generated by scripts/generate-tsrx-types.mjs.
import type { HighlightResult } from '../plugin-types';
import type { ComponentProps } from '../types';
type CodeBlockBodyProps = ComponentProps<'div'> & {
    result: HighlightResult;
    language: string;
    startLine?: number;
    /** Show line numbers in code blocks. @default true */
    lineNumbers?: boolean;
};
export declare const CodeBlockBody: (({ children, result, language, className, startLine, lineNumbers, ...rest }: CodeBlockBodyProps) => import("octane/jsx-runtime").JSX.Element) & {
    readonly type: ({ children, result, language, className, startLine, lineNumbers, ...rest }: CodeBlockBodyProps) => import("octane/jsx-runtime").JSX.Element;
    displayName?: string;
};
export {};
