// Generated by scripts/generate-tsrx-types.mjs.
import type { HighlightResult } from '../plugin-types';
import type { ComponentProps } from '../types';
type CodeBlockBodyProps = ComponentProps<'div'> & {
    result: HighlightResult;
    language: string;
    startLine?: number;
    /** Show line numbers in code blocks. @default true */
    lineNumbers?: boolean;
};
export declare const CodeBlockBody: import("octane").ComponentBody<CodeBlockBodyProps, any>;
export {};
