// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentProps, CSSProperties } from '../types';
type CodeBlockContainerProps = Omit<ComponentProps<'div'>, 'style'> & {
    language: string;
    style?: CSSProperties;
    /** Whether the code block is still being streamed (incomplete) */
    isIncomplete?: boolean;
};
export declare const CodeBlockContainer: ({ className, language, style, isIncomplete, ...props }: CodeBlockContainerProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
