// Generated by scripts/generate-tsrx-types.mjs.
interface CodeBlockContextType {
    code: string;
}
export declare const CodeBlockContext: import("octane").Context<CodeBlockContextType>;
export declare const useCodeBlockContext: () => CodeBlockContextType;
export {};
