// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentProps } from '../types';
export type CodeBlockCopyButtonProps = ComponentProps<'button'> & {
    onCopy?: () => void;
    onError?: (error: Error) => void;
    timeout?: number;
};
export declare const CodeBlockCopyButton: ({ onCopy, onError, timeout, children, className, code: propCode, ...props }: CodeBlockCopyButtonProps & {
    code?: string;
}) => import("octane/jsx-runtime").Octane.JSX.Element;
