// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentProps } from '../types';
export type CodeBlockDownloadButtonProps = ComponentProps<'button'> & {
    onDownload?: () => void;
    onError?: (error: Error) => void;
};
export declare const CodeBlockDownloadButton: ({ onDownload, onError, language, children, className, code: propCode, ...props }: CodeBlockDownloadButtonProps & {
    code?: string;
    language?: string;
}) => import("octane/jsx-runtime").Octane.JSX.Element;
