// Generated by scripts/generate-tsrx-types.mjs.
interface CodeBlockHeaderProps {
    language: string;
}
export declare const CodeBlockHeader: ({ language }: CodeBlockHeaderProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
