// Generated by scripts/generate-tsrx-types.mjs.
import type { HighlightResult } from '../plugin-types';
import type { HTMLAttributes } from '../types';
type HighlightedCodeBlockBodyProps = HTMLAttributes<HTMLDivElement> & {
    code: string;
    language: string;
    raw: HighlightResult;
    startLine?: number;
    lineNumbers?: boolean;
};
export declare const HighlightedCodeBlockBody: ({ code, language, raw, className, startLine, lineNumbers, ...rest }: HighlightedCodeBlockBodyProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
