// Generated by scripts/generate-tsrx-types.mjs.
import type { HTMLAttributes } from '../types';
type CodeBlockProps = HTMLAttributes<HTMLDivElement> & {
    code: string;
    language: string;
    /** Whether the code block is still being streamed (incomplete) */
    isIncomplete?: boolean;
    /** Custom starting line number for line numbering (default: 1) */
    startLine?: number;
    /** Show line numbers in code blocks. @default true */
    lineNumbers?: boolean;
};
export declare const CodeBlock: ({ code, language, className, children, isIncomplete, startLine, lineNumbers, ...rest }: CodeBlockProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
