// Generated by scripts/generate-tsrx-types.mjs.
import type { FC } from 'react';
import type { AnnotationProps, EditableAnnotationProps } from '@octanejs/visx/annotation';
import type { ScaleInput } from '@octanejs/visx/scale';
import type { AxisScale } from '@octanejs/visx/axis';
export type BaseAnnotationProps<XScale extends AxisScale, YScale extends AxisScale, Datum extends object> = Pick<EditableAnnotationProps, 'canEditLabel' | 'canEditSubject' | 'children' | 'dx' | 'dy' | 'onDragEnd' | 'onDragMove' | 'onDragStart'> & {
    /** Annotation component to render. */
    AnnotationComponent: FC<AnnotationProps> | FC<EditableAnnotationProps>;
    /** Key for series to which datum belongs (used for x/yAccessors). Alternatively xAccessor + yAccessor may be specified. */
    dataKey?: string;
    /** Datum to annotate, used for Annotation positioning. */
    datum: Datum;
    /** If dataKey is not specified, you must specify an xAccessor for datum. */
    xAccessor?: (d: Datum) => ScaleInput<XScale>;
    /** If dataKey is not specified, you must specify an yAccessor for datum. */
    yAccessor?: (d: Datum) => ScaleInput<YScale>;
};
export default function BaseAnnotation<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ AnnotationComponent, children, datum, dataKey, xAccessor: propsXAccessor, yAccessor: propsYAccessor, dx: propsDx, dy: propsDy, ...annotationProps }: BaseAnnotationProps<XScale, YScale, Datum>): import("react").JSX.Element | null;
