// Generated by scripts/generate-tsrx-types.mjs.
export type NodeProps = {
    node: {
        x0: number;
        x1: number;
        y0: number;
        y1: number;
    };
};
export default function HierarchyDefaultRectNode({ node: { x0, x1, y0, y1 } }: NodeProps): import("react").JSX.Element;
