// Generated by scripts/generate-tsrx-types.mjs.
type Node = {
    x: number;
    y: number;
};
export type LinkProps = {
    link?: {
        source: Node;
        target: Node;
    };
};
export default function HierarchyDefaultLink({ link }: LinkProps): import("react").JSX.Element;
export {};
