// Generated by scripts/generate-tsrx-types.mjs.
export type NodeProps = {
    node?: {
        x: number;
        y: number;
        r?: number;
    };
};
export default function HierarchyDefaultNode({ node }: NodeProps): import("react").JSX.Element;
