// Generated by scripts/generate-tsrx-types.mjs.
export type TooltipPositionContextType = {
    isFlippedVertically: boolean;
    isFlippedHorizontally: boolean;
};
export declare const TooltipPositionProvider: import("octane").ComponentBody<{
    value: TooltipPositionContextType;
    children?: any;
}, any>;
export declare const TooltipPositionConsumer: any;
export declare const useTooltipPosition: () => TooltipPositionContextType;
