// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
import type { OctaneNode } from 'octane';
export type PolygonProps = {
    /** Override render function which is provided polygon and generated path. */
    children?: ({ path, polygon, }: {
        path: string;
        polygon: [number, number][];
    }) => OctaneNode;
    /** className to apply to path element. */
    className?: string;
    /** Array of coordinate arrays for the polygon (e.g., [[x,y], [x1,y1], ...]), used to generate polygon path. */
    polygon?: [number, number][];
};
export default function Polygon({ polygon, className, children, ...restProps }: PolygonProps & Omit<SVGProps<SVGPathElement>, keyof PolygonProps>): import("react").JSX.Element | null;
