// Generated by scripts/generate-tsrx-types.mjs.
import type { ThemeScopeProps } from '../provider/ThemeScope.tsrx';
export type ThemeProviderProps = ThemeScopeProps;
export default function ThemeProvider(props: ThemeProviderProps): import("react").JSX.Element;
