// Generated by scripts/generate-tsrx-types.mjs.
import type { VisxThemeRuntime } from '../tokens/types';
declare const ThemeContext: import("octane").Context<VisxThemeRuntime>;
export default ThemeContext;
