// Generated by scripts/generate-tsrx-types.mjs.
export type AxisOrientation = 'top' | 'right' | 'bottom' | 'left';
export type AxisTextAnchor = 'start' | 'middle' | 'end';
export type AxisVerticalAnchor = 'start' | 'middle' | 'end';
export type AxisTextStyleProps = {
    dx?: string | number;
    dy?: string | number;
    fill: string;
    fontFamily: string;
    fontSize: number;
    textAnchor: AxisTextAnchor;
    verticalAnchor?: AxisVerticalAnchor;
};
export type AxisStyleProps = {
    labelOffset?: number;
    stroke: string;
    strokeWidth: number;
    tickLength: number;
    tickStroke: string;
    tickLabelProps: AxisTextStyleProps;
    labelProps: AxisTextStyleProps;
};
export default function useAxisStyle(orientation: AxisOrientation): AxisStyleProps;
