// Generated by scripts/generate-tsrx-types.mjs.
import type { ChartConfig, ChartSeriesConfig } from '../tokens/types';
export type ResolvedSeries<K extends string = string> = ChartSeriesConfig & {
    key: K;
    color: string;
};
export type UseChartConfigOptions<K extends string = string> = {
    order?: readonly K[];
};
export type UseChartConfigResult<K extends string = string> = {
    series: ResolvedSeries<K>[];
    getColor: (key: K) => string;
    getLabel: (key: K) => string;
};
export default function useChartConfig<K extends string>(config: ChartConfig<K>, options?: UseChartConfigOptions<K>): UseChartConfigResult<K>;
