// Generated by scripts/generate-tsrx-types.mjs.
export type CategoricalColorAccessor<Domain extends readonly string[]> = (key: Domain[number]) => string;
export default function useCategoricalScale<Domain extends readonly string[]>(domain: Domain): CategoricalColorAccessor<Domain>;
