// Generated by scripts/generate-tsrx-types.mjs.
export type ColorScaleAccessor<Domain extends readonly string[]> = (key: Domain[number]) => string;
export type UseColorScaleOptions = {
    /** Optional explicit color range. Falls back to the active theme's categorical palette. */
    range?: readonly string[];
};
export default function useColorScale<Domain extends readonly string[]>(domain: Domain, { range }?: UseColorScaleOptions): ColorScaleAccessor<Domain>;
