// Generated by scripts/generate-tsrx-types.mjs.
import type { VisxThemeRuntime } from '../tokens/types';
export type ColorTokenName = Exclude<keyof VisxThemeRuntime['colors'], 'categorical'>;
export default function useColor(color: ColorTokenName | number): string;
