// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactNode } from 'react';
import type { AnnotationContextType } from '../types';
export type AnnotationProps = Pick<AnnotationContextType, 'x' | 'y' | 'dx' | 'dy'> & {
    /** Annotation children (Subject, Label, Connector) */
    children: ReactNode;
};
export default function Annotation({ x, y, dx, dy, children }: AnnotationProps): import("react").JSX.Element;
