// Generated by scripts/generate-tsrx-types.mjs.
import type { CSSProperties } from 'react';
import type { OctaneNode } from 'octane';
import type { LabelProps } from './Label.tsrx';
export type HtmlLabelProps = Pick<LabelProps, 'anchorLineStroke' | 'className' | 'horizontalAnchor' | 'resizeObserverPolyfill' | 'showAnchorLine' | 'verticalAnchor' | 'x' | 'y'> & {
    /** Pass in a custom element as the label to style as you like. Renders inside a <foreignObject>, be aware that most non-browser SVG renderers will not render HTML <foreignObject>s. See: https://github.com/airbnb/visx/issues/1173#issuecomment-1014380545.  */
    children?: OctaneNode;
    /** Optional styles to apply to the HTML container. */
    containerStyle?: CSSProperties;
};
export default function HtmlLabel({ anchorLineStroke, children, className, containerStyle, horizontalAnchor: propsHorizontalAnchor, showAnchorLine, verticalAnchor: propsVerticalAnchor, x: propsX, y: propsY, }: HtmlLabelProps): import("react").JSX.Element;
