// Generated by scripts/generate-tsrx-types.mjs.
import type { TextProps } from '@octanejs/visx/text';
interface AnchorLineProps {
    anchorLineOrientation: 'horizontal' | 'vertical';
    verticalAnchor: TextProps['verticalAnchor'];
    horizontalAnchor: TextProps['textAnchor'];
    anchorLineStroke: string;
    width: number;
    height: number;
}
export default function AnchorLine({ anchorLineOrientation, anchorLineStroke, verticalAnchor, horizontalAnchor, width, height, }: AnchorLineProps): import("react").JSX.Element;
export {};
