// Generated by scripts/generate-tsrx-types.mjs.
import type { ProjectionProps } from './Projection.tsrx';
import type { GeoPermissibleObjects } from '../types';
/**
 * All props pass through to `<Projection projection={customProjection} {...props} />`
 */
export default function CustomProjection<Datum extends GeoPermissibleObjects>(props: ProjectionProps<Datum>): import("react").JSX.Element;
