// Vendored from react-router@8.2.0 packages/react-router/lib/types/future.ts — unmodified.
// Re-vendor with `node scripts/vendor-remix-router.mjs`; never hand-edit.
/**
 * An augmentable interface users can modify in their app-code to opt into
 * future-flag-specific types
 */
export interface Future {
	// We list the potential fields here in comments strictly for clarity.
	// They will be generated by the react-router/dev/typegen/generate.ts module
}
