// Generated by scripts/generate-tsrx-types.mjs.
import type { Ref } from 'react';
import type { OctaneNode } from 'octane';
export type ScaleSVGProps = {
    /** Child SVG to scale, rendered as the child of the parent wrappers provided by this component `<div><svg>{children}</svg></div>`. */
    children?: OctaneNode;
    /** Width of the desired SVG. */
    width?: number | string;
    /** Height of the desired SVG. */
    height?: number | string;
    /** xOrigin of the desired SVG. */
    xOrigin?: number | string;
    /** yOrigin of the desired SVG. */
    yOrigin?: number | string;
    /** Whether to preserve SVG aspect ratio. */
    preserveAspectRatio?: string;
    /** Ref to the parent `<svg />` used for scaling. */
    innerRef?: Ref<SVGSVGElement>;
};
export default function ScaleSVG({ children, width, height, xOrigin, yOrigin, preserveAspectRatio, innerRef, }: ScaleSVGProps): import("react").JSX.Element;
