// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
import type { OctaneNode } from 'octane';
import type { Symbol } from 'd3-shape';
export type GlyphWyeProps<Datum> = {
    /** Render function override which is passed the configured path generator. */
    children?: ({ path, }: {
        path: Symbol<unknown, Datum>;
    }) => OctaneNode;
    /** classname to apply to glyph path element. */
    className?: string;
    /** Top offset to apply to glyph g element container. */
    top?: number;
    /** Left offset to apply to glyph g element container. */
    left?: number;
    /** Size of wye glyph in px, or an accessor which takes Datum as input and returns a size. */
    size?: number | ((d: Datum) => number);
};
export default function GlyphWye<Datum = unknown>({ children, className, top, left, size, ...restProps }: GlyphWyeProps<Datum> & Omit<SVGProps<SVGPathElement>, keyof GlyphWyeProps<Datum>>): import("react").JSX.Element;
