// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
export type GlyphProps = {
    /** Top offset to apply to glyph g element container. */
    top?: number;
    /** Left offset to apply to glyph g element container. */
    left?: number;
    /** classname to apply to glyph g element container. */
    className?: string;
    /** Children to render. */
    children?: OctaneNode;
};
export default function Glyph({ top, left, className, children }: GlyphProps): import("react").JSX.Element;
