// Generated by scripts/generate-tsrx-types.mjs.
import type { ReactNode, SVGProps } from 'react';
import type { Symbol } from 'd3-shape';
export type GlyphTriangleProps<Datum> = {
    /** Render function override which is passed the configured path generator. */
    children?: ({ path, }: {
        path: Symbol<unknown, Datum>;
    }) => ReactNode;
    /** classname to apply to glyph path element. */
    className?: string;
    /** Top offset to apply to glyph g element container. */
    top?: number;
    /** Left offset to apply to glyph g element container. */
    left?: number;
    /** Size of triangle in px, or an accessor which takes Datum as input and returns a size. */
    size?: number | ((d: Datum) => number);
};
export default function GlyphTriangle<Datum = unknown>({ children, className, top, left, size, ...restProps }: GlyphTriangleProps<Datum> & Omit<SVGProps<SVGPathElement>, keyof GlyphTriangleProps<Datum>>): import("react").JSX.Element;
