// Generated by scripts/generate-tsrx-types.mjs.
import type { MarkerComponentProps } from './Marker.tsrx';
export default function MarkerCross({ id, size, strokeWidth, ...restProps }: MarkerComponentProps): import("react").JSX.Element;
