// Generated by scripts/generate-tsrx-types.mjs.
import type { MarkerComponentProps } from './Marker.tsrx';
export default function MarkerLine({ id, size, fill, stroke, strokeWidth, ...restProps }: MarkerComponentProps): import("react").JSX.Element;
