// Generated by scripts/generate-tsrx-types.mjs.
import type { ComponentType } from 'react';
import type { DebounceSettings, Simplify, ResizeObserverPolyfill } from '../types';
/** @deprecated @TODO remove in the next major version - exported for backwards compatibility */
export type WithParentSizeProps = DebounceSettings;
type WithParentSizeConfig = {
    initialWidth?: number;
    initialHeight?: number;
} & DebounceSettings;
type WithParentSizeState = {
    parentWidth?: number;
    parentHeight?: number;
};
export type WithParentSizeProvidedProps = WithParentSizeState;
type WithParentSizeComponentProps<P extends WithParentSizeProvidedProps> = Simplify<Omit<P, keyof WithParentSizeProvidedProps> & WithParentSizeConfig>;
export default function withParentSize<P extends WithParentSizeProvidedProps>(BaseComponent: ComponentType<P>, resizeObserverPolyfill?: ResizeObserverPolyfill): ComponentType<WithParentSizeComponentProps<P>>;
export {};
