const people = {
	avery: { name: 'Avery Stone', initials: 'AS', tone: 'violet' },
	maya: { name: 'Maya Chen', initials: 'MC', tone: 'coral' },
	kai: { name: 'Kai Bell', initials: 'KB', tone: 'mint' },
	lena: { name: 'Lena Ortiz', initials: 'LO', tone: 'gold' },
	rowan: { name: 'Rowan Ellis', initials: 'RE', tone: 'blue' },
};

function message(id, channel, author, body, sentAt, order, reactions = 0, threadCount = 0) {
	return { id, channel, author: people[author], body, sentAt, order, reactions, threadCount };
}

export const channelMessages = {
	general: [
		message(
			'g-001',
			'general',
			'rowan',
			'Morning! The customer notes from Berlin are in the research folder.',
			'Mon 8:42',
			1,
			3,
		),
		message(
			'g-002',
			'general',
			'maya',
			'Thank you. I’ll fold the onboarding themes into today’s review.',
			'Mon 8:47',
			2,
			2,
		),
		message(
			'g-003',
			'general',
			'kai',
			'The accessibility pass is green on keyboard and reduced motion.',
			'Mon 9:06',
			3,
			6,
		),
		message(
			'g-004',
			'general',
			'lena',
			'I added the support-volume baseline to the launch brief.',
			'Mon 9:18',
			4,
			1,
		),
		message(
			'g-005',
			'general',
			'avery',
			'Nice. Let’s keep the decision log beside the brief so context stays close.',
			'Mon 9:24',
			5,
			5,
		),
		message(
			'g-006',
			'general',
			'maya',
			'First critique is at 11:00. Bring one question, not a polished solution.',
			'Mon 10:02',
			6,
			8,
		),
		message(
			'g-007',
			'general',
			'rowan',
			'I can take notes and tag the open research questions.',
			'Mon 10:11',
			7,
			2,
		),
		message(
			'g-008',
			'general',
			'kai',
			'Preview environment is refreshed with the new navigation labels.',
			'Mon 10:35',
			8,
			4,
		),
		message(
			'g-009',
			'general',
			'lena',
			'Support macros are ready for a final wording check.',
			'Mon 11:14',
			9,
			1,
		),
		message(
			'g-010',
			'general',
			'avery',
			'The pilot group is confirmed for Thursday afternoon.',
			'Mon 12:03',
			10,
			7,
		),
		message(
			'g-011',
			'general',
			'maya',
			'Sharing the critique summary now: direction B is clearer under pressure.',
			'Today 9:04',
			11,
			9,
		),
		message(
			'g-012',
			'general',
			'kai',
			'I’ll pair with Rowan on the motion details after stand-up.',
			'Today 9:12',
			12,
			3,
		),
		message(
			'g-013',
			'general',
			'lena',
			'Two customers volunteered for the workflow follow-up next week.',
			'Today 9:19',
			13,
			5,
		),
		message(
			'g-014',
			'general',
			'rowan',
			'The handoff checklist now includes ownership, rollback, and a success signal.',
			'Today 9:27',
			14,
			12,
			3,
		),
		message(
			'g-015',
			'general',
			'avery',
			'That checklist is excellent. Please pin it in the launch channel too.',
			'Today 9:31',
			15,
			6,
		),
		message(
			'g-016',
			'general',
			'maya',
			'Research readout is recorded; the three-minute summary is at the top.',
			'Today 9:44',
			16,
			7,
		),
		message(
			'g-017',
			'general',
			'kai',
			'Build 218 is ready. No regressions in the keyboard smoke test.',
			'Today 9:52',
			17,
			10,
		),
		message(
			'g-018',
			'general',
			'lena',
			'I’m drafting the customer note and will share it before lunch.',
			'Today 10:03',
			18,
			4,
		),
	],
	design: [
		message(
			'd-001',
			'design',
			'maya',
			'Starting a thread for the activation map.',
			'Yesterday 14:08',
			1,
			4,
		),
		message(
			'd-002',
			'design',
			'rowan',
			'The quiet state needs one clear next action and less explanatory copy.',
			'Yesterday 14:22',
			2,
			7,
		),
		message(
			'd-003',
			'design',
			'avery',
			'Agreed. Could the example sit beside the empty canvas?',
			'Yesterday 14:31',
			3,
			2,
		),
		message(
			'd-004',
			'design',
			'kai',
			'I tested that layout at 320px; the action remains above the fold.',
			'Yesterday 15:04',
			4,
			8,
		),
		message(
			'd-005',
			'design',
			'lena',
			'Customer language favors “start a space” over “create workspace.”',
			'Yesterday 15:17',
			5,
			5,
		),
		message(
			'd-006',
			'design',
			'maya',
			'I pushed the copy update and a higher-contrast focus treatment.',
			'Today 8:36',
			6,
			11,
		),
		message(
			'd-007',
			'design',
			'rowan',
			'The prototype is ready for the 2pm critique.',
			'Today 9:18',
			7,
			3,
		),
		message(
			'd-008',
			'design',
			'avery',
			'I’ll bring the activation metrics so we can make the tradeoff explicit.',
			'Today 9:39',
			8,
			6,
		),
	],
	random: [],
};

export const threadReplies = {
	'g-014': [
		{
			id: 'r-1',
			author: people.maya,
			body: 'Adding a named owner made the biggest difference in yesterday’s rehearsal.',
			sentAt: 'Today 9:29',
		},
		{
			id: 'r-2',
			author: people.kai,
			body: 'I linked the rollback dashboard directly from the checklist.',
			sentAt: 'Today 9:30',
		},
		{
			id: 'r-3',
			author: people.rowan,
			body: 'Perfect — I’ll keep the template current after each release.',
			sentAt: 'Today 9:32',
		},
	],
};

export { people };
