// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
export type PatternProps = {
    /** Unique id of the pattern element. */
    id?: string;
    /** Width of the pattern. */
    width: number;
    /** Height of the pattern. */
    height: number;
    /** Children of pattern element to render. */
    children: OctaneNode;
};
export default function Pattern({ id, width, height, children }: PatternProps): import("react").JSX.Element;
