// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
import type { OctaneNode } from 'octane';
import type { PickD3Scale, ContinuousDomainScaleType } from '@octanejs/visx/scale';
import type { SharedProps } from './types';
export type ViolinPlotProps<Datum extends object> = SharedProps & {
    /** Scale for converting values to pixel offsets. */
    valueScale: PickD3Scale<ContinuousDomainScaleType, number>;
    /** Data used to draw the violin plot glyph. Violin plot values and counts should be able to be derived from data. */
    data: Datum[];
    /** Given an datum, returns the count for it. */
    count?: (d: Datum) => number;
    /** Given an datum, returns the value for it. */
    value?: (d: Datum) => number;
    /** Width of the violin plot glyph. */
    width?: number;
    /** Override render function to fully control the rendering of the ViolinPlot glyph. */
    children?: (providedProps: {
        path: string;
    }) => OctaneNode;
};
export default function ViolinPlot<Datum extends object>({ left, top, className, data, width, count, value, valueScale, horizontal, children, ...restProps }: ViolinPlotProps<Datum> & Omit<SVGProps<SVGPathElement>, keyof ViolinPlotProps<Datum>>): import("react").JSX.Element;
