// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
import type { OctaneNode } from 'octane';
export type ClipPathProps = {
    /** Unique id for the clipPath. */
    id?: string;
    /** clipPath children. */
    children?: OctaneNode;
};
/** Handles rendering of <defs> and <clipPath> elements for you, with any children you want. */
export default function ClipPath({ id, children, ...restProps }: ClipPathProps & Omit<SVGProps<SVGClipPathElement>, keyof ClipPathProps>): import("react").JSX.Element;
