// Generated by scripts/generate-tsrx-types.mjs.
import type { SVGProps } from 'react';
export type RectClipPathProps = {
    /** Unique id for the clipPath. */
    id?: string;
    /** x position of the ClipPath rect. */
    x?: string | number;
    /** y position of the ClipPath rect. */
    y?: string | number;
    /** width of the ClipPath rect. */
    width?: string | number;
    /** height of the ClipPath rect. */
    height?: string | number;
};
export default function RectClipPath({ id, x, y, width, height, ...restProps }: RectClipPathProps & Omit<SVGProps<SVGRectElement>, keyof RectClipPathProps>): import("react").JSX.Element;
