// Generated by scripts/generate-tsrx-types.mjs.
import type { PositionScale } from '@octanejs/visx/shape';
import type { BaseBarGroupProps } from './private/BaseBarGroup.tsrx';
export default function AnimatedBarGroup<XScale extends PositionScale, YScale extends PositionScale, Datum extends object>(props: Omit<BaseBarGroupProps<XScale, YScale, Datum>, 'BarsComponent'>): import("react").JSX.Element;
