// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { FC } from 'react';
import type { GlyphProps } from '../../types';
import type { BaseGlyphSeriesProps } from './private/BaseGlyphSeries.tsrx';
export default function AnimatedGlyphSeries<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ renderGlyph, ...props }: Omit<BaseGlyphSeriesProps<XScale, YScale, Datum>, 'renderGlyphs'> & {
    renderGlyph?: FC<GlyphProps<Datum>>;
}): import("react").JSX.Element;
