// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BaseAreaSeriesProps } from './private/BaseAreaSeries.tsrx';
export default function AnimatedAreaSeries<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(props: Omit<BaseAreaSeriesProps<XScale, YScale, Datum>, 'PathComponent'>): import("react").JSX.Element;
