// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BaseBarSeriesProps } from './private/BaseBarSeries.tsrx';
export default function AnimatedBarSeries<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ colorAccessor, ...props }: Omit<BaseBarSeriesProps<XScale, YScale, Datum>, 'BarsComponent'>): import("react").JSX.Element;
