// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { BaseAreaStackProps } from './private/BaseAreaStack.tsrx';
export default function AreaStack<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>(props: Omit<BaseAreaStackProps<XScale, YScale, Datum>, 'PathComponent'>): import("react").JSX.Element;
