// Generated by scripts/generate-tsrx-types.mjs.
import type { PositionScale } from '@octanejs/visx/shape';
import type { BaseBarStackProps } from './private/BaseBarStack.tsrx';
export default function BarStack<XScale extends PositionScale, YScale extends PositionScale, Datum extends object>(props: Omit<BaseBarStackProps<XScale, YScale, Datum>, 'BarsComponent'>): import("react").JSX.Element;
