// Generated by scripts/generate-tsrx-types.mjs.
import type { AxisScale } from '@octanejs/visx/axis';
import type { OctaneNode } from 'octane';
import type { GlyphProps } from '../../types';
import type { BaseGlyphSeriesProps } from './private/BaseGlyphSeries.tsrx';
export default function GlyphSeries<XScale extends AxisScale, YScale extends AxisScale, Datum extends object>({ renderGlyph, ...props }: Omit<BaseGlyphSeriesProps<XScale, YScale, Datum>, 'renderGlyphs'> & {
    renderGlyph?: (props: GlyphProps<Datum>) => OctaneNode;
}): import("react").JSX.Element;
