import {
	INFINITE_PREFIX,
	SWRConfig,
	cache,
	createCacheHelper,
	initCache,
	mergeConfigs,
	serialize,
	stableHash,
	type Arguments,
	type BareFetcher,
	type BlockingData,
	type Broadcaster,
	type Cache,
	type Fetcher,
	type FetcherResponse,
	type FullConfiguration,
	type GlobalState,
	type InternalConfiguration,
	type IsLoadingResponse,
	type Key,
	type KeyedMutator,
	type KeyLoader,
	type Middleware,
	type Mutator,
	type MutatorCallback,
	type MutatorConfig,
	type MutatorFn,
	type MutatorOptions,
	type MutatorWrapper,
	type ProviderConfiguration,
	type PublicConfiguration,
	type RevalidateCallback,
	type RevalidateEvent,
	type Revalidator,
	type RevalidatorOptions,
	type ScopedMutator,
	type State,
	type StateDependencies,
	type StrictTupleKey,
	type SWRConfiguration,
	type SWRHook,
	type SWRResponse,
} from '../../src/_internal/index.js';

type InternalTypes = [
	Arguments,
	BareFetcher,
	BlockingData,
	Broadcaster,
	Cache,
	Fetcher,
	FetcherResponse,
	FullConfiguration,
	GlobalState,
	InternalConfiguration,
	IsLoadingResponse,
	Key,
	KeyedMutator<unknown>,
	KeyLoader,
	Middleware,
	Mutator,
	MutatorCallback,
	MutatorConfig,
	MutatorFn,
	MutatorOptions,
	MutatorWrapper<unknown>,
	ProviderConfiguration,
	PublicConfiguration,
	RevalidateCallback,
	RevalidateEvent,
	Revalidator,
	RevalidatorOptions,
	ScopedMutator,
	State,
	StateDependencies,
	StrictTupleKey,
	SWRConfiguration,
	SWRHook,
	SWRResponse,
];

const runtime = [
	INFINITE_PREFIX,
	SWRConfig,
	cache,
	createCacheHelper,
	initCache,
	mergeConfigs,
	serialize,
	stableHash,
];
declare const types: InternalTypes;
void [runtime, types];
