// Generated by scripts/generate-tsrx-types.mjs.
import type { MermaidConfig } from 'mermaid';
import type { OctaneNode } from 'octane';
interface MermaidDownloadDropdownProps {
    chart: string;
    children?: OctaneNode;
    className?: string;
    config?: MermaidConfig;
    onDownload?: (format: 'mmd' | 'png' | 'svg') => void;
    onError?: (error: Error) => void;
}
export declare const MermaidDownloadDropdown: ({ chart, children, className, onDownload, config, onError, }: MermaidDownloadDropdownProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
