// Generated by scripts/generate-tsrx-types.mjs.
import type { MermaidConfig } from 'mermaid';
import type { ComponentProps } from '../types';
type MermaidFullscreenButtonProps = ComponentProps<'button'> & {
    chart: string;
    config?: MermaidConfig;
    onFullscreen?: () => void;
    onExit?: () => void;
};
export declare const MermaidFullscreenButton: ({ chart, config, onFullscreen, onExit, className, ...props }: MermaidFullscreenButtonProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
