// Generated by scripts/generate-tsrx-types.mjs.
import type { MermaidConfig } from 'mermaid';
interface MermaidProps {
    chart: string;
    className?: string;
    config?: MermaidConfig;
    fullscreen?: boolean;
    showControls?: boolean;
}
export declare const Mermaid: ({ chart, className, config, fullscreen, showControls, }: MermaidProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
