// Generated by scripts/generate-tsrx-types.mjs.
import type { OctaneNode } from 'octane';
interface PanZoomProps {
    children: OctaneNode;
    className?: string;
    fullscreen?: boolean;
    initialZoom?: number;
    maxZoom?: number;
    minZoom?: number;
    showControls?: boolean;
    zoomStep?: number;
}
export declare const PanZoom: ({ children, className, minZoom, maxZoom, zoomStep, showControls, initialZoom, fullscreen, }: PanZoomProps) => import("octane/jsx-runtime").Octane.JSX.Element;
export {};
