// @ts-check
/**
 * Vercel Build Output API v3 emitter.
 *
 * Restructures an octane production build (`dist/client` + `dist/server`,
 * produced by @octanejs/vite-plugin) into `.vercel/output/`:
 *
 *   static/               ← dist/client verbatim (hashed assets; the build
 *                           already moved index.html — the SSR template —
 *                           to dist/server, so nothing shadows SSR at '/')
 *   functions/index.func/ ← dist/server verbatim + a generated index.js that
 *                           wraps the entry's fetch `handler` in Vercel's
 *                           Web-Standard function shape
 *   config.json           ← routing: immutable asset headers → filesystem →
 *                           catch-all to the function
 *
 * Modeled on @ripple-ts/adapter-vercel (itself after @sveltejs/adapter-vercel),
 * with one octane simplification: the server entry is SELF-CONTAINED (the
 * plugin bundles the app + octane with `ssr.noExternal: true`), so there is no
 * dependency tracing — the function is dist/server plus one wrapper file.
 */

/** @import { VercelAdapterOptions, VercelConfig, VercelRoute } from '@octanejs/adapter-vercel' */
/** @import { AdaptContext } from '@octanejs/vite-plugin' */

import { existsSync, mkdirSync, cpSync, writeFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { createRequire } from 'node:module';

const VERCEL_OUTPUT_DIR = '.vercel/output';
const VALID_NODE_MAJORS = [22, 24];
const VALID_NODE_RUNTIMES = new Set(VALID_NODE_MAJORS.map((major) => `nodejs${major}.x`));

/**
 * The adapter's own version (for .vc-config.json `framework`). MUST stay lazy:
 * octane.config.ts is compiled into the server bundle, so this module's scope
 * executes when the deployed function boots — where `../package.json` does not
 * exist. adapt() itself only ever runs at build time from the real package.
 * @returns {string}
 */
function get_adapter_version() {
	try {
		const require = createRequire(import.meta.url);
		return require('../package.json').version;
	} catch {
		return '0.0.0';
	}
}

/**
 * Default Node.js runtime for the function, from the build machine's major.
 * @returns {string}
 */
function get_default_runtime() {
	const major = Number(process.version.slice(1).split('.')[0]);
	if (!VALID_NODE_MAJORS.includes(major)) {
		throw new Error(
			`[@octanejs/adapter-vercel] Unsupported Node.js version: ${process.version}. ` +
				`Build with Node ${VALID_NODE_MAJORS.join('/')} or set serverless.runtime to ` +
				'nodejs22.x/nodejs24.x explicitly.',
		);
	}
	return `nodejs${major}.x`;
}

/**
 * Reject deployment runtimes outside Octane's supported Node.js baseline.
 * An explicit runtime still lets a newer build machine target Node 22 or 24.
 * @param {string} runtime
 * @returns {string}
 */
function validate_runtime(runtime) {
	if (!VALID_NODE_RUNTIMES.has(runtime)) {
		throw new Error(
			`[@octanejs/adapter-vercel] Unsupported serverless runtime: ${runtime}. ` +
				'Use nodejs22.x or nodejs24.x.',
		);
	}
	return runtime;
}

/**
 * @param {string} file_path
 * @param {string} data
 */
function write(file_path, data) {
	mkdirSync(dirname(file_path), { recursive: true });
	writeFileSync(file_path, data);
}

/**
 * The serverless function entry: Vercel's Web-Standard shape
 * (`export default { fetch(Request) => Response }`) over the built handler.
 * @returns {string}
 */
function generate_handler_source() {
	return `// Auto-generated by @octanejs/adapter-vercel — the Vercel function entry.
// The imported handler is the self-contained octane SSR bundle's fetch handler.
import { handler } from './entry.js';

export default {
	async fetch(request) {
		try {
			return await handler(request);
		} catch (error) {
			console.error('[octane] Serverless handler error:', error);
			return new Response('Internal Server Error', { status: 500 });
		}
	},
};
`;
}

/**
 * Build Output API v3 config.json.
 *
 * @param {VercelAdapterOptions} options
 * @returns {VercelConfig}
 */
function generate_vercel_config(options) {
	const { cleanUrls = true, trailingSlash, images, headers = [], redirects = [] } = options;

	/** @type {VercelRoute[]} */
	const routes = [];

	for (const redirect of redirects) {
		routes.push({
			src: redirect.source,
			headers: { Location: redirect.destination },
			status: redirect.permanent ? 308 : 307,
		});
	}

	// Hashed build assets are immutable by construction.
	routes.push({
		src: '/assets/.+',
		headers: { 'Cache-Control': 'public, max-age=31536000, immutable' },
		continue: true,
	});

	for (const header of headers) {
		routes.push({
			src: header.source,
			headers: Object.fromEntries(header.headers.map((h) => [h.key, h.value])),
			continue: true,
		});
	}

	// Static files win first; everything else — every page, including the
	// catch-all 404 route — is server-rendered by the function.
	routes.push({ handle: 'filesystem' });
	routes.push({ src: '/.*', dest: '/index' });

	/** @type {VercelConfig} */
	const config = { version: 3, routes };
	if (cleanUrls !== undefined) config.cleanUrls = cleanUrls;
	if (trailingSlash !== undefined) config.trailingSlash = trailingSlash;
	if (images) config.images = images;
	return config;
}

/**
 * Emit `.vercel/output` from a completed octane build.
 *
 * Callable two ways: by @octanejs/vite-plugin's closeBundle (which passes its
 * {@link AdaptContext}) or directly with explicit dirs.
 *
 * @param {AdaptContext} ctx
 * @param {VercelAdapterOptions} [options]
 * @returns {Promise<void>}
 */
export async function adapt(ctx, options = {}) {
	const { root, clientDir, serverDir } = ctx;
	const log = ctx.log ?? ((/** @type {string} */ msg) => console.log(msg));

	const server_entry = join(serverDir, 'entry.js');
	if (!existsSync(clientDir)) {
		throw new Error(`[@octanejs/adapter-vercel] Client build output not found at ${clientDir}.`);
	}
	if (!existsSync(server_entry)) {
		throw new Error(`[@octanejs/adapter-vercel] Server entry not found at ${server_entry}.`);
	}
	const runtime = validate_runtime(options.serverless?.runtime ?? get_default_runtime());

	const output_dir = join(root, VERCEL_OUTPUT_DIR);
	rmSync(output_dir, { recursive: true, force: true });
	mkdirSync(output_dir, { recursive: true });

	// 1. Static assets — dist/client verbatim (no index.html in it: the build
	//    moved the SSR template to dist/server).
	const static_dir = join(output_dir, 'static');
	mkdirSync(static_dir, { recursive: true });
	cpSync(clientDir, static_dir, { recursive: true });

	// 2. The serverless function — dist/server verbatim (self-contained entry +
	//    the SSR template + any dynamic-import chunks) plus the wrapper.
	const func_dir = join(output_dir, 'functions', 'index.func');
	mkdirSync(func_dir, { recursive: true });
	cpSync(serverDir, func_dir, { recursive: true });
	write(join(func_dir, 'index.js'), generate_handler_source());
	write(join(func_dir, 'package.json'), JSON.stringify({ type: 'module' }));

	/** @type {Record<string, unknown>} */
	const vc_config = {
		runtime,
		handler: 'index.js',
		launcherType: 'Nodejs',
		supportsResponseStreaming: true,
		framework: { slug: 'octane', version: get_adapter_version() },
	};
	if (options.serverless?.regions) vc_config.regions = options.serverless.regions;
	if (options.serverless?.memory) vc_config.memory = options.serverless.memory;
	if (options.serverless?.maxDuration) vc_config.maxDuration = options.serverless.maxDuration;

	// ISR belongs in an ADJACENT prerender-config file, not in the function's
	// .vc-config.json. Build Output API associates functions/index.func with
	// functions/index.prerender-config.json by basename.
	if (options.isr) {
		/** @type {Record<string, unknown>} */
		const prerender = { expiration: options.isr.expiration };
		if (options.isr.bypassToken) prerender.bypassToken = options.isr.bypassToken;
		if (options.isr.allowQuery !== undefined) prerender.allowQuery = options.isr.allowQuery;
		write(
			join(output_dir, 'functions', 'index.prerender-config.json'),
			JSON.stringify(prerender, null, '\t'),
		);
	}

	write(join(func_dir, '.vc-config.json'), JSON.stringify(vc_config, null, '\t'));

	// 3. Routing config.
	write(
		join(output_dir, 'config.json'),
		JSON.stringify(generate_vercel_config(options), null, '\t'),
	);

	log(`[@octanejs/adapter-vercel] Build Output written to ${VERCEL_OUTPUT_DIR} (${runtime})`);
}
